### ISSUE TITLE
Bytes being transformed to a numpy array with dtype=object in coordinates

### ISSUE THREAD

**Issue by ceridwen** [pydata/xarray#1003]
This relates again to this code: https://gist.github.com/ceridwen/21f86231e86b72bf18fcc16fcee01548 .

``` python
dataset = transform.read_games(['2016-06.json'])
>>> dataset
<xarray.Dataset>
Dimensions:        (event: 91, faction: 20, game: 2643, round: 7)
Coordinates:
  * round          (round) int64 0 1 2 3 4 5 6
  * faction        (faction) |S14 b'acolytes' b'alchemists' b'auren' ...
  * event          (event) |S26 b'action:ACT1' b'action:ACT2' b'action:ACT3' ...
  * game           (game) object b'005Stedda' b'006St3dda' b'00s10' b'0106' ...
Data variables:
    player5        (game) |S17 b'Stedda' b'Muchacho' b'' b'modong' b'' b'' ...
    player3        (game) |S19 b'Emoht' b'Xrystofer' b'' b'runrun57' ...
    date           (game) datetime64[ns] 2016-06-07T22:30:47 ...
    player1        (game) |S22 b'ocollard' b'BillyMirmidon' b'00' b'Animax' ...
    player2        (game) |S21 b'Mies730' b'Stedda' b'romance90' ...
    scoring_tiles  (game, round) |S6 b'' b'SCORE9' b'SCORE4' b'SCORE2' ...
    player4        (game) |S20 b'Deryl' b'CarpalTunnel' b'' b'Zak_tak' b'' ...
    events         (game, faction, event, round) float16 nan nan nan nan nan ...
    players_count  (game) int8 5 5 2 5 3 3 4 4 4 4 4 4 5 5 5 5 5 5 5 3 3 4 2 ...
```

Notice that the dtype for the coordinate game is `object`, even though `games` is a list of bytes, that is `{type(e) for e in names}` evaluates to `{bytes}`.

**Comment by shoyer** [comment]
The problem here is related to concatenating along the `game` axis. We use pandas to concatenate coordinate variables with their data saved as a `pandas.Index` (like the  `game` variable), but Pandas (and NumPy) does not have a dtype for variable-length strings, so this ends up getting converted to `dtype=object`.

We could probably add something to fix the dtype back after doing the concatenation and/or concatenate string indexes with NumPy instead of pandas.
