### ISSUE TITLE
developer workflow

### ISSUE THREAD

**Issue by qAp** [pydata/xarray#1069]
I want to make a change to `xarray.plot.plot.line` and use that change, what is the best way of going about this?  I was thinking that I could

(1) Fork xarrary on Github
(2) Make a local clone of the fork
(3) Edit the code for the function `line` in 'plot/plot.py'

Then?  I already use xarray that is installed with conda: `conda install xarray` .

Sorry need to ask because never done this before.

**Comment by fmaussion** [comment]
Hi, if you want to change something in xarray and use it instead of the original one you should uninstall it, and then install it in dev mode. From the xarray root directory:
```
pip install -e .
```
**However**, in that case this is probably **not** the best thing to do. Since the logic for xarray's line plot is extremely [simple](https://github.com/pydata/xarray/blob/master/xarray/plot/plot.py#L129-L175), in that case you'd better make you're own function out of it and call it instead. I.e. ``my_plot_func(dataarray)`` instead of ``datarray.plot()``.

Finally, you may want to consider using an [accessor](http://xarray.pydata.org/en/stable/internals.html#extending-xarray) for this purpose. You will then be able to write something like:

```python
datarray.qAp.plot()
```

**Comment by qAp** [comment]
I used an accessor to add more options for plotting 1d arrays; main ones demonstrated here:
https://github.com/qAp/climatools/blob/master/climatools/examples/1d_plotting/plotting_1d_DataArray.ipynb

Do you think these would be useful in xarray?  I guess they save time for people who are not familiar with matplotlib...

**Comment by fmaussion** [comment]
Thanks for these examples! 

I cannot speak for the xarray developers, but my felling is that these options are too specific. Furthermore, doing the same things would require only one or two lines of code on top of ``xarray.plot()``. 

However, I understand the argument that people who don't know matplotlib might find this useful, thought. The figsize kwarg could be a useful addition for example.

**Comment by shoyer** [comment]
A size argument would definitely be useful (see https://github.com/pydata/xarray/pull/637, which needs somebody to finish it up). I could see log scale options also being useful, though I would stick with the names used by pandas for consistency (e.g., `logx=True`)

**Comment by fmaussion** [comment]
Right, I forgot about https://github.com/pydata/xarray/pull/637 . I'll see what I can do.
