### ISSUE TITLE
Is it possible to modify a variable value in netCDF file?

### ISSUE THREAD

**Issue by wqshen** [pydata/xarray#1117]
Use netCDF4 package, one can modify the netCDF file variable as follow,

```python
import netCDF4
dset = netCDF4.Dataset('test.nc', 'r+')
dset['varname'][:] = 0
dset.close()
```

Is it possible in xarray?

**Comment by shoyer** [comment]
I'm afraid this is not possible. You'll need to write out a new file on disk if you want to do this sort of thing with xarray.

This was an intentional choice -- maintaining the consistency of a netCDF file in each incremental Dataset operation (especially more complex operations like adding a variable) is a good deal more complex than updating xarray's internal data structures in Python.
