### ISSUE TITLE
pass projection argument to plt.subplot when faceting with cartopy transform

### ISSUE THREAD

**Issue by vnoel** [pydata/xarray#1201]
I have a `data` 3D DataArray with `Time`, `Latitude` and `Longitude` coordinates.

I want to plot maps of this dataset, faceted by Time. The following code

```
import cartopy.crs as ccrs
proj = ccrs.PlateCarree()
data.plot(transform=proj, col='Time', col_wrap=3, robust=True)
```

fails with

``` 
ValueError: Axes should be an instance of GeoAxes, got <class 'matplotlib.axes._subplots.AxesSubplot'> 
```

this is because to plot with a transform, the axes must be a GeoAxes, which is done with something like `plt.subplot(111, projection=proj)`. The implicit subplotting done when faceting does not do that. To make the faceting works, I had to do

```
import cartopy.crs as ccrs
proj = ccrs.PlateCarree()
data.plot(transform=proj, col='Time', col_wrap=3, robust=True, subplot_kws={'projection':proj})
```

I propose that, when plot faceting is requested with a `transform` kw, the content of that keyword should be passed to the subplot function as a `projection` argument automatically by default. If a projection is provided explicitely like in the call above, use that one.

**Comment by shoyer** [comment]
This seems totally reasonable to me, and would be nice because it would improve the consistency between facetted and non-facetted plotting.

Going even further, we might even default to `projection=ccrs.PlateCarree()` if a cartopy transform is provided (see https://github.com/SciTools/cartopy/issues/645).

@fmaussion @jhamman any opinions?

**Comment by fmaussion** [comment]
> This seems totally reasonable to me, and would be nice because it would improve the consistency between facetted and non-facetted plotting.

I don't really understand what you mean here. Neither facetted nor non-facetted plots have any logic to greate geoaxes automatically.

Otherwise, yes, I think that any logic making working with cartopy a little easier would be a good addition. The logic creating the axes is located [here](https://github.com/pydata/xarray/blob/master/xarray/plot/utils.py#L231)

**Comment by shoyer** [comment]
> I don't really understand what you mean here. Neither facetted nor non-facetted plots have any logic to greate geoaxes automatically.

Oops, I was indeed mixed up.

If we add a `projection` argument for faceted plots, we should certainly add it for non-faceted plots, too.

**Comment by vnoel** [comment]
I am confused. 

I planned to identify the plotting function that accepted the `transform` keyword (used in the code sample above), and add its value in `subplot_kws` if it wasn't already.

However it looks like no xarray code contains the `transform` keyword. However I definitely can use it in calls to `plot()`. I don't understand what is going on. Can someone enlighten me?

**Comment by fmaussion** [comment]
> However it looks like no xarray code contains the transform keyword. However I definitely can use it in calls to plot(). I don't understand what is going on. Can someone enlighten me?

Yes, this is what I meant with xarray not being directly "cartopy aware". The reason is that xarray intends to be a general library, and tries to avoid defining too many keyword arguments in order to avoid confusion. However, xarray passes along any kw argument you want to the underlying mpl plot function (https://github.com/pydata/xarray/blob/master/xarray/plot/plot.py#L379). You'll have to catch it first, either from the ``kwargs`` dict or by adding your own to the signature (the latter being recommended only if necessary, for the reason I mentioned above)

**Comment by vnoel** [comment]
I don't understand what you mean by 'adding you own to the signature'. Adding my own what to what signature?

**Comment by fmaussion** [comment]
> I don't understand what you mean by 'adding you own to the signature'. Adding my own what to what signature?

;-) I meant adding your own _keyword argument_ to the _function's signature_

**Comment by mathause** [comment]
I think this can be closed, as the following works:

```python
import cartopy.crs as ccrs
import xarray as xr

proj = ccrs.PlateCarree()

ds = xr.tutorial.open_dataset("air_temperature")
da = ds.air.isel(time=slice(None, 3))
da.plot(transform=proj, col='time', subplot_kws={'projection':proj})
```

**Comment by dcherian** [comment]
We should add this to the docs then

**Comment by mathause** [comment]
I think the second example shows this: http://xarray.pydata.org/en/stable/plotting.html#maps

Related: #3169
