### ISSUE TITLE
Enhance setup.py metadata with extras_require

### ISSUE THREAD

**Issue by ghisvail** [pydata/xarray#1210]
More of a suggestion than anything. It took me some time to collect all the optional dependencies `xarray` were potentially relying on (`bottleneck`, `scipy`, `netCDF4`...). Perhaps, this information could be added to the setup.py metadata inside `extras_require`. One that come straight to my mind is:

```python
extras_require = [
    'plot': ['matplotlib'],
    ...
]

**Comment by shoyer** [comment]
Thanks for the feedback.

This is a little tricky to do unambiguously for most optional dependencies, because in most cases something isn't strictly required. For example, there are four different libraries you can use for reading netCDF files (netCDF4, scipy, h5netcdf and pynio). It's not clear which if any should be included.

In the case of plotting and dask support, each of these do have required dependencies (matplotlib and dask.array, respectively), but I'm not sure how much value it adds to specify `extras_require` with a list of only one dependency each.
