### ISSUE TITLE
Dask distributed integration tests are failing on master

### ISSUE THREAD

**Issue by shoyer** [pydata/xarray#1292]
For example:
```
_______________ test_dask_distributed_integration_test[netcdf4] ________________
loop = <tornado.platform.epoll.EPollIOLoop object at 0x7f4c45739710>
engine = 'netcdf4'
    @pytest.mark.parametrize('engine', ENGINES)
    def test_dask_distributed_integration_test(loop, engine):
        with cluster() as (s, _):
>           with distributed.Client(('127.0.0.1', s['port']), loop=loop):
E           KeyError: 'port'
```

@mrocklin did you change the API for this?

**Comment by mrocklin** [comment]
Yes.  This was changed in 0.14.0.  Correct use is as follows:

```python
with dask.distributed.Client(s['address'], loop=loop):
    ...
```

This is because we're now supporting new transport mechanisms, not all of which have ports.  In particular you may find https://github.com/dask/distributed/pull/919 of interest, which should allow the distributed scheduler to run well with the client and workers all in the same shared memory process.  In this case we use queues, which don't have ports.
