### ISSUE TITLE
Opening multiple OpenDAP paths with open_mfdataset fails

### ISSUE THREAD

**Issue by nordam** [pydata/xarray#1302]
I'm trying to open multiple NetCDF files hosted on OpenDAP on a THREDDS server, using `xarray.open_mfdataset()`, but I get an error. If I open only one file (but still with `open_mfdataset()`), it works, if I open two, it doesn't.

For example, this works just fine:

    import xarray as xr
    chunks = {'time' : 1, 'depth' : 1}
    paths  = [
        'http://thredds.met.no/thredds/dodsC/fou-hi/norkyst800m-1h/NorKyst-800m_ZDEPTHS_his.an.2017022000.nc',
        ]
    d = xr.open_mfdataset(paths, chunks = chunks)

while this doesn't:

    import xarray as xr
    chunks = {'time' : 1, 'depth' : 1}
    paths  = [
        'http://thredds.met.no/thredds/dodsC/fou-hi/norkyst800m-1h/NorKyst-800m_ZDEPTHS_his.an.2017022000.nc',
        'http://thredds.met.no/thredds/dodsC/fou-hi/norkyst800m-1h/NorKyst-800m_ZDEPTHS_his.an.2017022100.nc',
        ]
    d = xr.open_mfdataset(paths, chunks = chunks)

I'm running this in a jupyter notebook, and I don't get any output in the notebook, it just keeps running, while in the terminal it prints the following 

    CURL Error: Failed initialization
    curl error details:
    CURL Error: Failed initialization
    CURL Error: Failed initialization
    CURL Error: Failed initialization
    syntax error, unexpected WORD_WORD, expecting SCAN_ATTR or SCAN_DATASET or SCAN_ERROR
    context: !�zF^@L������@L�Ы�J�@L�y@L�G`Lp@L�X�ڭ@L�/��a@L���@L��{�:@@L�Hl�D@L���i@L�f���@L�>����@L�x��f@L��DA�h@L�����@L��ڭ�M@L�u���@M
    CURL Error: Failed initialization
    curl error details:
    CURL Error: Failed initialization
    CURL Error: Failed initialization
    syntax error, unexpected WORD_WORD, expecting $end
    context: Dataset { Structure { Float64 lon[Y = 902][X = 2602]; } lon;} fou-hi/norkyst800m-1h/NorKyst-800m_ZDEPTHS_his.an.2017022100.nc;Data^:
    CURL Error: Failed initialization
    CURL Error: Failed initialization
    CURL Error: Failed initialization
    syntax error, unexpected WORD_WORD, expecting SCAN_ATTR or SCAN_DATASET or SCAN_ERROR
    context: �@��&��D^@�h�N�{@��I$�@B�

and from there on, it just degenerates into printing more garbage.

Isn't this supposed to work just fine?

I'm not sure if this is relevant, as I don't know if xarray and netCDF4 use the same backends, but in any case, the following works just fine. At least that suggests the problem isn't at the server side.

    import netCDF4 as nc
    d = nc.MFDataset([
        'http://thredds.met.no/thredds/dodsC/fou-hi/norkyst800m-1h/NorKyst-800m_ZDEPTHS_his.an.2017022000.nc',
        'http://thredds.met.no/thredds/dodsC/fou-hi/norkyst800m-1h/NorKyst-800m_ZDEPTHS_his.an.2017022100.nc',
    ])

I'm running xarray version 0.9.1, and netCDF4 version 1.2.4, and python 3.5.1, all installed with Anaconda, on a Mac.

**Comment by jonasghini** [comment]
Full disclosure, I am working with the same project as OP, but I am using a Linux machine (Ubuntu 16.04 LTS), having gotten the same package versions as OP, with Python 3.5.1 from Anaconda.

The problem is reproducible also on my machine, and I've done some more digging:

Tracing the different functions invoked from the first call to open_mfdataset() goes like this:
open_mfdataset()
-> auto_combine()
-> _auto_concat()
-> concat()
-> _dataset_concat()
-> _calc_concat_over()
-> differs()
-> equals()

Now, within the equals(), xarray tests for equality, and is """True if two DataArrays have the same dimensions, coordinates and  values; otherwise False."""

With the example files OP tests for, all calls to equals() works fine until it reaches the variable "lat" (long name: latitude) (note that I am not sufficiently versed in these kinds of datasets to tell if "lat" is a variable or a coordinate, but at least it is treated as different than, say, "X", "Y" and "time".). Once the equals() function is invoked to tell if dataset[1:] is equal to dataset[0], it starts spitting out the CURL error.

This information does not illuminate the problem for me, but perhaps for any of you.

**Comment by shoyer** [comment]
Does it work to load one of these single datasets completely into memory, e.g., by calling `.load()`?

There might be a general issue with loading the `"lat"` variable that only appears with open_mfdataset because it does the check explicitly.

**Comment by jonasghini** [comment]
Here I've got some more info:

1) Directly pertaining to your question, shoyer, with,
```python
d = xr.open_mfdataset([
	'http://thredds.met.no/thredds/dodsC/fou-hi/norkyst800m-1h/NorKyst-800m_ZDEPTHS_his.an.2017022000.nc',
])
d.load()
```
I get the same `CURL Error: Failed initialization`

However, skipping `.load()` solves that particular problem when having only a single file in `xr.open_mfdataset()`, as this works fine:
```python
d = xr.open_mfdataset([
	'http://thredds.met.no/thredds/dodsC/fou-hi/norkyst800m-1h/NorKyst-800m_ZDEPTHS_his.an.2017022000.nc',
])
fu = RectBivariateSpline(d.X[0:].values, d.Y[675:].values, d.u[0, 0, 675:, :].values.T)
```
If I skip the `.values` I get a `Request too big` error, but I do not know if it is SciPy or xarray that raises that error.

2) If I download several of the thredds*.nc files to my local machine, and then use `xr.open_mfdataset('DataSets/*.nc')` it all works beautifully: I do not get CURL errors, nor do I need to use `.values` in my interpolator call.

3) I tried following the call to `.load()` -> `dask.array.compute(*lazy_data.values())` -> `results = get(dsk, keys, **kwargs)`. At this point it spits out CURL errors. Dask != xarray, so perhaps the error is not with the xarray package at all.

4) When using `open_mfdataset()` to open a single local file, and then `.load()`-ing it, I get a memory error from dask, even if, by number, the file I am trying to load should fit in my computer's memory. This is ''an issue with load()'', but may not be related at all to the remote access problem we are trying to figure out.

5) I asked the people hosting the files if perhaps there were some access restrictions that might be the issue here, but they were not aware of anything. 

What conclusions to draw from this I don't know. I'll make another pass later and see if perhaps I can identify exactly what is different when loading remote VS local files, in case that could tell us something. At least it is clear that when calling the `.load()` directly, my computer does play nice, although it seems to break for different reasons when loading remote VS local files. Also, referring back to my previous comment, it does not seem that the single VS several file openings break at the same point either, given that the `equals()` function does not call `.load()`, although perhaps it does something similar in order to do the check.

**Comment by nordam** [comment]
Regarding the `Request too big` error, I believe this comes from the server. The paths in the examples above are publicly available files from the Norwegian Meteorolgical institute, and I believe they cap downloading via OpenDAP at 500 MB per request (though you can download the NetCDF files via http, and these are all larger than 500 MB, see http://thredds.met.no/thredds/catalog/fou-hi/norkyst800m-1h/catalog.html ).
