### ISSUE TITLE
Choose time units in output netcdf

### ISSUE THREAD

**Issue by rafa-guedes** [pydata/xarray#1324]
Is there any way to define the units in output netcdf created from `to_netcdf` method without having to manually convert the time objects into floats for example? It could maybe be handy if the units attribute of time coordinate could be modified and the modified value (if CF-compliant) used for encoding time in the output netcdf. Currently, `to_netcdf` raises ```ValueError: Failed hard to prevent overwriting key 'units'``` if the attribute is modified.

Thanks

**Comment by shoyer** [comment]
Yes, you can control this by setting `encoding`, e.g., `time.encoding['units'] = 'days since '1900-01-01'` 
http://xarray.pydata.org/en/stable/io.html#time-units

It looks like this error message is not very helpful currently -- a PR to improve it would be appreciated!

**Comment by rafa-guedes** [comment]
Thanks!

**Comment by mmartini-usgs** [comment]
I think I have a similar problem.

I have a netCDF file with CF time.  I'm trying to add two variables with a different kind of time (EPIC time, time2).  These variables should not be datetime.  They should be ordinary numbers.

Even when I don't include any units, it chokes on "units".  Even with encoding = None
ValueError: Failed hard to prevent overwriting key 'units'
The gist is here:  https://gist.github.com/anonymous/4614dfb55778cd0d51427daf6503cd8c

It's a time specific thing, because if I do the same operation with a different variable in the same file (read a variable, do something with it, then save it) it works fine.  One clue is that it still carries the attributes (generally desired behavior) to the new file.  But my EPIC time and time2 above, if they NOT datetime and have NO attributes... should work the same way.

This could be my misunderstanding of xarray and time operations, I'm a python newbie, if so I would appreciate someone setting me straight.  It's preventing me from using xarray.

**Comment by shoyer** [comment]
@mmartini-usgs The here comes up because your `time` variables have dtype `datetime64`. There are two ways to handle this:
- If you don't want xarray to convert from datetime64 to numbers when saving the netCDF file, you need to convert the data yourself to a float or integer array.
- If you do want to make use of xarray's automated conversion, you need to specify units in `encoding` instead of `attrs`.

If something else seems to be going on, please share the result of calling `.info()` on your dataset.

**Comment by mmartini-usgs** [comment]
Thanks - It turns out the workaround is to open the file with decoding_times = False

Is this a bug, or a feature?

In the notebook, those variables called time and time2 are not datetime objects (I demonstrate that).   In fact, there are no datetime objects in the Notebook's scope, unless you count the CF time variable that is part of the open Dataset.  And yet, time and time2 seem to be treated as such when the dataset is written to a file.  Or, is it that the CF time in the Dataset is getting re-encoded somehow in spite of encoding=None?  Why would that fail?  Would you explain what is going on here?

I have updated my gist with the .info() information here:  
https://gist.github.com/anonymous/ff055f732029585605b965f282685d73

**Comment by rvalenzuelar** [comment]
Hello,

I'm having similar issues. However, I'm creating a dataset from a dict (data are packed in Matlab file).

The dataset is ```ds_ivt``` and I have tried:
```python
ds_ivt.time.encode['units'] = 'days since 1900-01-01'
```
and

```python
ds_ivt.to_netcdf('ds_ivt.nc',encoding={'time':{'units':'days since 1900-01-01'}})
```
The ```.info()``` method retrieves:

```bash
ds_ivt.info()
xarray.Dataset {
dimensions:
	lat = 161 ;
	lon = 291 ;
	time = 1460 ;
variables:
	float32 lat(lat) ;
		lat:units = degrees ;
	float32 lon(lon) ;
		lon:units = degrees ;
	datetime64[ns] time(time) ;
		time:units = days since 1900-01-01 ;
	float32 iqu(time, lat, lon) ;
		iqu:units = kg m-1 s-1 ;
	float32 iqv(time, lat, lon) ;
		iqv:units = kg m-1 s-1 ;
// global attributes:
}
```

**Comment by gauteh** [comment]
Does this approach work anymore? I can't seem to set either encoding or attrs, xarray complains that the units is attempted to be overwritten on write.

**Comment by gauteh** [comment]
Hi, while trying to reproduce this I realized I added the unit encoding to all other variables as well (because of using the same subdict when creating the encoding dict).
