### ISSUE TITLE
Setting attributes to multi-index coordinate

### ISSUE THREAD

**Issue by rafa-guedes** [pydata/xarray#1366]
I can't seem to be able to define attributes to "virtual" coordinates from multi-index coordinates. Taking from the exemple from the docs:
```python
In [1]: import numpy as np
In [2]: import pandas as pd
In [3]: import xarray as xr
In [4]: midx = pd.MultiIndex.from_arrays([['R','R','V','V'], [.1,.2,.7,.9]], names=('band','wn'))
In [5]: mda = xr.DataArray(np.random.rand(4), coords={'spec': midx}, dims='spec')

# Setting up attrs to the full coordinate works:
In [6]: mda['spec'].attrs
Out[6]: OrderedDict()
In [7]: mda['spec'].attrs = {'spec_attr': 'some_attr'}
In [8]: mda['spec'].attrs
Out[8]: OrderedDict([('spec_attr', 'some_attr')])

# Setting attrs to the virtual coordinate does not produce any effect:
In [9]: mda['band'].attrs
Out[9]: OrderedDict()
In [10]: mda['band'].attrs = {'band_attr': 'another_attr'}
In [11]: mda['band'].attrs
Out[11]: OrderedDict()
```

**Comment by shoyer** [comment]
This is a little tricky: there's only a single array `Variable` object (the MultiIndex), so we can't save `attrs` on any of the levels. But xarray doesn't raise an error in this case, because it's assigning to the temporary `mda['band']` object, which immediately gets thrown away. There would be the same issue if you tried to assign an attribute to `ds['time.dayofyear']`.

I don't think Python syntax gives us any good options for identifying these cases. It's essentially the same problem as assigning to an indexing result, e.g., `ds.sel(...).attrs = ...`, though it's less obvious here since you're doing indexing, not a method call.

At the very least we could document that this doesn't work.

CC @benbovy in case he has any other ideas.

**Comment by rafa-guedes** [comment]
That makes sense thanks for explaining @shoyer

**Comment by shoyer** [comment]
This will be eventually fixed as part of https://github.com/pydata/xarray/issues/1603

**Comment by benbovy** [comment]
#5636 is a 1st step towards representing multi-index levels in separate `Variable` objects having their own user-defined attributes. We'll also be able in theory to propagate the attributes through operations like `sel` and maybe other operations like alignment.

The features added in #5636 will be integrated in a follow-up PR.
