### ISSUE TITLE
Changing projections under plot()

### ISSUE THREAD

**Issue by CommonClimate** [pydata/xarray#1397]
Hi,
i was giving a spin to the plot functionality, tinkering with @rabernat 's code (xarray_multidimensional_coords.ipynb). 

That notebook works flawlessly with my setup (Mac OS 10.12.4, Python 3.5, cartopy 0.1.5, numpy 1.11.3, pandas version :  0.19.2, xarray version   :  0.9.1), but if I change the projection from PlateCarree() to Robinson(), the map never shows up. What am I doing wrong?

**Comment by shoyer** [comment]
What exactly did you type?

Note that even if you set `projection=Robinson()` you still need `transform=ccrs.PlateCarree()` (e.g., see https://github.com/SciTools/cartopy/issues/645).

**Comment by fmaussion** [comment]
I don't have this problem. did you use the code from the documentation?

http://xarray.pydata.org/en/latest/examples/multidimensional-coords.html

**Comment by CommonClimate** [comment]
@shoyer thanks for this tip. As you say, having to specify the transform is prodigiously unintuitive for a first-time cartopy user (my case). Unfortunately, I get the problem with or without applying transform=ccrs.PlateCarree(). 

@fmaussion yes, that is precisely the code I used, switching PlateCarree() for Robinson() in cell 16. 

The only output I get when I do this is the bottom legend; the rest of the plot vanishes.

**Comment by fmaussion** [comment]
This is what I get:

```python
import xarray as xr
import cartopy
import cartopy.crs as ccrs
import matplotlib
import matplotlib.pyplot as plt
%matplotlib inline

print(xr.__version__)
print(cartopy.__version__)
print(matplotlib.__version__)

ds = xr.tutorial.load_dataset('rasm')
plt.figure(figsize=(14, 4));
ax = plt.axes(projection=ccrs.Robinson());
ds.Tair[0].plot.pcolormesh(ax=ax, transform=ccrs.PlateCarree(), 
                           x='xc', y='yc', add_colorbar=False);
ax.coastlines();
plt.tight_layout();
```

```
0.9.5-1-gab4ffee
0.14.2
2.0.0
```

![index](https://cloud.githubusercontent.com/assets/10050469/25653642/1a45d776-2fee-11e7-88d6-db0b2f0d5af3.png)

**Comment by rabernat** [comment]
When I put together the tutorial, I remember that the Robinson projection was the only one that worked reliably. But that was more than a year ago--hopefully updating package versions can fix the issue.

**Comment by CommonClimate** [comment]
@fmaussion thanks, I think I know what the problem is: the last command I was using was `ax.set_ylim([0,90])`, not `plt.tight_layout()`. With the latter, everything shows up properly with the correct projection. I guess I was working with an older version of the notebook, which had the former command, not the latter. 

Bonus question for @shoyer : it's simple to add the colorbar, but not easy to make it horizontal, for instance. Is the idea is that if a lot of customization is desired, users should go with more direct cartopy commands, rather than xarray plotting tools, which are useful for quick checks, but not publication-quality figures?

thanks

**Comment by fmaussion** [comment]
> it's simple to add the colorbar, but not easy to make it horizontal

You can try:

```
ds.Tair[0].plot.pcolormesh(ax=ax, transform=ccrs.PlateCarree(), x='xc', y='yc', 
                           cbar_kwargs={'orientation':'horizontal'});
```

>  xarray plotting tools, which are useful for quick checks, but not publication-quality figures?

Yes, as a general purpose tool xarray will try to avoid the proliferation of keyword arguments. If you have very specific needs you might need to tweak the plots yourself. Fortunately, this is easy to do on top of xarray since you can control the axes, plots, and so on.

We could add more advanced examples to the docs though (for example in the gallery I had no time to add yet :( )

**Comment by CommonClimate** [comment]
Thanks Fabien, this is helpful. It would be great to see how the output of the `plot()` function can be broadcast to axes or handles, so that they can be manipulated at will. Right now, typing  
`a = s.Tair[0].plot.pcolormesh(ax=ax, transform=ccrs.PlateCarree(), x='xc', y='yc', 
                           cbar_kwargs={'orientation':'horizontal'});`
returns a complex object that is a bit forbidding for a first-time user without any example in the doc. A simple example would go a long way, but I understand that everything takes time and no-one is getting paid for this!
cheers
Julien

**Comment by rabernat** [comment]
> A simple example would go a long way

@CommonClimate, you are now the ideal contributor to create such an example for the docs. 😉

**Comment by CommonClimate** [comment]
Without a doubt - once I figure out how to do it!

**Comment by fmaussion** [comment]
What is it exactly what you are trying to do?

**Comment by CommonClimate** [comment]
Customizing legend, fonts, title, things like that. I'm slowly getting through it - mostly because I am new to cartopy and not that experienced with matplotlib overall. 

The biggest trouble I have is with tightening the space between the map and the colorbar at the bottom, but this looks like a cartopy/mpl question, not an xarray question, so I should quit pestering you guys.

**Comment by darothen** [comment]
> The biggest trouble I have is with tightening the space between the map and the colorbar at the bottom, but this looks like a cartopy/mpl question, not an xarray question, so I should quit pestering you guys.

You just need to pass the "pad" argument to `cbar_kwargs`. 

The trickier problem is that sometimes cartopy can be a bit unpredictable in controlling the size and aspect ratio of axes after you've plotted maps on them. You can force a plot to respect the aspect ratio you use when you construct an axis by using the keyword `aspect="auto"`, but it can be a bit difficult to get this to work in xarray sometimes. But at the end of the day, it's not a big deal to hand-craft a publication-quality figure once you know the rough gist of what you want to go on it - and xarray's tools are already great for that.

**Comment by fmaussion** [comment]
@darothen did you find out how to control the map extent in facetgrids? See this example:

```python
p = ano.T2M.plot(col='month', col_wrap=4, transform=ccrs.PlateCarree(),
                            subplot_kws={'projection': ccrs.PlateCarree()});
for ax in p.axes.flat:
    ax.add_feature(cartopy.feature.BORDERS)
    ax.add_feature(cartopy.feature.COASTLINE)
    ax.set_extent([70, 100, 25, 40])
```
Cartopy basically ignores my ``extent'' since it wants to make the plots more quadratic than they should:

![index](https://cloud.githubusercontent.com/assets/10050469/25706592/28782a94-30e1-11e7-8f4d-06f5c8beae61.png)

**Comment by darothen** [comment]
@fmaussion What happens if you add `aspect="auto"` to **subplot_kws**? 

I'm tempted to have us move this discussion to StackOverflow (for heightened visibility), but I suspect there might actually be a bug somewhere in the finalization of the faceting that undoes the specifications you pass to the initial subplot constructor.

**Comment by fmaussion** [comment]
``aspect='auto'`` does "work", but it looks ugly because it doesn't preserve aspect ratio:

![index](https://cloud.githubusercontent.com/assets/10050469/25707109/cd687ddc-30e2-11e7-975e-a4909a2ff2e0.png)

The default is ``aspect='equal'``, which is good for the maps geometry but it shouldn't be ignored by the axes of the facetgrid, I think we have to do something on the xarray side here, unless there is a way to preserve the aspect ratio already. I'll dig into this.

**Comment by darothen** [comment]
Cool; please keep me in the loop if you don't mind, because I also have an application which I'd really like to just be able use the built-in faceting for rather than building my plot grids manually. 

A good comparison case is to perform the same plots (with the same set aspect/size/ratio at both the figure and subplot level) but just don't use the Cartopy transformations. In these cases, I have all the control that I would expect. There are also important differences between `pcolor`ing and `imshow`ing which would be useful to understand. At a minimum, we should deliver back to **xarray** some improved documentation discussing handling subplot geometry during faceting.

**Comment by fmaussion** [comment]
OK, I've had success with  ``ax.set_aspect('equal', 'box-forced')``:

```python
p = ano.T2M.plot(col='month', col_wrap=4, transform=ccrs.PlateCarree(),
                 subplot_kws={'projection': ccrs.PlateCarree()});
for ax in p.axes.flat:
    ax.add_feature(cartopy.feature.BORDERS)
    ax.add_feature(cartopy.feature.COASTLINE)
    ax.set_extent([70, 100, 25, 40])
    ax.set_aspect('equal', 'box-forced')
```
![index](https://cloud.githubusercontent.com/assets/10050469/25708362/91153998-30e6-11e7-92c6-7d015461e43c.png)

Note that the result will look better if you set ``aspect`` in xarray's facetgrid first, since it will decide on a cleverer figsize based on this information:

```python
p = ano.T2M.plot(col='month', col_wrap=4, transform=ccrs.PlateCarree(),
                 aspect=ds.dims['lon']/ds.dims['lat'],
                 subplot_kws={'projection': ccrs.PlateCarree()});
for ax in p.axes.flat:
    ax.add_feature(cartopy.feature.BORDERS)
    ax.add_feature(cartopy.feature.COASTLINE)
    ax.set_extent([70, 100, 25, 40])
    ax.set_aspect('equal', 'box-forced')
```

![index2](https://cloud.githubusercontent.com/assets/10050469/25708485/e95323a4-30e6-11e7-8f0c-bbd047f03ea8.png)
