### ISSUE TITLE
time.units truncated when saving to_netcdf

### ISSUE THREAD

**Issue by mathause** [pydata/xarray#1449]
When I manually specify the `units` attribute for time, and then save the Dataset `to_netcdf` the string is truncated. See exaple

    import pandas as pd
    import xarray as xr

    time = pd.date_range('2000-01-01', '2000-01-31', freq='6h')
    ds = xr.Dataset(coords=dict(time=time))

    units = 'days since 1975-01-01 00:00:00'
    calendar = 'gregorian'
    encoding=dict(time=dict(units=units, calendar=calendar))

    ds.to_netcdf('test.nc', format='NETCDF4_CLASSIC', encoding=encoding)

    ! ncdump -h test.nc
    # time:units = "days since 1975-01-01" ;

Some programs seem to require the hours to be present to interpret the time properly (e.g. panoply). When specifying the hour, a 'T' is added.

    units = 'days since 1975-01-01 01:00:00'

    ! ncdump -h test.nc
    # time:units = "days since 1975-01-01T01:00:00" ;

When xarray defines the `time.units` it works fine.

    ds = xr.Dataset(coords=dict(time=time))
    ds.to_netcdf('test.nc', format='NETCDF4_CLASSIC',)

    ! ncdump -h test.nc
    # time:units = "hours since 2000-01-01 00:00:00" ;

xarray version 0.9.6

**Comment by shoyer** [comment]
I didn't realize that some applications would have trouble with time-offsets without hours, but we can easily change this. The logic in controlled by [these](https://github.com/pydata/xarray/blob/aeb4108b1f39cde2bac765ca58c70b5011b188c5/xarray/conventions.py#L208) [lines](https://github.com/pydata/xarray/blob/aeb4108b1f39cde2bac765ca58c70b5011b188c5/xarray/conventions.py#L233) (called [from here](https://github.com/pydata/xarray/blob/aeb4108b1f39cde2bac765ca58c70b5011b188c5/xarray/conventions.py#L280-L283)), as you can see use different helper functions for formatting the time-offset string -- either `format_timestamp(x)` or `str(pd.Timestamp(x))`.

Either way, you certainly have identified as inconsistency. It doesn't make sense to "clean-up" manually specified time units to add the "T" but not include that in our auto-generated time units. We should probably switch our time units to include "T" because that's ISO-8601, and I'm no longer sure why we normalize time units at all rather than just writing them unmodified.

**Comment by mathause** [comment]
Well, not specifying the time would conform to the CF conventions... (http://cfconventions.org/cf-conventions/v1.6.0/cf-conventions.html#time-coordinate), so this might be an issue in panoply.

**Comment by dcherian** [comment]
still an issue...

**Comment by guziy** [comment]
Hi, I have a similar problem. We have model runs starting at 0Z and 12Z so the ones starting at 0Z don't have time in the unit string, which is not consistent... Is there a workaround?

**Comment by kmuehlbauer** [comment]
Given the age of this issue this can be discussed at the very recent issue #8137.
