### ISSUE TITLE
groupby should still squeeze for non-monotonic inputs

### ISSUE THREAD

**Issue by shoyer** [pydata/xarray#1460]
We can simply use `argsort()` to determine `group_indices` instead of `np.arange()`:
https://github.com/pydata/xarray/blob/22ff955d53e253071f6e4fa849e5291d0005282a/xarray/core/groupby.py#L256

**Comment by dsh0** [comment]
I'd like add that the groupby docstring never mention that squeezing only works for monotonic index (which is an unreasonable restriction in the first place)

**Comment by shoyer** [comment]
A better long term solution is probably removing "squeeze" from groupby entirely: https://github.com/pydata/xarray/issues/2157

**Comment by relativistic** [comment]
Just wanted to mention I just got tripped up by this. It took me a long time to figure out why my code wasn't working like the groupby example. It took a lot of trial and error to figure out the problem was one of my dims wasn't sorted. It was a categorical string-based dim that you wouldn't think to sort.

I personally find squeeze a convenient option when applying map. FWIW, it would break some of my code if the default behavior were to change (I'm using map to apply  some mathematical code that expects 2d matrix input. The DataArray is 3D, where the third dimension is a label for each 2d matrix). Easy to adapt the code, but I wanted to point out a case where squeeze is what you want.

**Comment by shoyer** [comment]
Well, even if we keep `squeeze` as an option, I think `squeeze=False` would be much more consistent default behavior :)
