### ISSUE TITLE
Rasterio - Attribute Error

### ISSUE THREAD

**Issue by slharris** [pydata/xarray#1466]
I am able to open a tif using rasterio but when I try to open the same tif using rasterio in xarray I receive the following error message:

/Users/slburns/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/xarray/backends/rasterio_.pyc in open_rasterio(filename, chunks, cache, lock)
    141         # CRS is a dict-like object specific to rasterio
    142         # We convert it back to a PROJ4 string using rasterio itself
--> 143         attrs['crs'] = riods.crs.to_string()
    144     # Maybe we'd like to parse other attributes here (for later)
    145 

AttributeError: 'dict' object has no attribute 'to_string' 

Is there some other step I should be doing first?
Thanks

**Comment by ceholden** [comment]
Could you include the version of `rasterio` that you have installed? It's an optional dependency for `xarray`, and so a little tricky to enforce a minimum version number for, but my first guess would be to check the version:

```bash
python -c "import rasterio; print(rasterio.__version__)"
```

At one point in rasterio's development, the CRS information was stored as an simple `dict` instead of a `rasterio.crs.CRS`, which has a `to_string` method. Rasterio has been developing pretty rapidly, and it looks like it had been using a simple `dict` as soon as March, 2016 (version `0.33`). The tests for `xarray` are running against `rasterio=1.0a9` specifically (see [docs/environment.yml](https://github.com/pydata/xarray/blob/e39dae4c4ba83de09bea16ed5b3132ce4e88ba98/doc/environment.yml)), but any of the recent 1.0 alpha releases of `rasterio` will likely work. If your copy of `rasterio` is older than `1.0a[something]`, it might be as simple as upgrading the package.

**Comment by slharris** [comment]
That solved the issue - I should have checked that first!

thank you

**Comment by fmaussion** [comment]
@ceholden do you know when the ``to_crs()`` method was implemented? Should we make ``rasterio>1.0a`` a required dependency?

**Comment by ceholden** [comment]
@fmaussion sorry for the delay. Looks like the switch to an actual `CRS` class happened just before `rasterio=0.36` ([commit](https://github.com/mapbox/rasterio/commit/a7e7cbef6374abc94b46980bc188dba2004d0172)), which was the last `0.x` release before the alphas for `1.0` started up. Previously this `to_string` capability was a function inside of `rasterio.crs`, and now it's just on the `rasterio.crs.CRS` class.

Quite a bit of reorganization happened between `0.36` and `1.0a`, so I'd agree sticking to `rasterio>1.0a` would be best. For specifying the requirement, I guess we would put it in `extra_requires`? Dask does a nice job of this for its various components ([their setup.py](https://github.com/dask/dask/blob/master/setup.py)).

**Comment by fmaussion** [comment]
> I guess we would put it in extra_requires ?

Mh, rasterio should remain an optional dependency. We can however add a version check in the backend and raise an ```ImportError``` if the rasterio version is too old.
