### ISSUE TITLE
Dataset.copy() drops encoding

### ISSUE THREAD

**Issue by crusaderky** [pydata/xarray#1586]
```
ds = Dataset()
ds.encoding = {"unlimited_dims": 'x'}
ds.copy().encoding
{}
```
By looking at dataset.py, there's a lot of calls to ``Dataset._construct_direct`` that omit the encoding. Is it correct to add it in all cases?

**Comment by crusaderky** [comment]
By looking at the code, copy() is the only case where it is proper to pass the encoding to \_construct\_direct, but somebody please confirm

**Comment by shoyer** [comment]
I think this was intentional at one point, but to be honest we never carefully defined the semantics for preserving `encoding` are.

My original thought (along the lines of some of my comments in https://github.com/pydata/xarray/issues/1297), was that we should not propagate `encoding` in cases where it might no longer be valid, so it should be dropped from most operations. Essentially, `encoding` should *only* stay with original files loaded from disk. Hence why it wasn't copied in `.copy()`.

That said, I can see why this rule would be confusing and we haven't done a good job of enforcing it. Possibly a better policy would be "`encoding` is copied whenever `attrs` is copied".

**Comment by jhamman** [comment]
I agree that we haven't done a good job defining how `encoding` should behave. I agree that any modification of the shape/type of an xarray object should probably drop the original encoding. I don't know if a copy should drop the encoding though. I don't see why we shouldn't be able rountrip datasets via a open/load/copy/write workflow.

**Comment by crusaderky** [comment]
Can we reach a resolution on this? It's blocking #1551...

**Comment by jhamman** [comment]
@crusaderky - After thinking about it, I'm still a 👍 on copying the encoding in this case.

**Comment by shoyer** [comment]
I'm OK copying encoding, but we do still need to figure out general rules for propagating it.
