### ISSUE TITLE
Behavior of dataarray with no dimensions

### ISSUE THREAD

**Issue by 0x0L** [pydata/xarray#1726]
Consider

```python
type(np.array([1.0]).mean())
# -> numpy.float64

type(pd.Series([1.0]).mean())
# -> float

type(xr.DataArray([1.0]).mean())
# -> xarray.core.dataarray.DataArray
```

The issue is that this dimensionless data array won't be cast into float by numpy/pandas when constructing a new ndarray/dataframe. You'll have to do it explicitly. Not a big deal but it feels weird.

I'm sure there's a real technical reason (keeping metadata ?) behind this behavior but I couldn't find any discussion about it.

**Comment by shoyer** [comment]
Yes, this was an intentional choice, though not without occasional regrets!

This is nice from an consistency perspective: every operation on an xarray object returns another xarray object. Also, as you point out, this allows us to preserve metadata such as attributes or scalar coordinates.

I'm going to mark this as a documentation issue: this would be a great thing to add our docs where (maybe the FAQ page?).

**Comment by 0x0L** [comment]
Thanks for your answer.
I'll try to find a good spot in the doc to write a line or two about this.

**Comment by 0x0L** [comment]
I dug it a bit further. Contrary to what I said numpy seems fine. If `x` is a 1D DataArray

```python
np.array(x.mean())
# -> array(2.0)
np.array([x.mean()])
# -> array([2.0])
```

`pandas` behavior is more surprising

```python
pd.Series(2)
# ok

pd.Series(x.mean())
# -> TypeError: len() of unsized object

pd.Series([x.mean()])
# -> a series with dtype=object

# however
pd.Series(x)
# drops the index but dtype is fine
```

Something looks a bit odd to me.
