### ISSUE TITLE
Tables in docs make looking up functions unnecessarily hard

### ISSUE THREAD

**Issue by cutculus** [pydata/xarray#1728]
Before anything else: I think `xarray` is awesome and I love using it! It has made my life so much simpler over juggling dictionaries of arrays and maintaining indices in my head. Thank you to all contributors 😄!

#### Problem description

I can't read the method tables all at once (i.e. method name + args + short description). This makes it unnecessarily hard to see which function is doing what. Here are some pictures using Firefox, with and without tree-style tabs, and on a larger monitor for the last one.

![table_1](https://user-images.githubusercontent.com/7187503/32976427-79b7078e-cbe3-11e7-9582-78b6b017f86d.png)
![table_2](https://user-images.githubusercontent.com/7187503/32976428-7b523a96-cbe3-11e7-8fb7-a080894aa543.png)
![table_3](https://user-images.githubusercontent.com/7187503/32976430-7dba6786-cbe3-11e7-8260-705d33fdcdc5.png)

You have to scroll horizontally to read. This makes using a mouse terrible as the horizontal scrollbar is at the bottom of the table and not the bottom of the screen (the table is too big vertically to fit on the screen). The "hack" I'm using is to start selecting some text inside the table and drag the cursor to the edge leading to horizontal scrolling.

#### Suggestion

It would be nice if you didn't have tables but just inlined the short description like this one.

![table_replace](https://user-images.githubusercontent.com/7187503/32976460-123d7088-cbe4-11e7-8abb-9be544ace43d.png)

This allows text to wrap properly to the next line if needed. The only shortcoming is that the page takes up more vertical space but that's not such a big deal imo.

I'm happy to contribute a patch if someone can point me in the right direction. Is this a problem with `sphinx_rtd_theme`? I don't recall having similar issues with other packages' docs hosted on readthedocs.

**Comment by shoyer** [comment]
This is indeed the default behavior for `sphinx_rtd_theme`. I'm certainly open to better alternatives!

I would be slightly reluctant to adopt the two line version you show for `DataArray.to_series()` because it takes up significantly more vertical space, which makes the docs harder to skim.

The API docs for pandas (http://pandas.pydata.org/pandas-docs/stable/api.html) show a nice alternative: the description in the right column is allowed to span multiple lines if necessary (rather than relying on horizontal scrolling).

Apparently this is a common complaint -- I just Googled and turned up [a how-to guide for fixing it](https://rackerlabs.github.io/docs-rackspace/tools/rtd-tables.html).

I would encourage you to put together a PR. Try using our [environment.yml](https://github.com/pydata/xarray/blob/master/doc/environment.yml) file to setup a conda environment.

**Comment by dcherian** [comment]
now fixed.

![image](https://user-images.githubusercontent.com/2448579/77549934-5eaa4680-6ea8-11ea-90f6-0d05b16519d5.png)
