### ISSUE TITLE
Rank function

### ISSUE THREAD

**Issue by 0x0L** [pydata/xarray#1731]
Hi,

I think xarray is missing a rank function.
Is there any reason not to expose a wrapper to `bottleneck.nanrankdata` ?

See also https://github.com/pydata/xarray/issues/1635

[edit]
Although moving rank is mentioned in the whats-new for v0.9.2 I wasn't able to find that functionality nor a trace of it in the code :)

**Comment by jhamman** [comment]
> Is there any reason not to expose a wrapper to bottleneck.nanrankdata

@0x0L - I don't think so and I think we'd be open to adding this function. Even better if there is a fallback numpy equivalent but I don't think that would be required.

I looked at the (my) whatsnew note from 0.9.2 and I it seems we decided to remove this option until there is a rank method for dataarray/dataset objects. See @shoyer's comment: https://github.com/pydata/xarray/pull/1278#discussion_r103511989

**Comment by maxim-lian** [comment]
Great idea. 

We use `bottleneck.nanrankdata` manually; I don't think there's a vectorized numpy fallback

**Comment by 0x0L** [comment]
* `nanrankdata` only support numeric types, how about wrapping `rankdata` with a keyword option ?

* There's also a push `push` method similar to pandas `ffill` which would be nice.

* `move_rank` outputs are not normalized as `rankdata`, this might be a bit confusing

**Comment by shoyer** [comment]
> nanrankdata only support numeric types, how about wrapping rankdata with a keyword option ?

We already do dispatching to appropriate functions based on the dtype for aggregations:
https://github.com/pydata/xarray/blob/9d09c1659741dafb1fadeed49c81f9e90a548b07/xarray/core/duck_array_ops.py#L174
(Yes, this is a bit of a mess)

Since `NaN` has a consistent sorting position in NumPy/bottleneck (it sorts to the end), I would suggest including a `skipna` keyword argument, like one we use for aggregation functions. Alternatively, we could use `na_option : {‘keep’, ‘top’, ‘bottom’}` [like pandas](https://pandas.pydata.org/pandas-docs/stable/generated/pandas.DataFrame.rank.html).

> There's also a push push method similar to pandas ffill which would be nice.

@jhamman is already working on `ffill`/`bfill` in https://github.com/pydata/xarray/pull/1640
