### ISSUE TITLE
DataArray.sum does not respect dtype keyword

### ISSUE THREAD

**Issue by gerritholl** [pydata/xarray#1838]
#### Code Sample, a copy-pastable example if possible

```python
# Your code here
da = xarray.DataArray(arange(5, dtype="i2"))
print(da.sum(dtype="i4").dtype)
```
#### Problem description

The result is int64.  This is a problem because I asked for int32.

#### Expected Output

Expected output `int32`.

#### Output of ``xr.show_versions()``

<details>
# Paste the output here xr.show_versions() here
INSTALLED VERSIONS
------------------
commit: None
python: 3.6.1.final.0
python-bits: 64
OS: Linux
OS-release: 2.6.32-696.6.3.el6.x86_64
machine: x86_64
processor: x86_64
byteorder: little
LC_ALL: None
LANG: en_GB.UTF-8
LOCALE: en_GB.UTF-8

xarray: 0.10.0+dev12.gf882a58
pandas: 0.22.0
numpy: 1.14.0
scipy: 1.0.0
netCDF4: 1.3.1
h5netcdf: None
Nio: None
bottleneck: 1.2.1
cyordereddict: None
dask: 0.16.1
matplotlib: 2.1.1
cartopy: 0.15.1
seaborn: 0.8.1
setuptools: 38.4.0
pip: 9.0.1
conda: 4.3.16
pytest: 3.1.2
IPython: 6.1.0
sphinx: 1.6.2

</details>

**Comment by fujiisoup** [comment]
I notice here

https://github.com/pydata/xarray/blob/f3deb2f2495220af819021b199a5305b0d62ef36/xarray/core/duck_array_ops.py#L177-L181

we removed `dtype` arguments from reduce methods, but I'm not sure why.
This might be a bug.

As a temporal solution, 
```python
da.reduce(np.sum dtype="i4")
```
preserves dtype.

**Comment by shoyer** [comment]
We do this for two reasons:
- bottleneck's aggregation functions like `bottleneck.nansum()` don't have a `dtype` argument, so passing on a dtype argument causes an error to be raised.
- If you call a numpy function like `numpy.sum()` on an xarray object, it calls the appropriate method with all keyword arguments, e.g., `numpy.sum(xarray_obj)` -> `xarray_obj.sum(axis=None, dtype=None, out=None)`.

What we should probably do here instead of ignoring `dtype` and `out` entirely is to look at their values:
- If `dtype` is not None, use numpy's aggregation function instead of bottleneck's.
- If `out` is not None, raise an error.
