### ISSUE TITLE
bug: 2D pcolormesh plots are wrong when coordinate is not ascending order

### ISSUE THREAD

**Issue by nbren12** [pydata/xarray#1852]
#### Code Sample, a copy-pastable example if possible

```python
import matplotlib.pyplot as plt
import numpy as np
import xarray as xr


x = np.arange(10)
y = np.arange(20)

np.random.shuffle(x)

x = xr.DataArray(x, dims=['x'], coords={'x': x})
y = xr.DataArray(y, dims=['y'], coords={'y': y})

z = x + y
z_sorted = z.isel(x=np.argsort(x.values))


# make plot
fig, axs= plt.subplots(1, 2, figsize=(6,3))
z_sorted.plot(ax=axs[0])
axs[0].set_title("X is sorted")

z.plot(ax=axs[1])
axs[1].set_title("X is not unsorted")
plt.tight_layout()
```
#### Problem description

Sometime the coordinates in an xarray dataset are not always sorted in ascending order. I recently had an issue where the time coordinate of a 2D datasets was scrambled, so calling `x.plot` gave very strange results. In my opinion, `x.plot` should probably sort the data along the coordinates, or at least provide a warning if the coordinates are unsorted.

#### Expected Output
Here is the image generated by the snippet above:

![image](https://user-images.githubusercontent.com/1386642/35318676-36d136a0-0091-11e8-9c94-bce67f4d5991.png)

The left and right panels should be the same.

# Paste the output here xr.show_versions() here

<details>
INSTALLED VERSIONS
------------------
commit: None
python: 3.6.2.final.0
python-bits: 64
OS: Darwin
OS-release: 16.0.0
machine: x86_64
processor: i386
byteorder: little
LC_ALL: None
LANG: en_US.UTF-8
LOCALE: en_US.UTF-8

xarray: 0.10.0+dev50.ga988dc2
pandas: 0.20.3
numpy: 1.13.1
scipy: 0.19.1
netCDF4: 1.3.1
h5netcdf: 0.5.0
Nio: None
zarr: None
bottleneck: 1.2.1
cyordereddict: None
dask: 0.15.2
distributed: 1.18.3
matplotlib: 2.0.2
cartopy: None
seaborn: 0.8.0
setuptools: 36.5.0.post20170921
pip: 9.0.1
conda: 4.3.29
pytest: 3.2.1
IPython: 6.1.0
sphinx: 1.6.3
</details>

**Comment by nbren12** [comment]
This is pretty easily fixed running 
```python
sort_inds = {dim: np.argsort(z[dim].values) for dim in z}
z = z.isel(**sort_inds)
```

**Comment by fmaussion** [comment]
It's not a trivial problem, because pcolormesh expects n+1 coordinates (the coordinates of the mesh corners), and to do what you want with matplotlib's pcolormesh alone (i.e. without xarray), you'll probably have to sort the values beforehand too (correct me if I'm wrong).

So the question is how much sanity check xarray should do before sending the data to matplotlib, and maybe a warning of some kind would be useful. Xarray's pcolormeh already implements some logic to make it easier to use than matplotlib's (see e.g. https://github.com/pydata/xarray/pull/1079).

**Comment by nbren12** [comment]
> pcolormesh expects n+1 coordinates
I agree that pcolormesh ultimately works with the mesh corners, but I am pretty sure passing coordinates of the same length also works.

> you'll probably have to sort the values beforehand too

True. But we can do it automatically with xarray because it has the coordinate information.

> So the question is how much sanity check xarray should do before sending the data to matplotlib, and maybe a warning of some kind would be useful.

I am not sure there there is any circumstance where it would be preferable to plot the scrambled data. Is there some the problem with just adding something like the two lines a wrote above to `plot.pcolormesh`?

**Comment by nbren12** [comment]
I think automatically sorting is OK for 1D coordinates at least. I agree it is more complicated for other situations.

**Comment by fmaussion** [comment]
>  Is there some the problem with just adding something like the two lines a wrote above to plot.pcolormesh?

Performance I guess, and the fact that monotonically descending coordinates also work fine. I don't think this happens very often so sorting and calling ``isel`` on every single array is overkill.

I don't have a strong opinion here, so I'll let @shoyer or others decide what's best.

**Comment by fmaussion** [comment]
... But I guess that you're right, it should be fine to do as you suggest!

**Comment by fmaussion** [comment]
> I agree that pcolormesh ultimately works with the mesh corners, I am pretty sure passing coordinates of the same length also works.

Passing N coordinates will crop the data of one pixel and plot N-1 pixels. For example:

```python
import matplotlib.pyplot as plt

data = [[1, 2], [3, 4]]
f, (ax1, ax2) = plt.subplots(1, 2)
ax1.pcolormesh([1, 2, 3], [2, 3, 4], data)
ax1.set_title('N+1 coords')
ax2.pcolormesh([1, 2], [2, 3], data)
ax2.set_title('N coords')
plt.savefig('example.png')
```
![example](https://user-images.githubusercontent.com/10050469/35358897-7ab95f42-0158-11e8-9988-996eb2b31228.png)

**Comment by shoyer** [comment]
One indication that something is broken here is that `z.plot.imshow()` and `z.plot.pcolormesh()` show very different figures. (`imshow` shows the right data, but the labels on the x-axis are wrong.)

I can see use cases for plotting scrambled data, but for those cases I would probably defer to `seaborn.heatmap()` which does the right thing (including labels):
```
import seaborn
z.to_pandas().pipe(seaborn.heatmap, cmap='viridis')
```
![download 46](https://user-images.githubusercontent.com/1217238/35358810-be1152dc-010c-11e8-8b97-2d1e375890f8.png)

Rather than automatically sorting data, we could start raising an error if labels are unsorted. The error message could suggest either sorting the data with the `sortby()` method or using `seaborn.heatmap`.

**Comment by fmaussion** [comment]
> Rather than automatically sorting data, we could start raising an error if labels are unsorted.

yes, I prefer that too.
