### ISSUE TITLE
Should imshow() recognise 0-255 images?

### ISSUE THREAD

**Issue by fmaussion** [pydata/xarray#1880]
#### Code Sample, a copy-pastable example if possible

```python
import os
import urllib.request
import xarray as xr
import matplotlib.pyplot as plt

# Download the file from rasterio's repository
url = 'https://github.com/mapbox/rasterio/raw/master/tests/data/RGB.byte.tif'
urllib.request.urlretrieve(url, 'RGB.byte.tif')

# Read the data
da = xr.open_rasterio('RGB.byte.tif')

f, (ax1, ax2) = plt.subplots(1, 2, figsize=(9, 4))
da.plot.imshow(ax=ax1)
(da / 255).plot.imshow(ax=ax2)
plt.tight_layout()
plt.show()

# Delete the file
os.remove('RGB.byte.tif')
```

![figure_1](https://user-images.githubusercontent.com/10050469/35730809-c157c7ba-0813-11e8-8909-24b6d61e685c.png)

#### Problem description

In https://github.com/pydata/xarray/pull/1796, @Zac-HD added support for RGBA images. If an alpha channel is not found, it is added ([code](https://github.com/pydata/xarray/blob/master/xarray/plot/plot.py#L708))

The problem is that adding this alpha channel requires the images to be normalized to 0-1, while plotting an image in 0-255 range without alpha channel works fine in matplotlib. Removing https://github.com/pydata/xarray/blob/master/xarray/plot/plot.py#L708-L715 would solve the problem, but I guess it was added for a reason. 

@Zac-HD , thoughts?

**Comment by Zac-HD** [comment]
Ouch, this is definitely a bug in the code I wrote - that's terrible 😭 

Probably related to matplotlib/matplotlib/pull/10220, where I'm looking at clipping instead of wrapping colours from the other side.

Fixing this issue *may* be as simple as setting alpha to 255 instead of 1 for integer dtypes, or it might be more involved.  Either way I'll try to open a pull within the next few days.
