### ISSUE TITLE
Dataset doesn't work with inspect.getmembers()

### ISSUE THREAD

**Issue by titusjan** [pydata/xarray#2014]
When passing a `Dataset` to the `inspect.getmembers`function [from the standard library](https://docs.python.org/3/library/inspect.html), a `TypeError` is raised:

```python
In [1]: import numpy as np

In [2]: from xarray import DataArray

In [3]: import inspect

In [4]: d = DataArray(np.ones(5))

In [5]: inspect.getmembers(d)
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-5-371ad12e6fd2> in <module>()
----> 1 inspect.getmembers(d)

~/miniconda3/envs/specind/lib/python3.6/inspect.py in getmembers(object, predicate)
    340         # looking in the __dict__.
    341         try:
--> 342             value = getattr(object, key)
    343             # handle the duplicate key
    344             if key in processed:

~/miniconda3/envs/specind/lib/python3.6/site-packages/xarray/core/accessors.py in __init__(self, xarray_obj)
     85     def __init__(self, xarray_obj):
     86         if not is_datetime_like(xarray_obj.dtype):
---> 87             raise TypeError("'dt' accessor only available for "
     88                             "DataArray with datetime64 or timedelta64 dtype")
     89         self._obj = xarray_obj

TypeError: 'dt' accessor only available for DataArray with datetime64 or timedelta64 dtype

```

Is it possible to fix this? I'd like to pass `DataArrays` to my [Object Browser GUI](https://github.com/titusjan/objbrowser), which relies on the `getmembers` function to get a list of attributes.

**Comment by maxim-lian** [comment]
It looks like `inspect.getmembers` raises on any property that raises anything but `AttributeError`. With `.dt`, we raise a `TypeError` on anything that isn't date-like. 

I wouldn't choose it initially, but could this be an `AttributeError`?

Though I wonder whether there are going to be enough errors on other objects (& libraries) that @titusjan you might want a `safe_inspect_members` that don't break if a property raises when called. For example, because I don't use Dask, all the dask properties broke as I was recreating the example.

@titusjan - cool app!

**Comment by shoyer** [comment]
Switching to raise `AttributeError` when `.dt` is invalid might work in this case, but I'm not sure it would work for the right reason. It looks like `inspect.getmembers` only allows `AttributeError` to pass because that's the error raised by `getattr()` when called on a missing attribute.

I'm definitely open to changing this, but there's another unfortunate complication: if you raise `AttributeError` during the construction of a property on a class that defines `__getitem__`, the [error gets silently caught](https://stackoverflow.com/questions/11116896/python-why-is-getattr-catching-attributeerrors). Here's an example:
```python-traceback
In [51]: def error():
    ...:     raise AttributeError("important message about invalid dtype!")
    ...:

In [52]: xarray.DataArray.dt = property(lambda self: error())

In [53]: d = xarray.DataArray([1, 2])

In [54]: d.dt
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-54-b3ec8208cbfc> in <module>()
----> 1 d.dt

~/dev/xarray/xarray/core/common.py in __getattr__(self, name)
    173                     return source[name]
    174         raise AttributeError("%r object has no attribute %r" %
--> 175                              (type(self).__name__, name))
    176
    177     def __setattr__(self, name, value):

AttributeError: 'DataArray' object has no attribute 'dt'
```
Notice that the important message has been lost!

The alternatives as I see them:
- Xarray shouldn't have properties that can potentially error when accessed. This probably a good idea in principle, but I don't see another good way to make our `.dt` property.
- Adjust your introspection code to use something more flexible than `inspect.getmembers()`. This is my reluctant recommendation. I know Jedi does something similar.

Also, not that it's any excuse but pandas has the same issue with `inspect.getmembers`:
```python-traceback
In [32]: s = pd.Series([1])

In [33]: inspect.getmembers(s)
---------------------------------------------------------------------------
AbstractMethodError                       Traceback (most recent call last)
<ipython-input-33-1468c2169e82> in <module>()
----> 1 inspect.getmembers(s)

~/miniconda3/envs/xarray-py36/lib/python3.6/inspect.py in getmembers(object, predicate)
    340         # looking in the __dict__.
    341         try:
--> 342             value = getattr(object, key)
    343             # handle the duplicate key
    344             if key in processed:

~/miniconda3/envs/xarray-py36/lib/python3.6/site-packages/pandas/core/generic.py in _constructor_sliced(self)
    204         original, such as DataFrame single columns slicing.
    205         """
--> 206         raise AbstractMethodError(self)
    207
    208     @property

AbstractMethodError: This method must be defined in the concrete class of Series```
