### ISSUE TITLE
Cross-platform in-memory serialization of netcdf4 (like the current scipy-based dumps)

### ISSUE THREAD

**Issue by ebrevdo** [pydata/xarray#23]
It would be nice to create in-memory netCDF4 objects.  This is difficult with the netCDF4 library, which requires a filename (possibly one that it can mmap, but probably not, based on its opendap documentation).

One solution is to call os.mkfifo (in *nix) or its windows equivalent (if the library is available) using tempfile.mktemp as the path.  Pass this to the netCDF4 object.  dumps() is equivalent to calling sync, close, reading from the pipe, then deleting the result.

We may actually be able to use the same functionality in reverse for creating a netCDF4 object from a StringIO.

**Comment by shoyer** [comment]
Just wrote a little library to do netCDF4 via h5py: https://github.com/shoyer/h5netcdf

Unfortunately h5py still can't do in-memory file images (https://github.com/h5py/h5py/issues/552). But it does give an alternative way to read/write netCDF4 without going via the Unidata libraries. There is experimental support for `engine='h5netcdf'` in my dask PR: https://github.com/xray/xray/pull/381

pytables was not a viable option because it can't read or write HDF5 dimension scales, which are necessary for dimensions in netCDF4 files.

**Comment by max-sixty** [comment]
In an effort to reduce the issue backlog, I'll close this, but please reopen if you disagree

**Comment by pikulmar** [comment]
Still an issue, as far as I can tell. Possibly duplicated in https://github.com/pydata/xarray/issues/3372.

**Comment by jhamman** [comment]
This must be the one of the oldest active issues in the project!

Curious if folks have thoughts on the current state here? Netcdf4-python has a some support for [in-memory datasets](https://unidata.github.io/netcdf4-python/#in-memory-diskless-datasets) but we are not exposing them with xarray (as far as I can tell). How about h5netcdf?

**Comment by kmuehlbauer** [comment]
There is effort in #6956 to enable this for netcdf4. 

This is possible for h5py/h5netcdf, too. See https://docs.h5py.org/en/stable/high/file.html#file-drivers. xarray has just to enable this via kwarg `driver="core"`. Not sure how much effort this will take.
