### ISSUE TITLE
da.loc[date[0]] brings up two instead of one

### ISSUE THREAD

**Issue by am-thyst** [pydata/xarray#2450]
#### Problem description
My dataset has lots of days, with data for two times for each day: midnight and midday (12am and 12pm). With date[0], I am trying to retrieve only the midnight data from the first day; with date[1], the midday data from the same day; date[3] the midnight data from the next day, etc. Now I'm writing this, I'm not sure I've posted this in the right place so please let me know if I haven't.

#### Code Sample 1: this gives data for midnight and midday (time: 2)
```python
from datetime import datetime, timedelta
start = datetime(1979, 1, 1)
date = [start.strftime('%Y%m%d')]
a = first_dataset.loc[date[0]]
print(a)

<xarray.DataArray (time: 2, latitude: 241, longitude: 480)>
array([[[  #there are numbers here, cut out for ease of reading
            ]]])
Coordinates:
  * longitude  (longitude) float32 0.0 0.75 1.5 2.25 3.0 3.75 4.5 5.25 6.0 ...
  * latitude   (latitude) float32 90.0 89.25 88.5 87.75 87.0 86.25 85.5 ...
  * time       (time) datetime64[ns] 1979-01-01 1979-01-01 T12:00:00 #as you can see here, for
#midnight the time is just 1979-01-01 instead of 1979-01-01 00:00:00, which I think might be causing
#some confusion in my code
```
#### Code Sample 2: try adding hour to the date
```python
from datetime import datetime, timedelta
start = datetime(1979, 1, 1)
date = [start.strftime('%Y%m%d%H')] #this what I changed
a = first_dataset.loc[date[0]]
print(a)

Traceback (most recent call last):
  File "pandas/index.pyx", line 589, in pandas.index.DatetimeEngine.get_loc (pandas/index.c:11661)
  File "pandas/src/hashtable_class_helper.pxi", line 404, in pandas.hashtable.Int64HashTable.get_item (pandas/hashtable.c:8543)
TypeError: an integer is required
 
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/nerc/n02/n02/amethyst/.conda/envs/my_root/lib/python3.4/site-packages/pandas/indexes/base.py", line 2134, in get_loc
    return self._engine.get_loc(key)
  File "pandas/index.pyx", line 553, in pandas.index.DatetimeEngine.get_loc (pandas/index.c:11829)
  File "pandas/index.pyx", line 591, in pandas.index.DatetimeEngine.get_loc (pandas/index.c:11735)
  File "pandas/index.pyx", line 597, in pandas.index.DatetimeEngine._date_check_type (pandas/index.c:11899)
KeyError: '1979010100'
```
#### Expected Output
```python
a = first_dataset.loc[date[0]]
print(a)

<xarray.DataArray (time: 1, latitude: 241, longitude: 480)>
array([[[  #there are numbers here, cut out for ease of reading
            ]]])
Coordinates:
  * longitude  (longitude) float32 0.0 0.75 1.5 2.25 3.0 3.75 4.5 5.25 6.0 ...
  * latitude   (latitude) float32 90.0 89.25 88.5 87.75 87.0 86.25 85.5 ...
  * time       (time) datetime64[ns] 1979-01-01
```

**Comment by spencerkclark** [comment]
Thanks @am-thyst, this happens to be expected behavior.  For a dimension indexed by a DatetimeIndex (e.g. your `'time'` dimension), label-based indexing with strings uses so-called ["partial string indexing"](https://pandas.pydata.org/pandas-docs/stable/timeseries.html#partial-string-indexing).  This behavior in xarray is inherited from pandas.  Essentially what it means is that if you provide a string to a label-based indexer (like `.loc`), then it will return values from all times that would begin with the string you provided if expressed in string form.  So, in your example, if you provide only the year, month, and day (e.g. `'1979-01-01'`) it will return values from `'1979-01-01'` and `1979-01-01T12:00:00`, because both string representations start with `'1979-01-01'`.

As you inferred, if you add detail to the string you provide, you can refine the selection.  That said, you need to be careful of the format you use (I think the reason you get a `KeyError` in your second example is that pandas does not know how to interpret the string you provided).  While pandas has some flexibility in how it parses datetime-strings I might recommend sticking to the [ISO 8601 format](https://en.wikipedia.org/wiki/ISO_8601), which should work in all cases.  For example to select just the values associated with the first date in your array you could do something like this:
```
In [1]: import numpy as np; import pandas as pd; import xarray as xr

In [2]: times = pd.date_range('1979', periods=8, freq='12H')

In [3]: da = xr.DataArray(np.arange(8), coords=[times], dims=['time'])

In [4]: da
Out[4]:
<xarray.DataArray (time: 8)>
array([0, 1, 2, 3, 4, 5, 6, 7])
Coordinates:
  * time     (time) datetime64[ns] 1979-01-01 ... 1979-01-04T12:00:00

In [5]: da.loc['1979-01-01T00']
Out[5]:
<xarray.DataArray ()>
array(0)
Coordinates:
    time     datetime64[ns] 1979-01-01
```
One other thing to note, in general, is that you can pass datetimes themselves to label-based indexers if you want to select specific dates; this way you don't need to go through the intermediate step of converting a date to a string:
```
In [6]: da.loc[datetime(1979, 1, 1)]
Out[6]:
<xarray.DataArray ()>
array(0)
Coordinates:
    time     datetime64[ns] 1979-01-01
```

**Comment by spencerkclark** [comment]
@am-thyst could you provide more details on what sort of operation you are trying to do with each time slice?  Typically this kind of process is better handled in a vectorized way.

**Comment by am-thyst** [comment]
@spencerkclark I'm creating a 2D array of the percentage of time each lon/lat coordinate exceeds a defined threshold. I did this fine before, but I was only using 1 time from each day

**Comment by spencerkclark** [comment]
I'm not sure if I'm understanding the calculation correctly; is something like the following what you are looking for?
```
In [1]: import numpy as np; import pandas as pd; import xarray as xr

In [2]: times = pd.date_range('1979', periods=4, freq='12H')

In [3]: da = xr.DataArray(np.random.rand(4, 2, 3), coords={'time': times}, dims=['time', 'x', 'y'])

In [4]: threshold = 0.5

In [5]: (da > threshold).mean('time')
Out[5]:
<xarray.DataArray (x: 2, y: 3)>
array([[ 0.25,  0.5 ,  0.25],
       [ 0.25,  0.5 ,  0.5 ]])
Dimensions without coordinates: x, y
```

**Comment by am-thyst** [comment]
@spencerkclark 
```python
a = da.loc[date[0]] #the initial time, obviously this part doesn't work but this is the methodology
b = a.where(a >= threshold, other = 0) #keeps values that satisfy the threshold, sets the rest to 0
c = b.where(b == 0, other = 1) #sets all values that satisfy the threshold to 1
new_array = zero_array + c #zero_array is just an array of the same shape without time, set to 0
runs = runs + 1
```
Loops through this whole thing for every time (changing the loc to date[1], date[2], etc.), then:
```python
percentage = (new_array / runs) * 100
```

This is not my complete code but you should get the idea, as I said it works fine with only 1 time per day

**Comment by spencerkclark** [comment]
@am-thyst thanks for the extra details -- try out my method -- I think it does the same thing.  Well perhaps you'll just need to multiply the result by 100 at the end and use `>=` instead of `>` for the threshold condition :)

Your approach can also be vectorized in such a way that you don't need to manually iterate over the individual times:
```
In [6]: b = da.where(da >= threshold, other=0)

In [7]: c = b.where(b == 0, other=1)

In [8]: (c.sum('time') / c.sizes['time']) * 100
Out[8]:
<xarray.DataArray (x: 2, y: 3)>
array([[ 25.,  50.,  25.],
       [ 25.,  50.,  50.]])
Dimensions without coordinates: x, y
```
Effectively `da >= threshold` in my earlier example is shorthand for lines 6 and 7 from the example above (and taking the mean is the same as summing over the dimension and dividing by the number of elements along that dimension).

**Comment by am-thyst** [comment]
@spencerkclark Thanks a lot, I'll give it a try 👍

**Comment by am-thyst** [comment]
@spencerkclark following your method:
```python
AttributeError: 'tuple' object has no attribute 'where'
```

**Comment by spencerkclark** [comment]
@am-thyst could you show all the code that you used to try it out?  If I run all the lines (from 1-8 in 
https://github.com/pydata/xarray/issues/2450#issuecomment-426340226 and https://github.com/pydata/xarray/issues/2450#issuecomment-426353764) in my IPython console things  work for me.

**Comment by am-thyst** [comment]
@spencerkclark ah sorry I missed line 5 - I'm not looking to get the mean, I want to make sure the unusual values are still represented. That might be why mine went wrong, it generally only works when there's just one time. Anyway, here's what I tried:
```python
import xarray as xr
from function_codes import sfcwinds, complete_shear, winds
import os
pathway = #my pathway
os.chdir(pathway)

sfc_winds = sfcwinds("sfc")
ml50_winds = winds("ml50")
ml50_shear = complete_shear(sfc_winds, ml50_winds)

a = ml50_shear.where(ml50_shear >= 11, other = 0)
b = a.where(a == 0, other = 1)
pa = (b.sum('time') / b.sizes['time']) * 100
print(pa)
```

**Comment by spencerkclark** [comment]
Does `complete_shear` happen to return more than one DataArray?

**Comment by am-thyst** [comment]
@spencerkclark Oh you're right, I didn't think about that - it returns 4

**Comment by spencerkclark** [comment]
> Gonna try with just the first of the four

👍 let me know how it goes.

**Comment by am-thyst** [comment]
@spencerkclark
```python
Traceback (most recent call last):
  File "/var/spool/torque/mom_priv/jobs/63347.rdf-xcat.SC", line 22, in <module>
    a = ml50_shear[0].where(ml50_shear[0] >= 11, other = 0)

NotImplementedError: The optional argument 'other' has not yet been implemented
```

**Comment by am-thyst** [comment]
@spencerkclark  yeah I was using a different platform, updated my xarray version and this works now, thanks!
