### ISSUE TITLE
Reduction Problem on Datasets with ufloat type (from uncertainties package)

### ISSUE THREAD

**Issue by dfgill** [pydata/xarray#2546]
#### Code Sample

I am using xarray in conjunction with the uncertainties package to work with data that has stochastic uncertainty associated with it. I have specifically been looking at reduction operations and these work as expected when working with DataArrays but I do not see the behavior I expect when working with Datasets. It's entirely possible that my expectations are the real issue but I thought I would ask.

```python
import xarray as xr
import numpy as np
from uncertainties import unumpy

data = np.random.rand(10)
unc = np.random.rand(10)
udata = unumpy.uarray(data,unc)

da = xr.DataArray(udata, dims='dim_1')
da.sum()

ds = xr.Dataset({'udata' : da})
ds.sum()
```

The output for the sum of the DataArray is
```
<xarray.DataArray ()>
array(4.208380793371934+/-1.7689637725143232, dtype=object)
```
while that for the Dataset is

```
<xarray.Dataset>
Dimensions:  ()
Data variables:
    *empty*
```

#### Problem description

Given that the sum of the DataArray (with uncertainty information) is correctly computed I would have expected this would work for the Dataset as well. 

#### Expected Output

The resulting Dataset would still have a udata variable that has been reduced to 4.208380793371934+/-1.7689637725143232.  

#### Output of ``xr.show_versions()``

<details>
INSTALLED VERSIONS
------------------
commit: None
python: 3.6.3.final.0
python-bits: 64
OS: Windows
OS-release: 10
machine: AMD64
processor: Intel64 Family 6 Model 23 Stepping 10, GenuineIntel
byteorder: little
LC_ALL: None
LANG: None
LOCALE: None.None

xarray: 0.10.9
pandas: 0.23.4
numpy: 1.14.2
scipy: 0.19.1
netCDF4: None
h5netcdf: None
h5py: 2.7.0
Nio: None
zarr: None
cftime: None
PseudonetCDF: None
rasterio: None
iris: None
bottleneck: 1.2.1
cyordereddict: None
dask: 0.15.3
distributed: 1.19.1
matplotlib: 2.1.0
cartopy: None
seaborn: 0.8.0
setuptools: 36.5.0.post20170921
pip: 9.0.1
conda: 4.4.9
pytest: 3.2.1
IPython: 6.1.0
sphinx: 1.6.3

</details>

**Comment by shoyer** [comment]
@dfgill Thanks for this clear report!

We can reproduce this behavior with strings, which can be summed as if they're saved as object arrays, e.g.,
```
>>> ds = xarray.Dataset({'foo': ('x', np.array(['a', 'b'], dtype=object))})
>>> ds
<xarray.Dataset>
Dimensions:  (x: 2)
Dimensions without coordinates: x
Data variables:
    foo      (x) object 'a' 'b'
>>> ds.sum()
<xarray.Dataset>
Dimensions:  ()
Data variables:
    *empty*
```

One work around is to use the Dataset.reduce() method:
```
>>> ds.reduce(np.sum, numeric_only=False)
<xarray.Dataset>
Dimensions:  ()
Data variables:
    foo      <U2 'ab'
```

The underlying problem seems to be the `numeric_only` argument, which by default drops non-numeric arrays based on the dtype (`object` in both the case of these strings and uncertainty objects).

Ways we could solve this:
1. Drop this behavior -- if users have non-numeric data variables, they should put them in coordinates instead.
2. Check for errors (e.g., TypeError) rather than proactively identifying dtype=object as indicating the the operation won't be supported. This seems pretty error prone, because you might get a TypeError for some other reason and want to see why.
3. Add the keyword argument `numeric_only` to xarray's reduction methods -- at least you only need to type `ds.sum(numeric_only=False)` rather than using `.reduce()`

In the short term, (3) is probably the best option -- I would be happy to accept a PR here. (1) could be a good long-term choice, but would need some further discussion (especially because it would break backwards compatibility).
