### ISSUE TITLE
Dataset.to_netcdf with mixed int and str in data

### ISSUE THREAD

**Issue by ChengweiWang0** [pydata/xarray#2620]
Hi, 

The code below gives me a TypeError when use engine = ‘netcdf4’ or ‘scipy’ in to_netcdf() function, but works when use engine='h5netcdf' by automatically converting int to str. 

Any good idea to solve this issue? To save the data as their original dtype (not covert int to str)?

Code:
df = pd.DataFrame({'a' : ['x', 'y'], 'b': [1,2]})
da = xr.DataArray(df)
ds = xr.Dataset({'test' : da})

ds.to_netcdf('test.nc', engine='netcdf4')  #TypeError: expected bytes, int found
ds.to_netcdf('test.nc', engine='scipy')  #TypeError: expected bytes, int found
ds.to_netcdf('test.nc', engine='h5netcdf')  #works, but automatically covert int to str which is not good...

**Comment by shoyer** [comment]
Thanks for the report! This is definitely a bug, we should be raising an informative error message here.

It looks like these lines in `_infer_dtype` should be updated to look at the full array rather than only the first element:
https://github.com/pydata/xarray/blob/778ffc49135d6f97e17b37b48304995fca72f1e0/xarray/conventions.py#L119-L139

**Comment by ChengweiWang0** [comment]
Thank you very much shoyer, hope we can fix this bug in the next version.
