### ISSUE TITLE
Xarray tutorial at SciPy 2019?

### ISSUE THREAD

**Issue by mrocklin** [pydata/xarray#2692]
Is anyone interested in submitting a tutorial to SciPy 2019?  I think that it would be useful to have an official Xarray tutorial out there somewhere on the internet.  This could be good motivation to create one.

https://www.scipy2019.scipy.org/tutorials

See also: https://github.com/pydata/xarray/issues/1882

**Comment by jhamman** [comment]
@pydata/xarray - who's going to scipy this year? I agree with @mrocklin that it would be nice to have a basic xarray tutorial (beginner to intermediate). I can lead the charge on this but would appreciate help from others that can attend.

**Comment by rabernat** [comment]
I am definitely planning to go this year. I would love to be involved in a tutorial. We can build on our AGU tutorial.

**Comment by jhamman** [comment]
Closing. @rabernat and I submitted a proposal yesterday. I will reopen this issue if our proposal is accepted.

**Comment by mrocklin** [comment]
Looking at the [tutorial schedule](https://www.scipy2019.scipy.org/Tutorial/07%2F08%2F2019) it looks like it was not accepted, but that there is a TBA slot.  Any information here @jhamman ?  Did you all receive a rejection response?

**Comment by jhamman** [comment]
@mrocklin - No, we haven't heard anything from the organizers yet.

**Comment by jhamman** [comment]
Alright. Despite our best proposal and lobbying efforts, the xarray tutorial was not accepted this year. The reviews that came back were very noisy - everything from weak reject to strong accept. 

Our proposal is [here](https://docs.google.com/document/d/1yw6QX_B5DP5bxS37v1BQUtrQ1RuAqKZTUc1EbzU9gHo/edit?usp=sharing).

The reviews are below:


----------------------- REVIEW 1 ---------------------
PAPER: 176
TITLE: Xarray for Scalable Scientific Data Analysis
AUTHORS: Joseph Hamman and Ryan Abernathey

Overall evaluation: 2 (weak reject)

----------- Overall evaluation -----------
The topic seems very detailed and it's definitely really technical in the sense that this tutorial will introducer attendees to deeper levels of understanding for xarray, dask. The instructors are definitely the best fit for presenting this topic as clearly active developers for the xarray project and have impressive backgrounds. I also really appreciate that part of the tutorial is dedicated to also learning how xarray as a tool can be leveraged to solve real world problems in the field of geosciences.

I think what I really struggled to understand from the proposal is why I would use xarray and dask to process large datasets over other possible tools. Because I'm not very familiar with xarray, and there are not a lot of references to alternative technologies, it is hard for me to grasp from just the abstract/description, why this topic might be relevant to me and what I would gain from learning about xarray.


----------------------- REVIEW 2 ---------------------
PAPER: 176
TITLE: Xarray for Scalable Scientific Data Analysis
AUTHORS: Joseph Hamman and Ryan Abernathey

Overall evaluation: 3 (weak accept)

----------- Overall evaluation -----------
This looks like an interesting talk, and it seems like the presenters have expertise and experience.  From the proposal, it is hard to tell what the format of the tutorial is: how much is lecture; how much is hands-on work?


----------------------- REVIEW 3 ---------------------
PAPER: 176
TITLE: Xarray for Scalable Scientific Data Analysis
AUTHORS: Joseph Hamman and Ryan Abernathey

Overall evaluation: 4 (accept)

----------- Overall evaluation -----------
I think this is a solid proposal, and I would put it's diifficulty somewhere between intermediate and advanced.


----------------------- REVIEW 4 ---------------------
PAPER: 176
TITLE: Xarray for Scalable Scientific Data Analysis
AUTHORS: Joseph Hamman and Ryan Abernathey

Overall evaluation: 5 (strong accept)

----------- Overall evaluation -----------
The analysis of high-dimensional scientific data-sets is of broad interest, and the tools presented here are well established in the community.  The presenters are intimately familiar with the material, and have successfully taught it before.

**Comment by mrocklin** [comment]
There is usually a BoF at the end of the conference around planning for the next conference.  I suggest that a few of us show up and see if we can get engaged in the process for next year.

**Comment by max-sixty** [comment]
Thanks for trying @jhamman

**Comment by jhamman** [comment]
Irony of ironies. We resubmitted our tutorial proposal this year. It was accepted (yay!) BUT there is a good chance the conference will be rescheduled/canceled/virtual. I'll keep this issue updated as more details become available.

**Comment by mrocklin** [comment]
Gah!
