### ISSUE TITLE
[discussion] Use WKT or PROJ.4 string for CRS representation?

### ISSUE THREAD

**Issue by snowman2** [pydata/xarray#2722]
# Background
PROJ.4 is a popular format for storing projection strings. It has a nice and simple interface that is easy to use. However, converting to the PROJ.4 format from other formats can cause loss of useful projection information (PROJ.4 contains a warning about it [here](https://github.com/OSGeo/proj.4/blob/763ff547aea5e1013b49254b62fc06060eccfaaf/include/proj/io.hpp#L518-L522) and other users have had issues with losing information in the conversion, an example is [here](https://rasterio.groups.io/g/dev/message/70)). A lossless, though more complex, alternative is the WKT string. The WKT string is also going through improvements and will include the WKT2 (2015 and 2018) versions with useful information.

The [rasterio](https://github.com/mapbox/rasterio/pull/1597) project has already made the switch to use the WKT string.

# Discussion
The issue is meant to be a place to discuss whether the xarray project should use the WKT or the PROJ.4 format moving forward for storing CRS strings.

@fmaussion @sgillies @cratcliff @djhoese @rouault @kbevers

Feel free to include others that you think would provide valuable information to this discussion.

**Comment by fmaussion** [comment]
Thanks @snowman2 ! I don't think there is much discussion necessary about whether we should use WKT or not, the question is rather how? WKT strings are quite complex and verbose, but this should not be a big issue.

We used proj4 strings in xarray because it's what rasterio's `to_string` would give us back, and we need a canonical string representation for serialization to netCDF. I don't know how many users rely on the rasterio backend's `crs` attribute to be a proj4 string, but I guess that it's at least a few.

So, what should we do? My preferred solution right now would be to deprecate the `crs` attribute and replace it with two explicit `proj4_crs` and `wkt_crs` attributes to cover all use cases.

Thoughts?

**Comment by djhoese** [comment]
@fmaussion I like the idea of the `proj4_crs` and `wkt_crs` attributes. In the future I would hope the `geoxarray` package could handle this type of stuff (some day I'll get to it).

**Comment by snowman2** [comment]
Sounds like a good path forward to me.

Since the `crs` attribute will be deprecated, thoughts on replacing it with a `crs` coordinate and the `PROJ.4` and `WKT` representations in the coordinate attributes?

Something like:
```
<xarray.DataArray 'crs' ()>
array(0)
Coordinates:
    crs          int64 0
Attributes:
    crs_wkt:  PROJCS["UTM Zone 15, Northern Hemisphere",GEOGCS["WGS 84",D...
    crs_proj4: +proj=...
```

**Comment by snowman2** [comment]
Since the main discussion is resolved, I will close this issue to prevent spam. I will open another issue for implementation details later.
