### ISSUE TITLE
Stack() & unstack() issues on Multindex

### ISSUE THREAD

**Issue by ray306** [pydata/xarray#2933]
I would like to reshape the DataArray by one level in the Multindex, and I thought the `stack()`/`unstack()` should be the solution.

Make a DataArray with Multindex:
```python
import pandas as pd
arrays = [np.array(['bar', 'bar', 'baz', 'baz', 'foo', 'foo']),
          np.array(['one', 'two', 'one', 'two', 'one', 'two'])]
da = pd.DataFrame(np.random.randn(6, 4)).to_xarray().to_array()
da.coords['index'] = pd.MultiIndex.from_arrays(arrays, names=['first', 'second'])
da
```
```
<xarray.DataArray (variable: 4, index: 6)>
array([[ 0.379189,  1.082292, -2.073478, -0.84626 , -1.529927, -0.837407],
       [-0.267983, -0.2516  , -1.016653, -0.085762, -0.058382, -0.667891],
       [-0.013488, -0.855332, -0.038072, -0.385211, -2.149742, -0.304361],
       [ 1.749561, -0.606031,  1.914146,  1.6292  , -0.515519,  1.996283]])
Coordinates:
  * index     (index) MultiIndex
  - first     (index) object 'bar' 'bar' 'baz' 'baz' 'foo' 'foo'
  - second    (index) object 'one' 'two' 'one' 'two' 'one' 'two'
  * variable  (variable) int32 0 1 2 3
```
### Stack problem:
I want a dimension merges into another one:
```python
da.stack({'index':['variable']})
```
```
ValueError: cannot create a new dimension with the same name as an existing dimension
```

### Unstack problem:
Unstacking by the whole Multindex worked:
```python
da.unstack('index')
```
```
<xarray.DataArray (variable: 4, first: 3, second: 2)>
array([[[ 0.379189,  1.082292],
        [-2.073478, -0.84626 ],
        [-1.529927, -0.837407]],

       [[-0.267983, -0.2516  ],
        [-1.016653, -0.085762],
        [-0.058382, -0.667891]],

       [[-0.013488, -0.855332],
        [-0.038072, -0.385211],
        [-2.149742, -0.304361]],

       [[ 1.749561, -0.606031],
        [ 1.914146,  1.6292  ],
        [-0.515519,  1.996283]]])
Coordinates:
  * variable  (variable) int32 0 1 2 3
  * first     (first) object 'bar' 'baz' 'foo'
  * second    (second) object 'one' 'two'
```
But unstacking by a specified level failed:
```python
da.unstack('first')
```
```
ValueError: Dataset does not contain the dimensions: ['first']
```

**Comment by 0x0L** [comment]
Hello @ray306 

stack/unstack in xarray is a bit different from pandas mechanics.

- From the `stack` docstring
```
Stack any number of existing dimensions into a single new dimension.

New dimensions will be added at the end, and the corresponding
coordinate variables will be combined into a MultiIndex.
```
Breaking it down, `da.stack({'index': ['variable']})` fails because it's trying to:
1. create a new multi-index with a single level inside (`variable`) [so far so good but probably not what you had in mind]
2. add a new dimension named 'index' with coordinates given by the newly created index. This part yields the error you saw since `da` already has an index named `index`. 

To mesh the `variable` dimension into the `index` dimension, you first need to unstack it:
```python
da.unstack('index').stack(index=('first', 'second', 'variable'))
```

- From the `unstack` docstring
```
Unstack existing dimensions corresponding to MultiIndexes into
multiple new dimensions.

Parameters
----------
dim : str or sequence of str, optional
    Dimension(s) over which to unstack. By default unstacks all
    MultiIndexes.
```
Your `da` array only has two dimensions: `variable` and `index`. That's why you can't `da.unstack('first')`. `first` is a coordinate (along the dimension 'index') not a dimension.

You could use
```
da.unstack('index').stack(index=['second'])
```
but this is somehow the same thing as `da.unstack()` since a multi-index with a single level is totally equivalent to the level itself.

I hope this helps you enjoy xarray and use it more.

**Comment by Hoeze** [comment]
Is there a way without unstacking as well?
(Unstack can be quite wasteful)

**Comment by 0x0L** [comment]
You could do it by creating a flatten view of the underlying numpy array, building the multiindex manually and creating a new DataArray from the view and the multiindex.

**Comment by max-sixty** [comment]
Thanks to @0x0L for the answers. I'll close the issue now, please reopen if there are outstanding questions
