### ISSUE TITLE
Unable to access the mailing list

### ISSUE THREAD

**Issue by qobilidop** [pydata/xarray#3005]
This is not a code issue. But without access to the mailing list, I think I could only post it here.

The issue is that I followed https://xarray.pydata.org/en/stable/#get-in-touch trying to get into the [mailing list](https://groups.google.com/forum/#!forum/xarray), but failed with:
![image](https://user-images.githubusercontent.com/5176695/59124949-d7d6ae00-8915-11e9-9e75-9995cc315b6f.png)

**Comment by max-sixty** [comment]
Thanks @qobilidop !

This is weird - when I go to that link in incognito mode, I get the same error _but also access to the group_:

![image](https://user-images.githubusercontent.com/5635139/59131802-63b1ff80-8941-11e9-8b7a-66c937b5d86c.png)

When I go signed into my Google account which isn't in the group, I get the same error as @qobilidop without access

On the [About page](https://groups.google.com/forum/#!aboutgroup/xarray) I see that post permissions is Members; I don't think that's intentional:

> Access
Anyone can view content.
Anyone can join.
Only members can post.
Only members can view the list of members.

I know Google changed some of their groups default permissions recently; not sure if that is anything to do with this.

Also description has the old name: `Discussion list for xarray: N-D labeled arrays and datasets in Python: http://xray.readthedocs.org/`

Who is admin? @shoyer ? I'm happy to help with some of these admin tasks.

**Comment by shoyer** [comment]
Thanks for the heads up, it appears this was broken by the recent settings changes. It should be fixed now.
