### ISSUE TITLE
.reduce() on a DataArray with Dask distributed immediately executes the preceding portions of the computational graph

### ISSUE THREAD

**Issue by zbarry** [pydata/xarray#3161]
#### MCVE Code Sample

`.mean()` on a `DataArray` pointing to a Dask array returns a Dask array-containing `DataArray` as expected:

```python
da = xr.DataArray(np.zeros((500, 500, 500))).chunk((100, 100, 100)).mean('dim_0')
da
```

```
<xarray.DataArray (dim_1: 500, dim_2: 500)>
dask.array<shape=(500, 500), dtype=float64, chunksize=(100, 100)>
Dimensions without coordinates: dim_1, dim_2
```

Calling `.compute()` on this result produces the expected result:

```python
da = xr.DataArray(np.zeros((500, 500, 500))).chunk((100, 100, 100)).mean('dim_0').compute()
```

```
<xarray.DataArray (dim_1: 500, dim_2: 500)>
array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])
Dimensions without coordinates: dim_1, dim_2
```

The `.reduce()` method immediately executes all of the previously queued computations leading up to the new reduce method before even calling the supplied function.

```python
def func(x, axis=None):
    return x

da = xr.DataArray(np.zeros((500, 500, 500))).chunk((100, 100, 100)).mean('dim_0').reduce(func)
```

```
<xarray.DataArray (dim_1: 500, dim_2: 500)>
array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])
Dimensions without coordinates: dim_1, dim_2
```

#### Expected Output

A Dask array when `.reduce(func)` isn't followed up by `.compute()`.

#### Problem Description

When using Dask distributed, the computational graph you are constructing is immediately executed if you call `.reduce()` instead of adding that function as another node in the DAG. This graph execution happens before the function you pass to reduce is called.

#### Output of ``xr.show_versions()``
<details>
INSTALLED VERSIONS
------------------
commit: None
python: 3.7.3 | packaged by conda-forge | (default, Jul  1 2019, 21:52:21) 
[GCC 7.3.0]
python-bits: 64
OS: Linux
OS-release: 3.10.0-693.21.1.el7.x86_64
machine: x86_64
processor: x86_64
byteorder: little
LC_ALL: None
LANG: en_US.UTF-8
LOCALE: en_US.UTF-8
libhdf5: 1.10.4
libnetcdf: 4.6.2

xarray: 0.12.3
pandas: 0.25.0
numpy: 1.16.4
scipy: 1.3.0
netCDF4: 1.5.1.2
pydap: None
h5netcdf: None
h5py: 2.9.0
Nio: None
zarr: None
cftime: 1.0.3.4
nc_time_axis: None
PseudoNetCDF: None
rasterio: None
cfgrib: None
iris: None
bottleneck: None
dask: 2.1.0
distributed: 2.1.0
matplotlib: 3.1.1
cartopy: None
seaborn: None
numbagg: None
setuptools: 41.0.1
pip: 19.2.1
conda: None
pytest: 5.0.1
IPython: 7.6.1
sphinx: 2.1.2
</details>

**Comment by shoyer** [comment]
Yikes, this is pretty bad!

Thanks for the clear code to reproduce it.

**Comment by dcherian** [comment]
This ends up being because `allow_lazy=False`

https://github.com/pydata/xarray/blob/3f9069ba376afa35c0ca83b09a6126dd24cb8127/xarray/core/variable.py#L1412-L1460

I don't see why we need this kwarg or why it shouldn't be `True` by default. This kwarg is undocumented in `dataset.py`
https://github.com/pydata/xarray/blob/3f9069ba376afa35c0ca83b09a6126dd24cb8127/xarray/core/dataset.py#L3997-L4029

and invisible in `dataarray.py`
https://github.com/pydata/xarray/blob/3f9069ba376afa35c0ca83b09a6126dd24cb8127/xarray/core/dataarray.py#L2106-L2139

**Comment by shoyer** [comment]
I don't remember exactly why I added the `allow_lazy` argument. I think my original concern was backwards compatibility (when we were first adding dask!) with uses of `reduce` that expected to be applied to NumPy arrays, not dask arrays.

We do something similar in `apply_ufunc` with `dask='forbidden'`, but rather than automatically coercing to NumPy arrays we raise an error if a dask array is encountered. This seems much more sensible.

At this point, I think we would probably just remove the argument and always default to `allow_lazy=True`. Or possibly `allow_lazy=False` should result is an error instead of automatic coercion, and we should expose/document it as a public argument.

**Comment by dcherian** [comment]
> we would probably just remove the argument and always default to allow_lazy=True.

This seems best.
