### ISSUE TITLE
Accessing COG overviews with read_rasterio

### ISSUE THREAD

**Issue by rsignell-usgs** [pydata/xarray#3269]
[It's considered best practice to create cloud-optimized geotiff (COG) with overviews](https://medium.com/@_VincentS_/do-you-really-want-people-using-your-data-ec94cd94dc3f), which are essentially copies of the dataset at different resolutions to allow fast representation at different scales. 

It would be nice if we could pick a specific overview using `xr.read_rasterio`, perhaps by just an additional parameter on the call, like `xr.read_rasterio(url, overview=512)` or something.

Currently we need to use Rasterio to find out what the overlays are, for example:
```python
url = 'https://esip-pangeo-uswest2.s3-us-west-2.amazonaws.com/sciencebase/Southern_California_Topobathy_DEM_1m_cog.tif'
src = rasterio.open(url, 'r')
[src.overviews(i) for i in src.indexes]
``` 
which results in:
```
[[4, 8, 16, 32, 64, 128, 256, 512, 1023]]
```
See the notebook here for the hack workaround to extract an overlay from COG:
https://nbviewer.jupyter.org/gist/rsignell-usgs/dc4cf94fae97d085f6f2b9b896ec5336

**Comment by dcherian** [comment]
That kwarg looks good to me. Can you send in a PR?

**Comment by scottyhq** [comment]
@dcherian I was just revisiting a use-case for this and realized `xr.open_rasterio()` does not take **kwargs. 
http://xarray.pydata.org/en/stable/generated/xarray.open_rasterio.html#xarray.open_rasterio 

I think this would be easy to implement because a while back rasterio implemented a keyword argument so that you can do rasterio.open(path, overview_level=3)
https://github.com/mapbox/rasterio/issues/1504 

So is this just a matter of accepting kwargs in xr.open_rasterio() and passing them through?
https://github.com/pydata/xarray/blob/4aa7622b6ff16647df64fe69f39438b7cbe9576c/xarray/backends/rasterio_.py#L241

As seems to be done here for example:
https://github.com/pydata/xarray/blob/cc271e61077c543e0f3b1a06ad5e905ea2c91617/xarray/backends/h5netcdf_.py#L164

**Comment by dcherian** [comment]
looks right to me. Let's try it!
