### ISSUE TITLE
mypy --strict fails on scripts/packages depending on xarray; __all__ required

### ISSUE THREAD

**Issue by aldanor** [pydata/xarray#3695]
Checked this with both 0.14.1 and master branch.

Create `foo.py`:

```python
from xarray import DataArray
```

and run:

```sh
$ mypy --strict foo.py
```

which results in

```
foo.py:1: error: Module 'xarray' has no attribute 'DataArray'
Found 1 error in 1 file (checked 1 source file)
```

I did a bit of digging trying to make it work, it looks like what makes the above script work with mypy is adding

```python
__all__ = ('DataArray',)
```

to `xarray/__init__.py`, otherwise mypy treats those imports as "private" (and is correct in doing so).

Should `__all__` be added to the root `__init__.py`? To any `__init__.py` in subpackages as well?

**Comment by shoyer** [comment]
I'm a little surprised that mypy cares about `__all__`. For our `__init__.py` file, we are actually pretty careful to only define variables that are in xarray's public API, so `__all__` was otherwise redundant.

In principle I have no objection to adding this, but it would be nice to if you could dig up a reference that explains mypy's behavior.

**Comment by aldanor** [comment]
https://mypy.readthedocs.io/en/latest/command_line.html#cmdoption-mypy-no-implicit-reexport

**Comment by aldanor** [comment]
Any thoughts?
