### ISSUE TITLE
open_mfdataset(paths, combine='nested') with and without concat_dim=None

### ISSUE THREAD

**Issue by seth-p** [pydata/xarray#4044]
Is there a good reason `open_mfdataset(paths, combine='nested')` produces an error rather than work as `open_mfdataset(paths, combine='nested', concat_dim=None)`?

**Comment by TomNicholas** [comment]
Hi @seth-p ,

Just to be sure I understand your question, are you asking why `concat_dim` doesn't default to `None` in `open_mfdataset`?

If so, that behaviour is there currently because it's being adapted from a previous, different behaviour, which requires a special placeholder value to give certain backwards-compatible behaviour by default.

But you raise a good point that in future, when `combine='nested'`, the default value of `concat_dim` should be `None`, so I've [pushed a commit](https://github.com/pydata/xarray/pull/3926/commits/c14f9d1ca9620bcb8790e87b0531730578466690) to #3926 to ensure it will, and you should see that behaviour in the next major release.

**Comment by seth-p** [comment]
@TomNicholas , yes, thank you.
