### ISSUE TITLE
Type checking fails for multiplication

### ISSUE THREAD

**Issue by jenssss** [pydata/xarray#4054]
#### MCVE Code Sample

I save the following in a file called "foo.py"
```python
import xarray as xr

def mul(x: float, y: xr.Dataset):
    return x*y

```
and run
```
mypy foo.py
```

#### Expected Output

This should give
```
Success: no issues found in 1 source file
```

#### Problem Description

Instead I get the output
```
foo.py:4: error: Unsupported operand types for * ("float" and "Dataset")
```
It gives a similar error for addition.
If I reverse the order of multiplication it works as expected, namely
```python
import xarray as xr

def mul(x: float, y: xr.Dataset):
    return y*x

```
gives
```
Success: no issues found in 1 source file
```

But it would be nice if it also worked when the float is first, so I don't have to change a lot existing code to get typechecking to work.

#### Versions
I tested on version 0.15.1 and on the current master

<details><summary>Output of <tt>xr.show_versions()</tt></summary>

INSTALLED VERSIONS
------------------
commit: None
python: 3.8.2 (default, May  7 2020, 20:00:49) 
[GCC 7.3.0]
python-bits: 64
OS: Linux
OS-release: 5.4.0-29-generic
machine: x86_64
processor: x86_64
byteorder: little
LC_ALL: None
LANG: en_US.UTF-8
LOCALE: en_US.UTF-8
libhdf5: None
libnetcdf: None

xarray: 0.15.2.dev61+gbd84186a
pandas: 1.0.3
numpy: 1.18.4
scipy: None
netCDF4: None
pydap: None
h5netcdf: None
h5py: None
Nio: None
zarr: None
cftime: None
nc_time_axis: None
PseudoNetCDF: None
rasterio: None
cfgrib: None
iris: None
bottleneck: None
dask: None
distributed: None
matplotlib: None
cartopy: None
seaborn: None
numbagg: None
pint: None
setuptools: 46.2.0.post20200511
pip: 20.0.2
conda: None
pytest: None
IPython: None
sphinx: None

</details>

**Comment by Zeitsperre** [comment]
We're currently working on a library largely based on xarray and have seen the same types of errors from mypy (PR in our project that is currently trying to integrate mypy: https://github.com/Ouranosinc/xclim/pull/532). Currently working off of xarray v0.16.

I also wanst to note this error is raised for other operations as well (`+`, `-`, `/`, and `*`) between `xarray.DataArray` and `xarray.Datasets`.

**Comment by max-sixty** [comment]
Yes, this looks like incomplete typing. 

We would take a PR for these for sure.

**Comment by rhkleijn** [comment]
I have implemented a possible solution to have typing for all unary and binary operators which works for mypy and also displays correctly inferred type hints on hovering over the code in Pylance (with VS Code) and PyCharm. The approach involves generating a stub file using a simple helper script. I'll open a draft PR so you can see this approach and for soliciting feedback.

I have been experimenting with all kinds of other approaches to solve this issue but this was the only one with a satisfactory result. For reference, and jotting down from memory, I think I tried the following approaches without much success:

- add the typing information to the ``not_implemented`` function in https://github.com/pydata/xarray/blob/971bad7c21551f297d3e1e24e3779488ea1b9565/xarray/core/arithmetic.py#L83-L105
- adding type declarations in a Generic mixin class parameterized on the return type of the methods. This doesn't handle dependencies of the return type on the type of the second argument of binary operators.
- adding type declarations in a Generic mixin class parameterized on a Callback Protocol (PEP 544). This is too much
  magic for typing tools to grasp.
- adding type declarations directly using a Callback Protocol. This seems to works fine for regular function but for methods the type of self of the class implementing the Protocol gets confused with the type of self in the Protocol itself.
- using an overloaded abstract method for one operator (and then assigning the method to the dunders of all other operators to avoid a lot of repetition) results in mypy errors because it does not recognize that the concrete implementations are added dynamically. Making them concrete and returning NotImplemented doesn't work as type checkers are not sufficiently aware of the fallback logic of calling the corresponding reflexive method on the other argument of the binary operation. And raising causes some type checkers to think NoReturn is the intended return type.
