### ISSUE TITLE
Confusing behaviour with .weighted

### ISSUE THREAD

**Issue by t93hempel** [pydata/xarray#4207]
Using xarray's .weighted() following the example on:
http://xarray.pydata.org/en/stable/examples/area_weighted_temperature.html

I noticed that depending on the order, the data array sometimes reverts to its not weighted form. 

Using the tutorial dataset and following the first steps of the example up to the "Weighted mean" step. I get the correct weighted results with either of:
`air.weighted(weights).mean(('lon', 'lat')).plot()`
`air.weighted(weights).mean(('lat', 'lon')).plot()`
`air.weighted(weights).mean('lat').mean('lon').plot()`

but using:
`air.weighted(weights).mean('lon').mean('lat').plot()`
results in the unweighted mean.

This is not really a bug, but it is still confusing since there is no notification that the weighting is not applied.

**Comment by keewis** [comment]
this is expected, I think: `weights` was computed using `lat`:
```python
weights = np.cos(np.deg2rad(air.lat))
weights.name = "weights"
weights
```
which means that the weights are only defined for a computation along `lat`.

Since the result of `air.weighted(weights).mean("lon")` is a normal `DataArray`, the weights are discarded and the result is indeed the same as the unweighted operation.

So I guess you should treat the `.weighted(...).mean(...)` as a unit:
```python
xr.testing.assert_allclose(
    air.mean("lon").weighted(weights).mean("lat"),
    air.weighted(weights).mean("lat").mean("lon"),
)
```
does not raise.

Then again, we could try to always multiply with `weights` before the computation. Any comments, @mathause?

**Comment by mathause** [comment]
@keewis' interpretation is correct - `weighted(...).mean(...)` is a unit - `weighted` is a class and `mean` its method. The second `mean` is then again the method of the `DataArray`. Your example is actually a good argument for naming this `weighted_mean(...)` instead of `weighted(...).mean(...)`.

The weights are also applied in `air.weighted(weights).mean("lon")`, but they cancel out. What happens is:
```python
(air * weights).sum("lon") / weighs.sum("lon")
```
Due to floating point errors `air.weighted(weights).mean("lon")` is only approximately the same as `air.mean("lon")`.

**Comment by t93hempel** [comment]
Thank you very much @mathause and @keewis !! 
That makes a lot of sense.
