### ISSUE TITLE
to_dataframe: no valid index for a 0-dimensional object

### ISSUE THREAD

**Issue by ghislainp** [pydata/xarray#4228]
**What happened**: 
`xr.DataArray([1], coords=[('onecoord', [2])]).sel(onecoord=2).to_dataframe(name='name')` raise an exception `ValueError: no valid index for a 0-dimensional object`

**What you expected to happen**:

the same behavior as: `xr.DataArray([1], coords=[('onecoord', [2])]).to_dataframe(name='name')`

**Anything else we need to know?**:

I see that the array after the selection has no "dims" anymore, and this is what cause the error.  but it still has one "coords", this is confusing.  Is there any documentation about this difference ?

**Environment**:

<details>
INSTALLED VERSIONS
------------------
commit: None
python: 3.7.6 | packaged by conda-forge | (default, Jun  1 2020, 18:57:50) 
[GCC 7.5.0]
python-bits: 64
OS: Linux
OS-release: 4.19.0-9-amd64
machine: x86_64
processor: 
byteorder: little
LC_ALL: None
LANG: en_US.UTF-8
LOCALE: en_US.UTF-8
libhdf5: 1.10.5
libnetcdf: 4.7.4

xarray: 0.15.1
pandas: 1.0.4
numpy: 1.18.5
scipy: 1.4.1
netCDF4: 1.5.3
pydap: None
h5netcdf: None
h5py: 2.10.0
Nio: None
zarr: 2.4.0
cftime: 1.1.3
nc_time_axis: None
PseudoNetCDF: None
rasterio: None
cfgrib: None
iris: None
bottleneck: 1.3.2
dask: 2.18.1
distributed: 2.18.0
matplotlib: 3.2.1
cartopy: None
seaborn: 0.10.1
numbagg: None
setuptools: 47.3.1.post20200616
pip: 20.1.1
conda: 4.8.3
pytest: 5.4.3
IPython: 7.15.0
sphinx: 3.1.1

</details>

**Comment by ghislainp** [comment]
thanks for the very clear response. The behaviro make sense.

In fact, I should have explained what I'm trying to achieve, as this is kind of "take". I've a dict like this:
{'label1' : dict(coord1=1, coord2=4), 
'label2' : dict(coord1=5, coord2=6),
'label3' : dict(coord1=4, coord2=2),
}
and I want to build an xarray (and then a dataframe) with coord1 and coord2 replaced by a new dims with values 'label1', 'label2', 'label3'.
 
I've done that by iterating over the dict, selecting with sel using the dict values, convert to dataframe and then concat the dataframes. pd.concat([x.sel(**d[k]).to_dataframe() or k in d]

A better option would be to do this "sel" or "take" with xarray only.
Do you have an idea how to do it with existing xarray methods?

**Comment by dcherian** [comment]
You could do it with "advanced indexing" by providing a dataarray to the `.sel` or `.isel` methods: https://xarray.pydata.org/en/stable/indexing.html#more-advanced-indexing

``` python
da = xr.DataArray([[1, 2, 3], [4,5,6]], dims=["coord1", "coord2"], coords={"coord2": [10, 20, 30], "coord1": [1,2]}) 

i1 = xr.DataArray([1, 0], dims=["z"], coords={"z": ["label1", "label2"]})
i2 = xr.DataArray([2, 1], dims=["z"], coords={"z": ["label1", "label2"]})  

da.isel(coord1=i1, coord2=i2, drop=True).to_dataframe(name="asd")
```

```
        asd
z          
label1    6
label2    2
```

**Comment by PGijsbers** [comment]
Hi, I tried to work on this issue. I made the changes on the `fix_#4228` branch of my fork (all in [this commit](https://github.com/PGijsbers/xarray/commit/50d1ac9b82ff43c1a11f19ed554acd23219bf1c8)). 

Unfortunately I can't currently reproduce the full test environment. I am running `python` through the standard release and not `anaconda/miniconda`, and I am hesitant to install it alongside my current setup because that has caused some issues in the past. Simply installing `pytest` in my environment did allow me to run some tests (4031 passed, 4237 skipped, 66 xfailed, 15 xpassed, 41 warnings). Most notably the edited test ran successfully (i.e. pass on fresh pull, fail after I updated the test, pass again after I updated code).

Please let me know if that's good enough to open a pull request and ask for a review.

**Comment by dcherian** [comment]
> f that's good enough to open a pull request and ask for a review.

please go ahead and open a PR. Thanks.
