### ISSUE TITLE
rtd DataArray.to_netcdf

### ISSUE THREAD

**Issue by raybellwaves** [pydata/xarray#4413]
http://xarray.pydata.org/en/stable/generated/xarray.DataArray.to_netcdf.html#xarray.DataArray.to_netcdf

I believe there is a way to hyperlink to `xarray.Dataset.to_netcdf`. I believe there is also a way for sphinx to render the Note section e.g. in the doc string add `.. note::`

**Comment by keewis** [comment]
good catch, @raybellwaves. The link is missing a `:py:meth:` prefix and should be easy to fix.

However, the note is rendered that way because it is part of the `Notes` section, and might look strange because there's only that section. For example, in [DataArray.map_blocks](http://xarray.pydata.org/en/stable/generated/xarray.DataArray.map_blocks.html) directly after it there's `See Also`. So I guess we could add a `See Also` section and/or copy the parameter documentation from `Dataset.to_netcdf` to fix this.
