### ISSUE TITLE
Problem decoding times in data from OpenDAP server

### ISSUE THREAD

**Issue by albertotb** [pydata/xarray#4422]
**What happened**: I download data from an OpenDAP server using `xarray` directly. Then, I save the `xarray.DataArray` object to file. The times I get in the index are different (see output below). Note, for instance, the second element of the index in the original dataset is `2020-09-13T00:59:59.999997000`, while after saving and loading again is `2020-09-13T00:59:59.999997056`

**What you expected to happen**: I'm not sure if this is a bug or just something that we cannot rely upon, but I would expect the index `time` to have the same values in both objects.

**Minimal Complete Verifiable Example**:

```python
import datetime as dt
import xarray as xr
import cftime

print(xr.__version__)
print(cftime.__version__)

yesterday = (dt.date.today() - dt.timedelta(days=1)).strftime('%Y%m%d')
src = xr.open_dataset(f'https://nomads.ncep.noaa.gov/dods/gfs_0p25_1hr/gfs{yesterday}/gfs_0p25_1hr_00z')

print('-'*60)

var = src['ugrd10m'].isel(time=slice(0, 8))

print('Original: ', var.time)
var.to_netcdf('test.nc')

print('-'*60)

dst = xr.open_dataset('test.nc')
print('Recovered:', dst.time)

```

**Anything else we need to know?**: 

<details><summary>Output of the previous script</tt></summary>

```
0.16.0
1.2.1
------------------------------------------------------------
Original:  <xarray.DataArray 'time' (time: 8)>
array(['2020-09-13T00:00:00.000000000', '2020-09-13T00:59:59.999997000',
       '2020-09-13T02:00:00.000003000', '2020-09-13T03:00:00.000000000',
       '2020-09-13T03:59:59.999997000', '2020-09-13T05:00:00.000003000',
       '2020-09-13T06:00:00.000000000', '2020-09-13T06:59:59.999997000'],
      dtype='datetime64[ns]')
Coordinates:
  * time     (time) datetime64[ns] 2020-09-13 ... 2020-09-13T06:59:59.999997
Attributes:
    grads_dim:      t
    grads_mapping:  linear
    grads_size:     121
    grads_min:      00z13sep2020
    grads_step:     1hr
    long_name:      time
    minimum:        00z13sep2020
    maximum:        00z18sep2020
    resolution:     0.041666668
------------------------------------------------------------
Recovered: <xarray.DataArray 'time' (time: 8)>
array(['2020-09-13T00:00:00.000000000', '2020-09-13T00:59:59.999997056',
       '2020-09-13T02:00:00.000002944', '2020-09-13T03:00:00.000000000',
       '2020-09-13T03:59:59.999997056', '2020-09-13T05:00:00.000002944',
       '2020-09-13T06:00:00.000000000', '2020-09-13T06:59:59.999997056'],
      dtype='datetime64[ns]')
Coordinates:
  * time     (time) datetime64[ns] 2020-09-13 ... 2020-09-13T06:59:59.999997056
Attributes:
    grads_dim:      t
    grads_mapping:  linear
    grads_size:     121
    grads_min:      00z13sep2020
    grads_step:     1hr
    long_name:      time
    minimum:        00z13sep2020
    maximum:        00z18sep2020
    resolution:     0.041666668
```
</details>

**Environment**:

I create a clean enviroment with:

```conda create -n xarray_test python=3.6 xarray cfgrib cftime netCDF4```

<details><summary>Output of <tt>xr.show_versions()</tt></summary>

```
>>> xr.show_versions()

INSTALLED VERSIONS
------------------
commit: None
python: 3.6.12 |Anaconda, Inc.| (default, Sep  8 2020, 23:10:56) 
[GCC 7.3.0]
python-bits: 64
OS: Linux
OS-release: 4.4.0-112-generic
machine: x86_64
processor: x86_64
byteorder: little
LC_ALL: en_US.utf-8
LANG: en_US.utf-8
LOCALE: en_US.UTF-8
libhdf5: 1.10.6
libnetcdf: 4.7.4

xarray: 0.16.0
pandas: 1.1.1
numpy: 1.19.1
scipy: None
netCDF4: 1.5.4
pydap: None
h5netcdf: None
h5py: None
Nio: None
zarr: None
cftime: 1.2.1
nc_time_axis: None
PseudoNetCDF: None
rasterio: None
cfgrib: 0.9.8.4
iris: None
bottleneck: None
dask: None
distributed: None
matplotlib: None
cartopy: None
seaborn: None
numbagg: None
pint: None
setuptools: 49.6.0.post20200814
pip: 20.2.2
conda: None
pytest: None
IPython: None
sphinx: None
```

</details>

**Comment by spencerkclark** [comment]
### Description of the problem

I believe the issue here stems from the units attribute in the original dataset:
```
In [1]: import xarray as xr

In [2]: url = "https://nomads.ncep.noaa.gov/dods/gfs_0p25_1hr/gfs20200920/gfs_0p25_1hr_00z"

In [3]: ds = xr.open_dataset(url, decode_times=False)

In [4]: ds.time.attrs["units"]
Out[4]: 'days since 1-1-1 00:00:0.0'
```

This is an unusual format -- ordinarily we'd expect zero-padded year, month, and day values.  Pandas misinterprets this and parses the reference date to 2001-01-01:

```
In [5]: import pandas as pd

In [6]: pd.Timestamp("1-1-1 00:00:0.0")
Out[6]: Timestamp('2001-01-01 00:00:00')
```

Of course, with time values on the order 700000 and units of days, this results in dates outside the nanosecond-precision range of the `np.datetime64` dtype and throws an error; xarray catches this error and then uses cftime to decode the dates.  cftime parses the reference date properly, so in the end the dates are decoded correctly (good!).

There's a catch though.  When saving the dates back out to a file, the odd units remain in the encoding of the time variable. When parsing the reference date, xarray again first tries using pandas.  This time, there's nothing that stops xarray from proceeding, because we are no longer bound by integer overflow (taking the difference between a date in 2020 and a date in 2001 is perfectly valid for nanosecond-precision dates).  So encoding succeeds, and we no longer need to try with cftime.  

```
In [7]: ds = xr.decode_cf(ds)

In [8]: subset = ds["ugrd10m"].isel(time=slice(0, 8))

In [9]: subset.to_netcdf("test.nc")

In [10]: recovered = xr.open_dataset("test.nc", decode_times=False)

In [11]: recovered.time.attrs["units"]
Out[11]: 'days since 2001-01-01'
```

Thus when we read the file the first time, decoding happens with cftime and when we read the file the second time, decoding happens with pandas (encoding was also different for the two files).  This is the reason for the difference in values.

### Workaround

To get an accurate round-trip I would recommend overwriting the units attribute to something that pandas parses correctly:

```
In [12]: ds = xr.open_dataset(url, decode_times=False)

In [13]: ds.time.attrs["units"] = "days since 0001-01-01"

In [14]: ds = xr.decode_cf(ds)

In [15]: subset = ds["ugrd10m"].isel(time=slice(0, 8))

In [16]: subset.to_netcdf("test.nc")

In [17]: recovered = xr.open_dataset("test.nc")

In [18]: recovered.time
Out[18]:
<xarray.DataArray 'time' (time: 8)>
array(['2020-09-20T00:00:00.000000000', '2020-09-20T00:59:59.999997000',
       '2020-09-20T02:00:00.000003000', '2020-09-20T03:00:00.000000000',
       '2020-09-20T03:59:59.999997000', '2020-09-20T05:00:00.000003000',
       '2020-09-20T06:00:00.000000000', '2020-09-20T06:59:59.999997000'],
      dtype='datetime64[ns]')
Coordinates:
  * time     (time) datetime64[ns] 2020-09-20 ... 2020-09-20T06:59:59.999997
Attributes:
    grads_dim:      t
    grads_mapping:  linear
    grads_size:     121
    grads_min:      00z20sep2020
    grads_step:     1hr
    long_name:      time
    minimum:        00z20sep2020
    maximum:        00z25sep2020
    resolution:     0.041666668
```

**Comment by spencerkclark** [comment]
I don't know if there is anything we can do to make this less opaque.  My gut feeling is to label this as a "metadata issue," and recommend addressing it at the file level, but it is awkward that it sort of works as is, but not quite.  

This is not the first time an issue has been raised related to units like this:
https://github.com/pydata/xarray/blob/13c09dc28ec8ff791c6d87e2d8e80c362c65ffd4/xarray/tests/test_coding_times.py#L112-L116

**Comment by albertotb** [comment]
Thank you very much for the detailed explanation and taking the time to look into this. I had a feeling it had to do with time decoding, but did not know exactly what was going on. IMHO the confusing thing is that the file parses without problems, so maybe a warning indicating that the parsing failed with pandas could help. 

Also, would this be solved if using `use_cftime=True` when reading back the file?

**Comment by dcherian** [comment]
> This is an unusual format -- ordinarily we'd expect zero-padded year, month, and day values.

Can we raise an error here? Interpreting `1-1-1` as `2001-01-01` is really weird.

**Comment by spencerkclark** [comment]
> Also, would this be solved if using `use_cftime=True` when reading back the file?

To be honest I'm not sure.  You could give it a try -- the only thing there is that you'd need to cast the times back to `np.datetime64` if that was ultimately the date type you wanted to go with (instead of a cftime date type).

> If I understood correctly the code you quote, in that case you are overwritting the units attribute. Maybe the same could be done in this case.

In the test case I think we're merely acknowledging that the remaining part of the test would fail with these units.  I agree with you and @dcherian though, it's super weird that pandas behaves the way it does here.  Considering this isn't the first time these units have come up, it might be worth special-casing them in some way.

**Comment by dopplershift** [comment]
Probably shouldn't raise an error for `1-1-1` since that's valid according to the [Climate and Forecasting netCDF conventions](http://cfconventions.org/Data/cf-conventions/cf-conventions-1.8/cf-conventions.html#time-coordinate) (see examples 4.5 and 4.6). In fact, it works perfectly when using `use_cftime=True` both for the original data and reading in the data from disk.

**Comment by spencerkclark** [comment]
@dopplershift I agree an error doesn't really make sense, particularly since these units appear in the CF conventions -- thanks for pointing that out.

I hesitate to say things are working *perfectly* with `use_cftime=True`.  While the decoded time objects seem to be round-tripped exactly -- which is great -- the encoded values are not, since the date in the units encoding changes from `"1-1-1 00:00:0.0"` to `"2001-01-01"`.  We should be able to do better there.

**Comment by spencerkclark** [comment]
It's a little more delicate, but I also think we should be able to fix this in the case of `use_cftime=None` (the default), so that these dates can still be represented with the `np.datetime64` dtype and round-trip in a sensible way.

**Comment by dcherian** [comment]
> shouldn't raise an error for 1-1-1 since that's valid according to the Climate and Forecasting netCDF conventions

OK good point. Thanks @dopplershift 

One solution would be to extract this bit of the units string and 0-pad as necessary before passing to pandas. We would have to be careful to keep the unmodified `units` attribute in encoding.

**Comment by dopplershift** [comment]
I'd say in the case of `use_ctime=True` that it's a bug that it ever uses pandas for date parsing.

**Comment by albertotb** [comment]
I just want to add here for reference that this issue was posted earlier but closed at the time. I will leave this here just to link them both and to note that this is fixed: https://github.com/pydata/xarray/issues/827
