### ISSUE TITLE
open_dataset regression

### ISSUE THREAD

**Issue by dcherian** [pydata/xarray#5098]
**What happened**:

`open_dataset` doesn't replace `~` any more

**What you expected to happen**:

should replace `~` for backward compatibility

**Minimal Complete Verifiable Example**:

```python
import xarray as xr

da = xr.DataArray([1, 2, 3])
da.to_netcdf("~/bug_report.nc")

xr.open_dataarray("~/bug_report.nc")
```

**Anything else we need to know?**:
works on 0.17.0, fails on master

**Comment by aurghs** [comment]
I think that this is part of the refactor done by @alexamici when he has removed `_normalize_path`: https://github.com/pydata/xarray/pull/4701
We decided to demand the path interpretation to the backends. 

I'll have a look to understand how to fix it.

**Comment by alexamici** [comment]
The reason to delegate all path normalisation to backends is that not all strings are paths, for example `NETCDF:"~/sst.nc":tos` is a valid source string for GDAL / rasterio.

I would suggest to add path normalisation to the backends that needs them, in order to avoid any special case in the common code path.

@aurghs I suggest you add `os.path.expanduser` in the netCDF backend.
