### ISSUE TITLE
Progressbar for groupby operations?

### ISSUE THREAD

**Issue by pgierz** [pydata/xarray#5332]
I recently learned that `tqdm` can automatically create a progress bar for you when you are doing expensive groupby/map operations. See for instance here: https://stackoverflow.com/questions/18603270/progress-indicator-during-pandas-operations

Would it be simple to implement something similar in Xarray? The documentation seems to read as if the groupby is heavily inspired by pandas.

- - - - 

**Is your feature request related to a problem? Please describe.**
No, everything works as expected, this would just be a "quality of life" improvement. 

**Describe the solution you'd like**

The [implementation in tqdm](https://github.com/tqdm/tqdm/blob/bcce20f771a16cb8e4ac5cc5b2307374a2c0e535/tqdm/_tqdm_pandas.py) states:
```
Registers the given `tqdm` instance with `pandas.core.groupby.DataFrameGroupBy.progress_apply`.
```

I suppose something similar would need to be implemented in Xarray, and then we might be able to copy the tqdm logic.

**Describe alternatives you've considered**
I could loop over whatever dimension I have and make my own progress bar, but that seems like defeating the purpose of groupby.

**Comment by max-sixty** [comment]
The main issue with these is that we don't generally get callbacks so we can render progress, because we're trying to keep as much of the operation out of python as possible.

We actually do with groupby at the moment, but we're hopefully moving to numpy_groupies, which will mean we don't run the loop in python.

I'd be interested if there are approaches to this — which would be a very useful feature — for functions that don't return to python before the end of the operation.

**Comment by max-sixty** [comment]
NB: the example linked only operates on `.apply` in pandas, which runs in python, and so is slow. We want to do that as little as possible. Notably, there is no way of a progressbar with groupby in pandas.
