### ISSUE TITLE
DataArray.rolling should have center=True as default

### ISSUE THREAD

**Issue by sethmcg** [pydata/xarray#5523]
DataArray.rolling should default to center=True, putting the time coordinate (label) of the aggregated value at the center of the interval.

**What happened**: using rolling() to average over a period puts the result at the end of the period

**What you expected to happen**: the result should go in the middle of the period

There are some cases where you may want to put the label / time coordinate at the beginning or end of the interval instead, but this generally leads to confusion, and should be avoided unless you have a really good reason.  The default should be that the result of applying an aggregation over a time interval is located at the middle of the time interval.  (Voice of hard-won experience here.)

To be general, you would want to allow the user to specify whether the result goes at the beginning, middle, or end of the interval, so you'd change from center=(True|False) to something like resultAt=("beginning"|"middle"|"end"), but that may be too big a change in the interface, so I think it's reasonable to stick with center=(True|False) with True as the default.

**Comment by max-sixty** [comment]
Hi @sethmcg — I appreciate people will have different opinions on what default seems most natural to them. We have to decide on a default for everyone, though. And we do that by assessing which value would be wanted by a new user, and we try and minimize changes.

As part of assessing the value which would wanted by a new user, we can consider that defaults in other libraries — in this case they mostly have the same default as xarray's (or do you see it differently?). Maybe that's because everyone is doing it wrong, but even if that were the case — such is the permanence of inadequate equilibria.
