### ISSUE TITLE
RTD build failing

### ISSUE THREAD

**Issue by dcherian** [pydata/xarray#5758]
The current RTD build is failing in `plotting.rst`

```
sphinx.errors.SphinxParallelError: RuntimeError: Non Expected exception in `/home/docs/checkouts/readthedocs.org/user_builds/xray/checkouts/latest/doc/user-guide/plotting.rst` line None

Sphinx parallel build error:
RuntimeError: Non Expected exception in `/home/docs/checkouts/readthedocs.org/user_builds/xray/checkouts/latest/doc/user-guide/plotting.rst` line None
[IPKernelApp] WARNING | Parent appears to have exited, shutting down.
```

**Comment by mathause** [comment]
The failure might be the download of https://naciscdn.org/naturalearth/110m/physical/ne_110m_coastline.zip timing out (I had some issues with that in the tests of the regionmask package)

**Comment by kmuehlbauer** [comment]
@mathause I've experienced that too today in one of my packages. I've learned that if cartopy is used, `cartopy_offlinedata` package exist. But that is 260MB.

**Comment by mathause** [comment]
I created some workarounds for the problem. But they are only applicable for tests and unfortunately not for the docs...

<details>

The issue was that cartopy does not set a `timeout` in `urlopen` so my tests were running forever. Also I did not want to fail my test suite if the download fails. I am now working around this, skipping tests if it cannot be downloaded. (For the docs the no timeout does not seem to be a problem, though.)

https://github.com/regionmask/regionmask/blob/e59aaa94f07e1579033ef2436701a1fe99ff3659/regionmask/tests/utils.py#L70

I also cache `~/.local/share/cartopy/` in github actions (note that the cache is only saved if the tests succeed, so it's only a partial solution).

https://github.com/regionmask/regionmask/blob/e59aaa94f07e1579033ef2436701a1fe99ff3659/.github/workflows/ci.yaml#L38

</details>

**Comment by kmuehlbauer** [comment]
@mathause Thanks for sharing. :+1:

**Comment by mathause** [comment]
The issue might have been fixed by https://github.com/conda-forge/cartopy-feedstock/pull/116

**Comment by keewis** [comment]
RTD is working so I think this can be closed
