### ISSUE TITLE
Check for just ... in stack etc, and raise with a useful error message

### ISSUE THREAD

**Issue by dcherian** [pydata/xarray#6051]
**Is your feature request related to a problem? Please describe.**

The following doesn't work
``` python
import xarray as xr

da = xr.DataArray([[1,2],[1,2]], dims=("x", "y"))
da.stack(flat=...)
```

**Describe the solution you'd like**
This could be equivalent to
``` python
da.stack(flat=da.dims)
```

I *think* using `ds.dims` it should be fine for datasets too.

**Comment by max-sixty** [comment]
It still needs to be in a list! Otherwise it would be funky to do `flat=[x, ...]`

```python
In [2]: import xarray as xr
   ...:
   ...: da = xr.DataArray([[1,2],[1,2]], dims=("x", "y"))
   ...: da.stack(flat=[...])
```

**Comment by dcherian** [comment]
Can we special-case `...` and convert it to `[...]`?

**Comment by max-sixty** [comment]
I see @mathause agrees, so I am v happy to be voted into the minority, but I would vote against it — `...` stands for `x, y`, not `[x, y]`, and we're better to hold that line rather than have `...` be a "mood of 'etc'".

I would def be up for updating the error message to check for this mistake.

(I worry that when people disagree we can stay with the status quo, so I really would be fine doing this if you think it's better. Also I didn't get the release done yesterday so I should be downweighted 😁 )

**Comment by dcherian** [comment]
> — ... stands for x, y, not [x, y], and we're better to hold that line rather than have ... be a "mood of 'etc'".

Sounds good to me. `"mood of 'etc'".` is a great phrase!

I also agree with checking for `...` and raising an error asking the user to enter `[...]`
