### ISSUE TITLE
Only auxiliary coordinates are listed in nc variable attribute

### ISSUE THREAD

**Issue by tovogt** [pydata/xarray#6310]
### What happened?

When saving a dataset to a NetCDF file with both dimension and auxiliary coordinates, the data variables' `coordinate` attribute only lists the coordinates that are not related to any dimension (so-called "auxiliary" coordinates).

### What did you expect to happen?

I expect xarray to adhere to the CF conventions where it says:

> Every element of every feature must be unambiguously associated with its space and time coordinates and with the feature that contains it.  The coordinates attribute must be attached to every data variable to indicate the spatiotemporal coordinate variables that are needed to geo-locate the data.
> [from https://cfconventions.org/cf-conventions/cf-conventions.html#coordinates-metadata]

See also this example: https://cfconventions.org/cf-conventions/cf-conventions.html#_single_trajectory

### Minimal Complete Verifiable Example

```Python
import xarray as xr
xr.Dataset({"values": ('time', [0.0, 0.1])},
           coords={
               'time': ('time', [0, 1]),
               'lat': ('time', [5, 4]),
               'lon': ('time', [10, 12])
           }).to_netcdf("test.nc")
```

```bash
$ ncdump -h test.nc
netcdf test {
dimensions:
	time = 2 ;
variables:
	double values(time) ;
		values:_FillValue = NaN ;
		values:coordinates = "lon lat" ;
	int64 time(time) ;
	int64 lat(time) ;
	int64 lon(time) ;
}
```
Note that `values:coordinates` doesn't list the `time` coordinate (as in the example in the CF conventions).

### Anything else we need to know?

I don't want to offend anyone, please correct me if I read the CF conventions in the wrong way or if this is a special case, and in general, the CF conventions recommend to only include auxiliary coordinates in the `coordinates` attribute. I couldn't find any such recommendation in the conventions text, but it's a very long document. What I did find (see my second post) is that it is "permissible, but optional" to list non-auxiliary variables in general, and it is required for the special case of "Discrete Sampling Geometries".

### Environment

```
INSTALLED VERSIONS
------------------
commit: None
python: 3.8.12 | packaged by conda-forge | (default, Oct 12 2021, 21:59:51) 
[GCC 9.4.0]
python-bits: 64
OS: Linux
OS-release: 5.4.0-100-generic
machine: x86_64
processor: x86_64
byteorder: little
LC_ALL: None
LANG: en_US.UTF-8
LOCALE: ('en_US', 'UTF-8')
libhdf5: 1.12.1
libnetcdf: 4.8.1

xarray: 0.19.0
pandas: 1.3.4
numpy: 1.21.4
scipy: 1.7.0
netCDF4: 1.5.8
pydap: None
h5netcdf: None
h5py: 3.4.0
Nio: None
zarr: None
cftime: 1.5.1.1
nc_time_axis: None
PseudoNetCDF: None
rasterio: 1.2.10
cfgrib: 0.9.9.0
iris: None
bottleneck: 1.3.2
dask: 2021.07.1
distributed: 2021.07.1
matplotlib: 3.4.2
cartopy: 0.20.1
seaborn: None
numbagg: None
pint: 0.17
setuptools: 59.2.0
pip: 21.2.1
conda: None
pytest: None
IPython: 7.29.0
sphinx: None
```

**Comment by tovogt** [comment]
If you are interested in a fix, I would modify the following section:
https://github.com/pydata/xarray/blob/613a8fda4f07181fbc41d6ff2296fec3726fd351/xarray/conventions.py#L726-L744
The `variable_coordinates` should be initialized for each variable `v` with the names in `v.dims`. Currently, the dimension names are explicitly excluded. So it seems to me like this behavior has originally been implemented on purpose. I'm really wondering about the reason for this...?

**Comment by dcherian** [comment]
This seems OK to me :+1: a PR would be welcome.

cc @DWesl

**Comment by tovogt** [comment]
Hey @dcherian,

Thanks for your consideration! I just started to create a new branch with my suggested changes, but then I noticed that setting the `coordinates` attribute to include non-auxiliary dimensions by default will let a lot of unit tests fail. That made me think about this again: In fact, always setting the coordinates attribute is permissible according to the conventions. However, most users will probably be confused about the clutter and we might run into some discussions about this in the future.

In my original post, the example can easily be fixed to reflect the coordinate attributes in the conventions (https://cfconventions.org/cf-conventions/cf-conventions.html#_single_trajectory) by enforcing the attribute value in the `encoding`:
```python
import xarray as xr
ds = xr.Dataset(
    {"values": ('time', [0.0, 0.1])},
    coords={
       'time': ('time', [0, 1]),
       'lat': ('time', [5, 4]),
       'lon': ('time', [10, 12])
    })
ds['values'].encoding['coordinates'] = "time lon lat"
ds.to_netcdf("test.nc")
```
```shell
$ ncdump -h test.nc
netcdf test {
dimensions:
	time = 2 ;
variables:
	double values(time) ;
		values:_FillValue = NaN ;
		values:coordinates = "time lon lat" ;
	int64 time(time) ;
	int64 lat(time) ;
	int64 lon(time) ;
}
```

From here, there are several ways to proceed:
1. Stick to the current logic which might be non-conformal with the CF conventions in case of "Discrete Sampling Geometries". However, users can manually fix this by setting the `coordinates` in `encoding`.
2. Enforce to always list all non-auxiliary coordinates in the variable attribute, generating a lot of clutter.
3. Implement a logic to recognize cases where a dataset is a "Discrete Sampling Geometry" and only then list the non-auxiliary coordinates in the variable attribute. This is a bit tricky, and I don't have the time to implement this, I'm afraid.

I actually suggest to choose solution (1) and close this issue as "won't fix". What do you think?

**Comment by DWesl** [comment]
I tried to find what the CF conventions say about including dimension coordinates (I'm using [the name from scitools-iris](https://scitools-iris.readthedocs.io/en/stable/userguide/iris_cubes.html#coordinates) rather than "coordinate variable" as used in the CF conventions to keep myself from getting confused) in the `coordinates` attribute.  From what I can tell, the whole document is consistent with usually excluding dimension coordinates from the `coordinates` attribute.  Most of the [Discrete Sampling Geometry examples in appendix H](https://cfconventions.org/cf-conventions/cf-conventions.html#appendix-examples-discrete-geometries) seem to include the dimension coordinates in the `coordinates` attributes, [though at least one example](https://cfconventions.org/cf-conventions/cf-conventions.html#_orthogonal_multidimensional_array_representation_of_time_series) leaves the dimension coordinates implied rather than explicit.

From what I remember, XArray is based on the netCDF data model, rather than the CF data model, so initializing `variable_coordinates[var_name] = set(variable.dims)` will do the wrong thing if the dataset doesn't set one or more of its dimension coordinates ([example H.2](https://cfconventions.org/cf-conventions/cf-conventions.html#_orthogonal_multidimensional_array_representation_of_time_series) has variables with dimensions `("station", "time")`, but no variable named `station`.  [Section 4.5](https://cfconventions.org/cf-conventions/cf-conventions.html#discrete-axis) makes this practice explicit).  You could work around this by leaving the initialization as it stands but dropping the `if coordinate_name not in variable.dims` condition on including `coordinate_name` as part of the `coordinates` attribute.

> 1. Stick to the current logic which might be non-conformal with the CF conventions in case of "Discrete Sampling Geometries". However, users can manually fix this by setting the coordinates in encoding.

Based on this, I think doing solution one from the previous post on writing a dataset will always be consistent with CF, but assuming that netCDF files XArray reads into datasets will always follow this pattern would be a problem.  I suspect there are tests for reading netCDF files with dimension coordinates included in `coordinates` attributes already, but haven't checked.

> 3. Implement a logic to recognize cases where a dataset is a "Discrete Sampling Geometry" and only then list the non-auxiliary coordinates in the variable attribute. This is a bit tricky, and I don't have the time to implement this, I'm afraid.

If you want to try solution three, almost all Discrete Sampling Geometry files [must have a global attribute called `featureType`](https://cfconventions.org/cf-conventions/cf-conventions.html#featureType).  Since that attribute is recommended for all Discrete Sampling Geometry files, you could declare that the presence of that attribute defines a Discrete Sampling Geometry file for XArray.  However, I don't see any place that says including dimension coordinates in the `coordinates` attribute is required, even for Discrete Sampling Geometry files, and a few places that explicitly say dimension coordinates can be omitted from the `coordinates` attribute, even for Discrete Sampling Geometry files.

The references from CF on whether dimension coordinates can be included in the `coordinates` attribute:

The fifth paragraph of [CF section five](https://cfconventions.org/cf-conventions/cf-conventions.html#coordinate-system) says:

> If the longitude, latitude, vertical or time coordinate is multi-valued, varies in only one dimension, and varies independently of other spatiotemporal coordinates, it is not permitted to store it as an auxiliary coordinate variable.

I *think* this is saying that if you can represent a coordinate using just one dimension, you shouldn't use two (that is, avoid using `np.tile(np.arange(10), (3, 1))` as a longitude coordinate).  The other interpretation is that dimension coordinates must not be included in the `coordinates` attribute, which seems unlikely given that three lines later it says:

> Note that it is permissible, but optional, to list coordinate variables as well as auxiliary coordinate variables in the coordinates attribute.

The first paragraph of the [section on Discrete sampling geometries](https://cfconventions.org/cf-conventions/cf-conventions.html#discrete-sampling-geometries):

> Every element of every feature must be unambiguously associated with its space and time coordinates and with the feature that contains it.  The coordinates attribute must be attached to every data variable to indicate the spatiotemporal coordinate variables that are needed to geo-locate the data.

I think dimension coordinates are explicit enough to count as "unambiguously associated", even without inclusion in the `coordinates` attribute, since they share a name with one of the dimensions of the Discrete Sampling Geometry data variables.  This seems to be made explicit in the fourth paragraph:

> Auxiliary coordinate variables containing the nominal and the precise positions should be listed in the relevant coordinates attributes of data variables. In orthogonal representations the nominal positions could be coordinate variables, which do not need to be listed in the coordinates attribute, rather than auxiliary coordinate variables.

**Comment by tovogt** [comment]
@DWesl Thanks for digging into the details of the CF! I read your post in the sense that solution (1) is the one to choose.

I have one more question though before we close this:

When setting `"coordinates"` as a variable attribute instead of as an `encoding`, the value of that variable attribute is overwritten when writing to a NetCDF file, see this example:
```python
import xarray as xr
ds = xr.Dataset(
    {"values": ('time', [0.0, 0.1])},
    coords={
       'time': ('time', [0, 1]),
       'lat': ('time', [5, 4]),
       'lon': ('time', [10, 12])
    })
ds['values'].attrs['coordinates'] = "time lon lat"
ds.to_netcdf("test.nc")
```
```shell
$ ncdump -h test.nc
netcdf test {
dimensions:
	time = 2 ;
variables:
	double values(time) ;
		values:_FillValue = NaN ;
		values:coordinates = "lon lat" ;
	int64 time(time) ;
	int64 lat(time) ;
	int64 lon(time) ;
}
```
Is this intended, and if so, what is the reason?

**Comment by DWesl** [comment]
That could work.  Are you set up to check that?  That can be either a full repository checkout or an XArray installation you can edit.

**Comment by tovogt** [comment]
Yes, I tested this locally, and here is the PR for that suggestion: #6366
