### ISSUE TITLE
Documentation talks about Dataset, example is for DataArray

### ISSUE THREAD

**Issue by paapu88** [pydata/xarray#6336]
### What happened?

In the dev version of the documentation
https://docs.xarray.dev/en/latest/generated/xarray.Dataset.assign_coords.html

The page is about Dataset, but all the examples are for DataArray

### What did you expect to happen?

Examples should be for Dataset, not for DataArray

### Environment

https://docs.xarray.dev/en/latest/generated/xarray.Dataset.assign_coords.html

**Comment by gregbehm** [comment]
The `DataArray.assign_coords` examples appear on the `xarray.Dataset.assign_coords` [doc page](https://docs.xarray.dev/en/latest/generated/xarray.Dataset.assign_coords.html) because they're written in `/xarray/core/common.py` for the `.assign_coords` method of class `DataWithCoords`, the shared base class for `Dataset` and `DataArray`.

@andersy005 can you recommend a way to separate the `Dataset` and `DataArray` examples for methods shared by the same base class? This same problem affects other doc pages for common `Dataset`/`DataArray` methods.

Thanks, Greg

**Comment by gregbehm** [comment]
After further investigation, I think the easiest solution is to provide examples that cover both object types, `DataArray` and `Dataset`, analogous to the `pandas.DataFrame` and `pandas.Series` documentation, e.g. [pandas.DataFrame.describe](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.describe.html):

**Examples**
---
Describing a numeric `Series`.
`...`

Describing a `DataFrame`. By default only numeric fields are returned.
`...`

**Comment by max-sixty** [comment]
> After further investigation, I think the easiest solution is to provide examples that cover both object types,

I agree, this would be very reasonable. 

(For these methods that are basically the same between objects, it's nice to have at least one example for each to show that it works on each type, but otherwise it's fine to have the examples more focused on one object)
