### ISSUE TITLE
backwards incompatible changes in reductions

### ISSUE THREAD

**Issue by dcherian** [pydata/xarray#6408]
### What is your issue?

I merged #5950 but forgot that it included some backward-incompatible changes (Sorry! this came up in https://github.com/pydata/xarray/pull/6403 thanks to @mathause for spotting.)

1. Arguments like `keep_attrs`, `axis` are now keyword-only.
2. Some reductions had the 3rd position arg as `keep_attrs` and in other cases it was `axis`.

These have been standardized now, and only `dim` is accepted without kwarg-name.

@pydata/xarray Should we add a deprecation cycle (https://github.com/pydata/xarray/issues/5531)? Point (2) above will make it a little messy.

At the very least we should add a deprecation notice before releasing.

**Comment by shoyer** [comment]
I think this is probably fine without a deprecation cycle. This is a very easy fix for users.

**Comment by max-sixty** [comment]
@shoyer do you think we need a deprecation cycle for those in https://github.com/pydata/xarray/pull/6403? It would be less work if we didn't.

I was thinking that for some of them we did need a depr. cycle, but only because I've seen many cases where specific methods don't use kwargs — e.g. `.diff(dim, 2)`. WDYT?
