### ISSUE TITLE
"naive" iteration is very slow

### ISSUE THREAD

**Issue by anntzer** [pydata/xarray#643]
```
$ ipython
Python 3.5.0 (default, Sep 20 2015, 11:28:25) 
Type "copyright", "credits" or "license" for more information.

IPython 4.0.0 -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.
Using matplotlib backend: Qt4Agg

In [1]: from xray import DataArray

# Iteration over a Python list
In [2]: %%timeit t = list(range(10000))
for _ in t: pass
   ...: 
10000 loops, best of 3: 87.3 µs per loop

# Iteration over a ndarray
In [3]: %%timeit t = np.arange(10000)
for _ in t: pass
   ...: 
1000 loops, best of 3: 472 µs per loop

# Iteration over a DataArray
In [4]: %%timeit t = DataArray(np.arange(10000))
for _ in t: pass
   ...: 
1 loops, best of 3: 818 ms per loop
```

I'm not sure how much can be done about this as iterating over a DataArray needs to create a bunch of temporary objects (and I understand the emphasis is as usual on vectorized operations, etc.) but a >1500 fold difference certainly doesn't look good.

**Comment by shoyer** [comment]
A useful point of reference here is to compare xray's performance to pandas:
```
In [20]: %%timeit t = pd.DataFrame({'x': np.arange(10000)})
for _ in t.iterrows(): pass
   ....:
1 loops, best of 3: 558 ms per loop

In [21]: %%timeit t = DataArray(np.arange(10000))
for _ in t: pass
   ....:
1 loops, best of 3: 1.49 s per loop
```

So we're about 2.5-3x slower than pandas. We might be able to catch up there with some careful optimization, but I doubt we would be able to do much better.

Basically, the issue is that DataArray (like pandas's Series) is not an extension type (written in C/Cython), which means that it is much slower to construct -- iterating over it entails a lot of Python logic and a lot of memory allocation (e.g., a new dictionary for every instance).

We could imagine converting xray's core data objects to Cython extension types, but I doubt the tradeoff in easy of use would be worth it. I prefer to encourage users to use xray's easy interface to NumPy when entering into something performance critical like a loop.

**Comment by max-sixty** [comment]
Thanks for filing the original issue. Closing as stale, but please reopen if still an issue we could address
