### ISSUE TITLE
Feature request: only allow nearest-neighbor .sel for valid data (not NaN positions)

### ISSUE THREAD

**Issue by cwerner** [pydata/xarray#644]
Hi.

Maybe I'm missing something, but I'm trying to get data by providing lat & lon coordinates to the .sel operator together with the nearest argument. This works, but in my case often ocean pixels are nearby and those contain NaN. Is there a way to only return the nearest _valid_ point even if this is a bit further away then the invalid locations?

Christian

**Comment by shoyer** [comment]
This is tricky to put into `.sel` because that method currently works by only looking at coordinate labels, not at data values.

One way to fix this would be to unravel your two dimensions corresponding to latitude and longitude into a single "lat_lon" dimension. At this point, you could apply a sea mask, to produce a compressed lat_lon coordinate corresponding to only unmasked points. Now, it's relatively straightforward to imagine doing nearest neighbor lookups on this set of labels.

This later solution will require a few steps (all of which are on the "to do" list, but without any immediate timelines):
1. support for multi-level indexes in xray
2. support for "unraveling" multiple dimensions into 1-dimension
3. support for looking up nearest locations in multiple dimensions via some sort of spatial index (e.g., a KD tree)

**Comment by chrwerner** [comment]
Ah, ok, cool.

Thanks for the pointers and getting back to me. Looking forward to any future xray improvements. It’s really becoming my goto to for netcdf stuff (in addition to cdo).

Christian

**Comment by artlionel** [comment]
I am having this exact same issue. Has there been an update that would make this task straightforward using xarray capabilities?
Thanks

**Comment by shoyer** [comment]
There hasn't been any progress on this to my knowledge, unfortunately

**Comment by artlionel** [comment]
That's a bummer, but thanks for the fast reply

**Comment by albertotb** [comment]
I just want to +1 this issue since I'm having the exact same problem. It would be great if the `.sel(method="nearest")` could ignore `NaNs` as an option

**Comment by zflamig** [comment]
Just want to bump this again because I just ran into this issue too...

**Comment by davidshumway** [comment]
https://stackoverflow.com/questions/76239626/xarray-preprocess-for-nearest-lat-lon-non-nan-variable

**Comment by FiND-Tao** [comment]
Try the code below. If it finds the NaN from the results of standard sel function, then it execute find_nearest_valid.
```
def find_nearest_valid(ds, lon, lat, var, radius=1):
    """Find the nearest valid value in a dataset for a given variable and coordinates."""
    # Select a subset of points within a certain radius
    subset = ds.sel(longitude=slice(lon-radius, lon+radius), latitude=slice(lat-radius, lat+radius))
    # Calculate the Euclidean distance to the points in the subset
    dist = np.sqrt((subset.longitude - lon)**2 + (subset.latitude - lat)**2)
    # Create a new dataset that only includes valid values
    valid_subset = subset.where(~np.isnan(subset[var]), drop=True)
    # Find the coordinates of the valid point with the smallest distance
    min_dist_coords = dist.where(dist == dist.where(~np.isnan(valid_subset[var])).min(), drop=True)
    nearest_lon = min_dist_coords.longitude.values.item()
    nearest_lat = min_dist_coords.latitude.values.item()
    # Select the nearest valid value
    nearest = valid_subset.sel(longitude=nearest_lon, latitude=nearest_lat)
    return nearest[var].to_dataframe().reset_index()
    temp_series = combined_ds['t2m'].sel(longitude=lon, latitude=lat,method="nearest").to_dataframe().reset_index()
if temp_series['t2m'].isna().any():  # If temp_series contains any NaN values
    temp_series = find_nearest_valid(combined_ds, lon, lat,'t2m')  # Use find_nearest_valid to find the nearest valid value
```
