### ISSUE TITLE
BUG: not converting datetime64[ns] with tz from pandas.Series

### ISSUE THREAD

**Issue by jreback** [pydata/xarray#701]
```
In [5]: s = Series(pd.date_range('20130101',periods=3,tz='US/Eastern')) 

In [6]: s
Out[6]: 
0   2013-01-01 00:00:00-05:00
1   2013-01-02 00:00:00-05:00
2   2013-01-03 00:00:00-05:00
dtype: datetime64[ns, US/Eastern]

In [7]: xray.DataArray.from_series(s)
Out[7]: 
<xray.DataArray (index: 3)>
array(['2013-01-01T00:00:00.000000000-0500',
       '2013-01-02T00:00:00.000000000-0500',
       '2013-01-03T00:00:00.000000000-0500'], dtype='datetime64[ns]')
Coordinates:
  * index    (index) int64 0 1 2

In [8]: xray.DataArray.from_series(s).to_pandas()
Out[8]: 
index
0   2013-01-01 05:00:00
1   2013-01-02 05:00:00
2   2013-01-03 05:00:00
dtype: datetime64[ns]
```

**Comment by shoyer** [comment]
This is difficult to do properly, because xray uses numpy or dask.array to store array data, and datetime64 with a timezone is not a real numpy dtype.

I guess the right solution (similar to what I did for PeriodIndex in #692) would be to convert to dtype=object when necessary. Is there an easy way to get this from pandas?

Although, I do think it's pretty consistent that we use the result of `np.asarray(s)` as the values in xray. The timezone info is thrown away when you call this.

**Comment by jreback** [comment]
yeh, this is fine. maybe just note which dtypes are lossless and which are not. Yeah if you store things as ``Index`` objects, then this would go away.

**Comment by MaximilianR** [comment]
@jreback 
> Yeah if you store things as Index objects, then this would go away.

@shoyer remains unconvinced, and I defer to him without reservation - but if you think this would make sense, say so
