### ISSUE TITLE
release?

### ISSUE THREAD

**Issue by dcherian** [pydata/xarray#7069]
### What is your issue?

It's been 3 months since our last release.

We still have quite a few [regressions](https://github.com/pydata/xarray/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+label%3Aregression) from the last release but @benbovy does have open PRs for a number of them. However, we do have some nice bugfixes and other commits in the mean time.

I propose we issue a new release, perhaps after @benbovy merges the PRs he thinks are ready.

I'll be out of town for the next few days, so if someone else could volunteer to be release manager that would be great!

**Comment by TomNicholas** [comment]
It would be nice to be able to go back to what we were doing recently, i.e. releasing every 2 weeks (after each dev meeting). Will we be able to go back to that schedule after this release?

(I can release this next version too)

**Comment by benbovy** [comment]
#6992 and #6999 regression fixes are ready.

#6971 would be nice to include in the release. It is almost ready, we still need to decide whether to expose the `Index` public API in Xarray's root namespace or in an `indexes` subpackage. See https://github.com/pydata/xarray/pull/6971/#issuecomment-1246201402 and discussion thereafter.

**Comment by dcherian** [comment]
Looks like this is a good time to release!

@TomNicholas can you handle this one please?

**Comment by TomNicholas** [comment]
Should we wait to fix any of the other [regressions](https://github.com/pydata/xarray/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+label%3Aregression)? Or just fix them in the next release.

Are we doing any kind of announcement about indexes with this release? Or just summarise whatsnew as normal?

Also kind of unrelated (I forgot to mention this in the meeting today) but can someone please add my columbia email (thomas dot nicholas at columbia dot edu)to the xarray dev team google group/list? I think it was attached to my old institutional address which has since lapsed.

**Comment by benbovy** [comment]
I think we can go ahead with the release. The remaining regressions seem to affect only a limited number of use cases ; it could wait the following release if we we are not waiting too long between the two.

I'd also wait for an announcement about indexes. It has been already announced at the previous release, and it'd probably be better to communicate about it (maybe via a blog post?) after improving the docs and experimenting a bit more with custom indexes...
