### ISSUE TITLE
Dataset.to_netcdf() fails to interpret 'encoding' option

### ISSUE THREAD

**Issue by tkanmae** [pydata/xarray#709]
Attempting to save a dataset with compression

```python
ds.to_netcdf('demo.nc', mode='w', encoding={'data': {'zlib': True}})
```

raises an exception as follows::

```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-7-ec637fd612fd> in <module>()
----> 1 ds.to_netcdf('demo.nc', mode='w', encoding={'data': {'zlib': True}})

/Users/takeshi/Developer/xray/xray/core/dataset.py in to_netcdf(self, path, mode, format, group, engine, encoding)
    782         from ..backends.api import to_netcdf
    783         return to_netcdf(self, path, mode, format=format, group=group,
--> 784                          engine=engine, encoding=encoding)
    785 
    786     dump = utils.function_alias(to_netcdf, 'dump')

/Users/takeshi/Developer/xray/xray/backends/api.py in to_netcdf(dataset, path, mode, format, group, engine, writer, encoding)
    352     store = store_cls(path, mode, format, group, writer)
    353     try:
--> 354         dataset.dump_to_store(store, sync=sync, encoding=encoding)
    355         if isinstance(path, BytesIO):
    356             return path.getvalue()

/Users/takeshi/Developer/xray/xray/core/dataset.py in dump_to_store(self, store, encoder, sync, encoding)
    728             variables, attrs = encoder(variables, attrs)
    729 
--> 730         store.store(variables, attrs, check_encoding)
    731         if sync:
    732             store.sync()

/Users/takeshi/Developer/xray/xray/backends/common.py in store(self, variables, attributes, check_encoding_set)
    226         cf_variables, cf_attrs = cf_encoder(variables, attributes)
    227         AbstractWritableDataStore.store(self, cf_variables, cf_attrs,
--> 228                                         check_encoding_set)

/Users/takeshi/Developer/xray/xray/backends/common.py in store(self, variables, attributes, check_encoding_set)
    201                                 if not (k in neccesary_dims and
    202                                         is_trivial_index(v)))
--> 203         self.set_variables(variables, check_encoding_set)
    204 
    205     def set_attributes(self, attributes):

/Users/takeshi/Developer/xray/xray/backends/common.py in set_variables(self, variables, check_encoding_set)
    211             name = _encode_variable_name(vn)
    212             check = vn in check_encoding_set
--> 213             target, source = self.prepare_variable(name, v, check)
    214             self.writer.add(source, target)
    215 

/Users/takeshi/Developer/xray/xray/backends/netCDF4_.py in prepare_variable(self, name, variable, check_encoding)
    259 
    260         encoding = _extract_nc4_encoding(variable,
--> 261                                          raise_on_invalid=check_encoding)
    262         nc4_var = self.ds.createVariable(
    263             varname=name,

/Users/takeshi/Developer/xray/xray/backends/netCDF4_.py in _extract_nc4_encoding(variable, raise_on_invalid, lsd_okay, backend)
    160         if invalid:
    161             raise ValueError('unexpected encoding parameters for %r backend: '
--> 162                              ' %r' % (backend, invalid))
    163     else:
    164         for k in list(encoding):

ValueError: unexpected encoding parameters for 'netCDF4' backend:  ['z', 'l', 'i', 'b']
```

**Comment by tkanmae** [comment]
This issue is relevant to #682.

**Comment by slharris** [comment]
I am receiving the same error as #709 when trying:

ds.to_netcdf( 'myncfile.nc', encoding={'Temp': {'dtype': 'float'}})

and I am using xray v 0.6.1  - which is the version the 'what's new' changes appear under.

Do I need a different version? am I writing it incorrectly?

**Comment by slharris** [comment]
please ignore the last comment/issue
as soon as I added 'float32' rather than just 'float' it worked fine!

**Comment by avatar101** [comment]
I'm facing the same problem of the unexpected encoding parameter 

`big_ds.to_netcdf(out_dir + 'V250hov_N2000_2018_v4'  + '.nc', encoding={'V':{'_FillValue': -999.0}, 'time':{'units': "seconds since 1970-01-01 00:00:00"}})
`
The error is as follows:
`  File "./R_metric.py", line 61, in <module>
    big_ds.to_netcdf(out_dir + 'V250hov_N2000_2018_v4'  + '.nc',encoding={'V':{'_FillValue': -999.0}, 'time':{'units': "seconds since 1970-01-01 00:00:00"}})
  File "/usr/local/anaconda3/envs/work_env/lib/python3.6/site-packages/xarray/core/dataset.py", line 1222, in to_netcdf
    compute=compute)
  File "/usr/local/anaconda3/envs/work_env/lib/python3.6/site-packages/xarray/backends/api.py", line 718, in to_netcdf
    unlimited_dims=unlimited_dims)
  File "/usr/local/anaconda3/envs/work_env/lib/python3.6/site-packages/xarray/backends/api.py", line 761, in dump_to_store
    unlimited_dims=unlimited_dims)
  File "/usr/local/anaconda3/envs/work_env/lib/python3.6/site-packages/xarray/backends/common.py", line 266, in store
    unlimited_dims=unlimited_dims)
  File "/usr/local/anaconda3/envs/work_env/lib/python3.6/site-packages/xarray/backends/common.py", line 304, in set_variables
    name, v, check, unlimited_dims=unlimited_dims)
  File "/usr/local/anaconda3/envs/work_env/lib/python3.6/site-packages/xarray/backends/netCDF4_.py", line 450, in prepare_variable
    unlimited_dims=unlimited_dims)
  File "/usr/local/anaconda3/envs/work_env/lib/python3.6/site-packages/xarray/backends/netCDF4_.py", line 225, in _extract_nc4_variable_encoding
    ' %r' % (backend, invalid))
ValueError: unexpected encoding parameters for 'netCDF4' backend:  ['units']
`

However, the same syntax works when I tried writing out a different file. I'm using xarray version 11.0

**Comment by shoyer** [comment]
@avatar101 could you please open a separate issue for this? Please share what your dataset looks like as well.

**Comment by avatar101** [comment]
@shoyer Sure, I found a way around by using cdo but I can revisit it and provide more details
