### ISSUE TITLE
`to_netCDF` provides a `netcdf` that does not import correctly in QGIS

### ISSUE THREAD

**Issue by leomiquelutti** [pydata/xarray#7195]
### What is your issue?

I did some geospatial data processing and now I am trying to export my resulting `xarray.Dataset` to a `netCDF` file that works in QGIS with no success with `to_netcdf` (gray image in the map below). However, it works properly when I export it with `to_raster` (image inside the smaller yellow rectangle - the correct place).

![image](https://user-images.githubusercontent.com/9113903/197359251-89497617-0816-43c0-b9d7-5b45fa703144.png)

A Minimal Complete Verifiable Example can be found in [this Google Colab](https://colab.research.google.com/drive/1T0UWeKP2Ydt7lh77nJ0DNUSsoecPtbh8?usp=sharing).

I am using QGIS version 3.26.3.

Does anyone know how to solve this? I am working with dozens of layers, so a `netcdf` file is way better for me that several `tif` files.

**Comment by scottyhq** [comment]
@leomiquelutti I wasn't able to reproduce this (ran your colab notebook and opened the netcdf in qgis 3.26). It's possible for versions to change between your colab executions so I recommend using `rioxarray.show_versions()` Since you are using rioxarray to write the CRS, I'd also recommend opening this issue or discussion over in https://github.com/corteva/rioxarray

<img width="705" alt="Screen Shot 2022-10-24 at 11 54 28 AM" src="https://user-images.githubusercontent.com/3924836/197605366-d2571cf0-9823-4920-956d-42d0e87476c6.png">

**Comment by leomiquelutti** [comment]
Hi @scottyhq thank you very much for trying! I already opened a new issue in the [GIS community](https://gis.stackexchange.com/questions/443574/rioxarray-to-netcdf-provides-a-netcdf-file-that-does-not-import-correctly-into) with the `rioxarray` tag. I will also open an issue in https://github.com/corteva/rioxarray.

I also ran that Colab several times, and in NONE of them the `netcdf` went in the right place. Could be anything else, like my `GDAL` version being diferent of yours?
