### ISSUE TITLE
Using open_mfdataset the size of the final data becomes huge

### ISSUE THREAD

**Issue by mariasanur** [pydata/xarray#7274]
### What is your issue?

Hi, 

I've been struggling with open_mfdataset because of the size of the combined final data. I have 365 files whose size in the folder was 2.2 Gb aprox., but when I open them with open_mfdataset the size becomes 11 Gb. Is there a way to avoid it? 

<img width="267" alt="image" src="https://user-images.githubusercontent.com/89445148/200779136-3c888ab3-e959-4006-a486-c3268e71a82f.png">

<img width="568" alt="image" src="https://user-images.githubusercontent.com/89445148/200778737-54fd6434-c018-438a-86f9-a8424df889b8.png">

**Comment by kmuehlbauer** [comment]
That might be due to compression of the source file. Just have a look into `.encoding`, if If there is some mention of compression.

`dset_year.analysed_sst.encoding`

No, there is nothing you can do about. But as in your example `open_mfdataset` wraps the data on disk using `dask`. That way the data isn't read into memory. It will be read into memory in chunks once processed. In your case one chunk is 32MB. Depending on your algorithms `dask` will take care to not load complete dataset into memory but process chunk-wise. 

Please also have a look at xarray and dask here: https://docs.xarray.dev/en/stable/user-guide/dask.html.

**Comment by mariasanur** [comment]
Thank you so much for your help. I've just started using xarray for large data. There was indeed a compression level. 

<img width="567" alt="image" src="https://user-images.githubusercontent.com/89445148/200797443-16b3b65b-94a5-4223-8ec6-b527abcb0ab8.png">
