### ISSUE TITLE
Doctests failing

### ISSUE THREAD

**Issue by headtr1ck** [pydata/xarray#7322]
### What is your issue?

It seems that some update in urllib3 causes our doctests to fail.

The reason seems to be that botocore uses an interesting construction to import deprecated urllib3 things:
```python
try:
    # pyopenssl will be removed in urllib3 2.0, we'll fall back to ssl_ at that point.
    # This can be removed once our urllib3 floor is raised to >= 2.0.
    with warnings.catch_warnings():
        warnings.simplefilter("ignore", category=DeprecationWarning)
        # Always import the original SSLContext, even if it has been patched
        from urllib3.contrib.pyopenssl import (
            orig_util_SSLContext as SSLContext,
        )
except ImportError:
    from urllib3.util.ssl_ import 
```

I assume that this fails because we use `-Werror` which translates the warning into an error which then is not ignored...

Not sure if this is an issue with botocore or we have to catch this?

**Comment by headtr1ck** [comment]
I guess we could ask botocore to add the `DeprecationWarning` to the except?

**Comment by keewis** [comment]
When investigating this yesterday (sorry for not posting earlier), I concluded that the reason is that we somehow install a  older version of `botocore`: the `doctest` environment lists `1.27.59`, the most recent version with the ignore is `1.29.16` (`botocore` has a very high release frequency, the version we're installing is from August). We could try to add a module specific warning filter, which I think is fine because as far as I can tell `botocore` is a indirect dependency.

**Comment by headtr1ck** [comment]
It seems that botocore is not directly the cause of the warning, it is urllib3. But botocore only silences the warning which does not work with `-Werror`.
So we probably have to either restrict to an older version of urllib3 or filter this warning/error specifically.

**Comment by mathause** [comment]
aiobotocore pins botocore as the versions must match (see aio-libs/aiobotocore#983). I opened #7322 to suppress the warning in our tests.
