### ISSUE TITLE
reindex_like with tolerance changes the type of returned DataArray 

### ISSUE THREAD

**Issue by oceanEngineer** [pydata/xarray#738]
I am really excited about all of the new changes to xarray! reindexing with tolerance has great potential to clean up some sort of nasty stuff that I use a lot but have tucked away into a corner of my code. I am not sure I am 100% comfortable with it at the moment, however, because it seems to be changing the types of my data in unexpected ways.

Bei:

```
test = xr.DataArray([1,2,3], coords=[[0.1, 0.2, 0.3]])
test_i = xr.DataArray([5,6,7,8], coords=[[0.21, 0.31, 0.41, 0.51]])

test.dtype
test.reindex_like(test_i, method='pad', tolerance=0.2).dtype
```

the reindexed output has changed from int64 to float64!

Even more concerning is the complex example:

```
test = xr.DataArray(np.array([1,2,3], dtype=np.complex), coords=[[0.1, 0.2, 0.3]])

test.dtype
test.reindex_like(test_i, method='pad', tolerance=0.2).dtype
```

Conversion from complex to object? Oh no. 

Hope this isn't anything too big, let me know if I can help.
Thank

**Comment by shoyer** [comment]
Unfortunately, NumPy has no integer type that can support missing values. This leaves us in a difficult situation for integer types. So, we've copied the approach from pandas of upcasting integers to floats when we need to add NaNs:
http://pandas.pydata.org/pandas-docs/stable/gotchas.html#nan-integer-na-values-and-na-type-promotions
http://xarray.pydata.org/en/stable/computation.html#missing-values (this could use a reference to the aforementioned pandas docs)

Conversion from complex to object is certainly not what we want, though, because NaN is a perfectly valid complex number. A fix to `_maybe_promote` *should* take care of that:
https://github.com/pydata/xarray/blob/v0.7.0/xarray/core/common.py#L412

A contribution here would definitely be appreciated! We have made some improvements to complex number support recently but it definitely gets less use.
