### ISSUE TITLE
Numerical operations with empty DataArrays fail

### ISSUE THREAD

**Issue by MaximilianR** [pydata/xarray#739]
We're running into this a fair amount at the moment, and so constantly having to check whether DataArrays are empty before multiplying them together:

```python
In [6]: a=xr.DataArray([[]])

In [7]: b=xr.DataArray([[1,2,3]])

In [8]: a*b
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-8-8201c27d19b7> in <module>()
----> 1 a*b

/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/xarray/core/dataarray.py in func(self, other)
   1182                 if empty_indexes:
   1183                     raise ValueError('no overlapping labels for some '
-> 1184                                      'dimensions: %s' % empty_indexes)
   1185             other_variable = getattr(other, 'variable', other)
   1186             other_coords = getattr(other, 'coords', None)

ValueError: no overlapping labels for some dimensions: ['dim_1']

```

Is the failure a useful one? If it's taking an inner join, isn't it OK to return an empty result if there are no matching labels?

FWIW Pandas & Numpy both allow this:

```python
In [12]: pd.Series()*pd.Series()
Out[12]: Series([], dtype: float64)

In [13]: pd.DataFrame()*pd.DataFrame()
Out[13]: 
Empty DataFrame
Columns: []
Index: []

In [16]: np.asarray([])*np.asarray([])
Out[16]: array([], dtype=float64)
```

**Comment by shoyer** [comment]
I would be OK with changing this. This would be pretty straightforward and almost entirely backwards compatible.

My original thought was that was that raising an error would more immediately identify cases where the user didn't have compatible coordinates to both arrays, because in many (most?) cases this does indicate an error in the original code. Given that concern, we might consider switching the error to only occur if both of the original dimensions were *not* size 0. On the other hand, making things more complex is usually not the solution :).
