### ISSUE TITLE
Add clarifying language to contributor's guide

### ISSUE THREAD

**Issue by paigem** [pydata/xarray#7439]
### What is your issue?

I am going through the [contributor's guide](https://docs.xarray.dev/en/stable/contributing.html#creating-a-development-environment) for `xarray`, and I have a few suggested updates to make the instructions clearer to relatively new contributors like me!

## General questions
- If making updates to docstrings, I am unclear if I should use the virtual env `xarray-tests` or `xarray-docs`. I assumed I should use `xarray-docs` since I am only updating docstrings which are fed into the documentation. But this isn't entirely clear, since the file I updated is not in the `\docs` folder, but is at `\xarray\backends\api.rst`.
- If only updating docs or docstrings, should I still run pytest locally before pushing? Or do those tests only apply to code updates? Either way, this should be made clear in the contributing guide.

## Suggestion updates
- Under [Code Formatting](https://docs.xarray.dev/en/stable/contributing.html#code-formatting):
  - Contributors are recommended to use `pre-commit` via `pre-commit install`, but when I tried this I found that `pre-commit` was not installed in the virtual env `xarray-docs`. It does appear to be installed in virtual env `xarray-tests` ([yml file](https://github.com/pydata/xarray/blob/b589f6b82968857dbfc9a4dfdb4c09dbcb5aeb44/ci/requirements/environment.yml)). Should I run pre-commit when updating docs? If so, we should add pre-commit to virtual env `xarray-docs` ([yml file](https://github.com/pydata/xarray/blob/b589f6b82968857dbfc9a4dfdb4c09dbcb5aeb44/ci/requirements/doc.yml)).
- Under [Building the Documentation](https://docs.xarray.dev/en/stable/contributing.html#building-the-documentation):
  - Add a sentence to make it clear that users can preview the html files from their updated documentation in their local browsers to verify it looks as expected. (This is a minor suggestion, but we might as well be as explicit as possible, especially since docs might more likely be updated by newer contributors.)
  - Suggested wording update: "Then you can find the HTML output in the folder xarray/doc/_build/html/. **You can preview the html files in your local browser to verify that you see expected behavior based on your changes.**"

**Comment by paigem** [comment]
One more comment (now that my docstring PR went through): 
- We should include something like the following under the section [Finally, make the pull request ](https://docs.xarray.dev/en/stable/contributing.html#finally-make-the-pull-request):
  - "If you have made updates to the documentation, you can see a preview of the updated docs by clicking on "Details" under the `docs/readthedocs.org` check near the bottom of the list of checks that run automatically when submitting a PR."

**Comment by Illviljan** [comment]
I've found this part of the documentation a bit scary in the past because there is so much stuff to do for a simple "typo fix" so I welcome changes here!

Nowadays, since the CI runs [pytest](https://github.com/pydata/xarray/actions/runs/3914705703/jobs/6692077250), [pre-commit](https://github.com/pydata/xarray/pull/7438/commits/93cd752fe58b8cd7047b15bb217e2ebbcb7a6d38) and [builds the documentation](https://xray--7438.org.readthedocs.build/en/7438/) on every PR it isn't really necessary for new contributors to get it to run locally. The only thing left is setting up a new branch with git and creating a PR. 
Setting up git can also be scary for new users but then there is [github desktop](https://desktop.github.com/) which hides away all of that in a quite user friendly GUI.

Sure, if you're doing bigger changes running the specific tests locally is probably faster but at that point you're probably a more experienced contributor anyway.

**Comment by TomNicholas** [comment]
Thanks for these comment @paigem! It's useful to hear things that might not occur to us.

Good points @Illviljan. Perhaps we should restructure to make it clear that running tests / pre-commit locally is optional, but still show people how to do it?
