### ISSUE TITLE
plotting facet grid with singleton dimension should create a facet grid with size 1

### ISSUE THREAD

**Issue by liorella-qm** [pydata/xarray#7552]
### What is your issue?

In my application, I want to plot facet grids of datasets, and the dimension I want to facet sometimes has a length of 1 and sometimes more than 1. When the length of the dimension is > 1, the `plot(col=....)` method of `DataArray` works as expected. However, when it is 1, I get an error and my code fails, although it would have been natrual for the plot method to create a `FacetGrid` with length of one facet.

As a minimal example, this code:
```python
import xarray as xr
da = xr.DataArray(np.random.rand(3,1), dims=('x', 'y'))
da.plot(col='y')
```
fails with an error:
```python
KeyError: 'y'
```
 This example works as expected:

```python
import xarray as xr
da = xr.DataArray(np.random.rand(3,2), dims=('x', 'y'))
da.plot(col='y')
```

**Comment by headtr1ck** [comment]
This is caused by the `squeeze()` here: https://github.com/pydata/xarray/blob/41949209b6cfb0d5c25d000b1e0c5739b513385c/xarray/plot/dataarray_plot.py#L267

@Illviljan do you know why this is required? I assume you want to remove singleton dimensions to better choose the correct plot method?

Maybe we should exclude col, row dims from the squeeze?

**Comment by headtr1ck** [comment]
@liorella-qm in the meantime you can use `da.plot.line(col='y')` as a workaround

**Comment by dcherian** [comment]
See  #620 (!)

> Maybe we should exclude col, row dims from the squeeze?

This seems sensible.

**Comment by akanshajais** [comment]
The reason why you are getting a KeyError in your first example when trying to plot with col='y' is because when y is a dimension with length 1, xarray automatically drops the dimension and promotes its coordinates to 1D.

In your example, the y dimension has length 1, so it is dropped, and da.coords['y'] returns a scalar value rather than a 1D coordinate array. When you try to plot with col='y', xarray looks for the 'y' key in the coordinates dictionary, which doesn't exist, hence the KeyError.

To work around this, you can manually promote the y coordinate to a 1D array using the expand_dims method:

```
import xarray as xr
import numpy as np

da = xr.DataArray(np.random.rand(3,1), dims=('x', 'y'))
da.coords['y'] = da.coords['y'].expand_dims('y')
da.plot(col='y')

```
This will ensure that the y coordinate is always a 1D array, even when the dimension it represents has length 1.

**Comment by wkrasnicki** [comment]
Since I didn't see anyone objecting to the solution provided by @headtr1ck and I also found this behaviour annoying, I hope that nobody minds that I created a PR with it.
