### ISSUE TITLE
illustrate time offset arithmetic

### ISSUE THREAD

**Issue by dcherian** [pydata/xarray#7596]
### Is your feature request related to a problem?

We should document changing the time vector using pandas date offsets [here](https://docs.xarray.dev/en/stable/user-guide/time-series.html#time-series-data)

This is particularly useful for centering the time stamps after a resampling operation.

Related: 
- CFTime offsets: https://github.com/pydata/xarray/issues/5687
- `loffset` deprecation: https://github.com/pydata/xarray/pull/7444

**Comment by Karimat22** [comment]
Time offset arithmetic involves adding or subtracting a duration from a specific time to obtain a new time. This is commonly used when dealing with time zones or calculating time differences between two events.

For example, suppose the current time is 3:30 PM in New York City, which is in the Eastern Time Zone (ET). We want to calculate what time it is in Los Angeles, which is in the Pacific Time Zone (PT), considering the 3-hour time difference between the two zones.

To do this, we can use time offset arithmetic by subtracting 3 hours from the current time in ET:

3:30 PM ET - 3 hours = 12:30 PM PT

Therefore, the current time in Los Angeles is 12:30 PM.

Another example of time offset arithmetic is when calculating the duration between two events. Suppose an event starts at 9:00 AM and ends at 10:30 AM. We can calculate the duration of the event by subtracting the start time from the end time:

10:30 AM - 9:00 AM = 1 hour 30 minutes

Therefore, the event lasted for 1 hour and 30 minutes.

**Comment by cyschneck** [comment]
Will the time offset arithmetic involve the use of pandas offset function? A potential solution from [Issue 4535](https://github.com/pydata/xarray/issues/4535#issuecomment-716066118) uses `from pandas.tseries.frequencies import to_offset`

I'd find an example helpful since I am attempting to [convert an existing function](https://github.com/NCAR/geocat-comp/blob/b28031f922b09244087451d965905b27c2d5d06d/geocat/comp/climatologies.py#L305) from `loffset` to the time offset arithmetic for MonthBegin ("MS")
