### ISSUE TITLE
xarray minimum versions policy is more aggressive than NEP-29

### ISSUE THREAD

**Issue by crusaderky** [pydata/xarray#7777]
### What is your issue?

In #4179 / #4907, the xarray policy around minimum supported version of dependencies was changed, with the reasoning that the previous policy (based on [NEP-29](https://numpy.org/neps/nep-0029-deprecation_policy.html)) was too aggressive.
Ironically, this caused xarray to drop Python 3.8 on Jan 26th (#7461), 3 months *before* what NEP-29 recommends (Apr 14th).
This is hard to defend - and in fact it sparked discontent (see late comments in #7461).

Regardless of what policy xarray decides to use internally, it should never be more aggressive than NEP-29.
[The xarray documentation](https://docs.xarray.dev/en/stable/getting-started-guide/installing.html#minimum-dependency-versions) is also incorrect, as it states "Python: 24 months ([NEP-29](https://numpy.org/neps/nep-0029-deprecation_policy.html))" which is not, in fact, in NEP-29.

**Comment by keewis** [comment]
see also #7765, where there is a bit more information and discussion about this. In short, the policy did work *like* NEP-29 before, but stopped doing so with python 3.8 because python switched from a irregular ~18 month release cycle to a regular 12 month cycle. We can adjust our policy by extending these 24 months to 30 months, which makes us align with NEP-29's 42 months window.
