### ISSUE TITLE
almost-equal grids

### ISSUE THREAD

**Issue by mathause** [pydata/xarray#784]
Sometimes it happens that you have two grids that are equal up to precision or "for practical purposes". xarray does not align them. Is there a possibility to still get them aligned (and not having to copy the coordinates from one to the other)? 

Examples:
- CESM output from the land model and the atmosphere model.
- I have a file with a region definition on a fine grid. If I regrid that to the model resolution with cdo the grids are equal up to `~1*10**-4`.

**Comment by darothen** [comment]
Hi @mathause, I actually just ran into a very similar problem to your second bullet point. I had some limited success by manually re-building the re-gridded dataset onto the CESM coordinate system, swapping out the not-exactly-but-actually-close-enough coordinates for the CESM reference data's coordinates. In my case, I was re-gridding with CDO, but even when I explicitly pull out the CESM grid definition it wouldn't match precisely.

Since there was a lot of boilerplate code to do this in xarray (although I had a lot of success defining a callback to pass in with open_dataset), it was far easier just to use NCO to copy the correct coordinate variables into the re-gridded data.

**Comment by shoyer** [comment]
This doesn't work *automatically*, but you can use the `method='nearest'` and the `tolerance` argument with `.reindex` or `.reindex_like` to align two datasets with different grids, i.e.,
```
second = first.reindex_like(second, method='nearest', tolerance=0.001)
```

It would be nice for this to be able to work automatically, but the challenge is picking a heuristic that does not violate the principle of least surprise. A proposed a few ideas in a related issue in pandas (https://github.com/pydata/pandas/issues/9817#issuecomment-115465360).

**Comment by ocefpaf** [comment]
> `second = first.reindex_like(second, method='nearest', tolerance=0.001)`

I really like this.  Explicit and self-documenting code. I would avoid making this automatic.

**Comment by mathause** [comment]
That sounds good. Do you need both, `method`and `tolerance`?

What I do at the moment is probably not as elegant:

        ds.coords['lat'] = np.round(ds['lat'], 4)
        ds.coords['lon'] = np.round(ds['lon'], 4)

**Comment by darothen** [comment]
The `reindex_like()` approach works super well in my case. Since only my latitudes are screwed up (and they're spaced by a tad more than a degree), a low tolerance 1e-2-1e-3 worked perfectly.

**Comment by jhamman** [comment]
@mathause - any reason to keep this open or did we sort this out?
