### ISSUE TITLE
Composite coordinate plot only works in one orientation

### ISSUE THREAD

**Issue by jamesp** [pydata/xarray#788]
When I create a composite coordinate i.e. `d.coords['c'] = d.a * d.b` and then try and plot a 2d plot of the data, it only works when the composite index is on the y axis.  When on the x-axis it fails with 

`TypeError: Dimensions of C (3, 5) are incompatible with X (4) and/or Y (6)`

ipynb notebook (and pdf version of same notebook) attached that recreate the error

[xarray composite coord plot.pdf](https://github.com/pydata/xarray/files/167044/xarray.composite.coord.plot.pdf)
[xarray composite coord plot.ipynb.zip](https://github.com/pydata/xarray/files/167045/xarray.composite.coord.plot.ipynb.zip)

**Comment by fmaussion** [comment]
Just out of curiosity, what is the use case here? In your example the coordinate `rtime` has a shape `(time: 3, r: 3)` ant it is not linked to any dimension of the variable that you are plotting. What do you expect the plot to do?

**Comment by jamesp** [comment]
my use case is that `rtime` is kind of like normalised time. `rtime` is implicitly linked to temperature via `time` and `r`, no?

I'm running many simulations with varying rotation period `r`.  `time` is just clock time in seconds; what I want to plot is time in terms of revolutions i.e. time/r.

It works just fine with `rtime` along the y-axis, but I would like it along the x and there it fails as the length of the coordinate seems to have changed.

**Comment by fmaussion** [comment]
I'm not an xarray developer so use my answer with caution, but: 

> my use case is that rtime is kind of like normalised time. rtime is implicitly linked to temperature via > time and r, no?

It is not "linked" in the sense that this new coordinate has no special meaning for indexing and plotting methods (they don't have the `*`, as explained in the [documentation](http://xarray.pydata.org/en/stable/data-structures.html#coordinates)). 

> It works just fine with rtime along the y-axis, but I would like it along the x and there it fails as the 
> length of the coordinate seems to have changed.

It works, but by "chance". The variable you are plotting has dimensions `(time: 3, x: 5)`. If you stick with the original dimensions, xarray will now what to do, i.e.: `.plot(x='time', y='x')` will make a plot rotated by 90°.

When you do `.plot(x='x', y='rtime')`, xarray doesn't know which dimension is meant by `rtime` and falls back to the default behavior, which is to plot the first dimension along the y axis. However, it does use your provided coordinates to scale the axis (this works because `time` and `rtime` share one dimension length). 

When you do `.plot(x='rtime', y='x')`, xarray still doesn't know what dimension `rtime` is and probably falls back to the default behavior too.

Does the following do what you want?
```
import xarray
import numpy as np

# create a random set of data
temp = np.random.randn(3, 5, 5,3)

dat = xarray.Dataset({
        'temperature': (['time', 'x', 'y', 'r'], temp)
        },
        coords={'x': [1,2,3,4,5],
                'y': [1,2,3,4,5],
                'time': [1,2,3],
                'r': [3,4,5]})

# Transform the coordinates
dat.coords['time'].values = dat.time.values / dat.r.values

# this works fine
dat.temperature.sel(r=4).mean('y').plot(x='time', y='x')
```

**Comment by fmaussion** [comment]
Aha, I think I just got it. I deleted my previous answer, as I don't know how to answer your question
 :flushed:

**Comment by fmaussion** [comment]
I guess that what you are asking is that `xarray` should infer from y='x' that the other dimension *must* be time, and then scale with your new `rtime` coordinates?

**Comment by jamesp** [comment]
yes, in some sense, but it doesn't need to infer.  I'm explicitly telling the plot command I want to use 'x' and 'rtime' as the axial coordiates in both examples in my notebook.

It does the right thing when y=rtime; it gives an error when x=rtime.

**Comment by fmaussion** [comment]
I think that the first case works by chance, since the data dimensions are still 'time', 'x'. But this workaround should work:

```python
dat.temperature.sel(r=2).mean('y').T.plot(x='rtime', y='x')
```
(note the transpose)

**Comment by jamesp** [comment]
That works, thanks.  You say that it only worked by chance, is there a "proper" xarray-way that I should be doing this?

**Comment by shoyer** [comment]
Honestly I'm a little surprised this doesn't error: `dat.temperature.sel(r=2).mean(’y’).plot(x=’x’, y=’rtime’)`. The plot from your PDF doesn't seem to have the right y labels (rtime ranges from 0 to 2, but the highest label on the plot is 1).

What would you expect these plots to look like? Can you do this in pure matplotlib instead of xarray plotting? I would guess the result you're looking for may be possible but it's not immediately obvious to me what plot *should* result from this code.

**Comment by jamesp** [comment]
I think the axes on the pdf are wrong as I used integers in the coordinate definition and Python 2 to generate the example. Redefining time as [1.0, 2,0, 3.0] gives a better plot. I should have done this in my example, sorry about that.

I can do this in matplotlib and will do so, I guess I was little surprised that (a) it worked at all, and (b) it only worked in one orientation. 

I would expect the plots to look exactly like time vs. x, except the time axis is normalised by 'r'. 

My hope was that this would work, so I could do something like:

temp.plot(x='rtime', y='x', col='r')

and get an array of plots, each with their own timescales along the x-axis. For my analysis, time is seconds is not really that interesting, it's how it maps to the rotation timescale that matters.

I realise this is probably not a normal use case, so thanks to both of you for taking the time to reply to my question!

**Comment by shoyer** [comment]
To be clear, by "Can you do this in pure matplotlib instead of xarray plotting?", I meant could you please demonstrate that here so I can understand exactly what you were hoping to see? Bug reports that show what you expect are more useful than those that only show what went wrong :).

**Comment by fmaussion** [comment]
the question (I guess) is: is it legal in xarray to use a non-linked coordinate name as argument for a plot? For example @jamesp wants to plot the following DataArray:

```python
<xarray.DataArray 'temperature' (time: 3, x: 5)>
...
Coordinates:
  * x        (x) int64 1 2 3 4 5
  * time     (time) int64 1 2 3
    r        int64 2
    rtime    (time) float64 0.5 1.0 1.5
```
By doing:

```python
.plot(x='x', y='rtime');
```
instead of the more conventional:

```python
.plot(x='x', y='time');
```

The dimension is still `time` but the coordinates of the plot (for the axis) is `rtime`. It works if you don't change the order of the dims, but it does not work if you do (hence the transpose in my workaround).

**Comment by fmaussion** [comment]
Here is a mwe:

```python
%matplotlib inline
import xarray as xr
import numpy as np

temp = xr.DataArray(np.random.randn(3, 5), 
                    dims=['time', 'x'], 
                    coords={'x': [1,2,3,4,5], 
                            'time': [1,2,3]})
temp.coords['rtime'] = temp.time + 3

# for some reason this works
temp.plot(x='x', y='rtime');

# this does not
temp.plot(x='rtime', y='x');

# and this works again
temp.T.plot(x='rtime', y='x');
```

**Comment by shoyer** [comment]
Thanks @fmaussion for that example.

I would tentatively call this is a bug. At the very least, I don't think there's a good reason why this *shouldn't* work.

I think we need a slightly more robust solution to these lines:
https://github.com/pydata/xarray/blob/v0.7.1/xarray/plot/plot.py#L380-L382

For example, it might be a better idea to look at `darray[xlab].dims` rather than `xlab` itself. Any interest in putting together a PR?

**Comment by fmaussion** [comment]
Hi @shoyer , here's an attempt: https://github.com/pydata/xarray/pull/794

**Comment by jamesp** [comment]
Fantastic, thanks both.  Hoping next time I can contribute a fix as well as an issue ticket!
