### ISSUE TITLE
`plot.scatter(hue_style="discrete")` does nothing

### ISSUE THREAD

**Issue by mgunyho** [pydata/xarray#7907]
### What happened?

I was trying to do a scatterplot of my data with one dimension determining the color. The dimension has only a few values so I used `hue_style="discrete"` to have a different color for each value. However, the resulting scatterplot has a continuous colorbar, which is the same as when I pass `hue_style="continuous"`:

![image](https://github.com/pydata/xarray/assets/20118130/5767e8ba-4635-463f-9f4b-b405b72a3597)

### What did you expect to happen?

The colorbar should have discrete colors. I was also expecting the colors to be from the default matplotlib color palette, C0, C1, etc, when there's less than 10 items, like this:

![image](https://github.com/pydata/xarray/assets/20118130/7cd2978e-2556-4aee-86cf-f4a5f3647ed1)

Although the [examples in the documentation](https://docs.xarray.dev/en/stable/user-guide/plotting.html#scatter) show the discrete case also using viridis.

What I was *really* expecting is a plot like one would get by passing `add_colorbar=False, add_legend=True`:

![image](https://github.com/pydata/xarray/assets/20118130/f0bef900-d701-4817-bff9-514b668172d8)

But that may be a bit too automagical.

### Minimal Complete Verifiable Example

```Python
import matplotlib.pyplot as plt
import numpy as np
import xarray as xr

x = xr.DataArray(
    np.random.default_rng().random((10, 3)),
    coords=[
        ("idx", np.linspace(0, 1, 10)),
        ("color", [1, 2, 3]),
    ]
)
y = x + np.random.default_rng().random(x.shape)

ds = xr.Dataset({
   "x": x,
   "y": y,
})

# the output is the same regardless of hue_style="discrete" or "continuous" or just leaving it out
ds.plot.scatter(x="x", y="y", hue="color", hue_style="discrete", ax=plt.figure().gca())
```

### MVCE confirmation

- [X] Minimal example — the example is as focused as reasonably possible to demonstrate the underlying issue in xarray.
- [X] Complete example — the example is self-contained, including all data and the text of any traceback.
- [X] Verifiable example — the example copy & pastes into an IPython prompt or [Binder notebook](https://mybinder.org/v2/gh/pydata/xarray/main?urlpath=lab/tree/doc/examples/blank_template.ipynb), returning the result.
- [X] New issue — a search of GitHub Issues suggests this is not a duplicate.

### Anything else we need to know?

This is the code for the "expected" plot:
```python
from matplotlib.colors import ListedColormap

ds.plot.scatter(
    x="x",
    y="y",
    hue="color",
    hue_style="discrete",
    ax=plt.figure().gca(),

    # these lines added in addition to the MVCE
    cmap=ListedColormap(["C0", "C1", "C2"]),
    vmin=0.5, vmax=3.5,
    cbar_kwargs=dict(ticks=ds.color.data),
)
```

### Environment

<details>

INSTALLED VERSIONS
------------------
commit: None
python: 3.8.10 (default, May 26 2023, 14:05:08) 
[GCC 9.4.0]
python-bits: 64
OS: Linux
OS-release: 5.14.0-1059-oem
machine: x86_64
processor: x86_64
byteorder: little
LC_ALL: None
LANG: en_US.UTF-8
LOCALE: ('en_US', 'UTF-8')
libhdf5: None
libnetcdf: None

xarray: 2023.1.0
pandas: 1.4.3
numpy: 1.23.0
scipy: None
netCDF4: None
pydap: None
h5netcdf: None
h5py: None
Nio: None
zarr: None
cftime: None
nc_time_axis: None
PseudoNetCDF: None
rasterio: None
cfgrib: None
iris: None
bottleneck: None
dask: None
distributed: None
matplotlib: 3.5.3
cartopy: None
seaborn: None
numbagg: None
fsspec: None
cupy: None
pint: None
sparse: None
flox: None
numpy_groupies: None
setuptools: 44.0.0
pip: 20.0.2
conda: None
pytest: None
mypy: None
IPython: 8.12.2
sphinx: None

</details>

I also tried this on main at 3459e6fa, the behavior is the same.

**Comment by mgunyho** [comment]
Possibly related: https://github.com/pydata/xarray/discussions/7268

**Comment by Illviljan** [comment]
`dataset.plot.scatter `doesn't use `hue_style` anymore. 
`dataarray.plot.scatter` has never had `hue_style`.

I remember at some point there was handling for `hue_style` but it's seems I've lost it somewhere in the refactors to handle both categorical and numerics the same way. #4909, #6778
I suppose we could print a warning for the dataset version for a while since it was used a while ago.
It's unfortunate that the dataarray version's docstring suggests it's possible to use `hue_style`, a copy/paste error I guess.
 
The idea now is to just choose if you want a legend or a colorbar. You'll get something useful either way. You'll even get hue and sizes in 1 legend if you want that, something that was not previously possible.

Now numbers are considered continuous so if you want them to act as a categorical then switch them to string: 
```python
ds["color"] = ds["color"].astype(str)
ds.plot.scatter(x="x", y="y", hue="color", ax=plt.figure().gca())
```
![image](https://github.com/pydata/xarray/assets/14371165/bdfb7125-933e-4215-a928-9c438b20ce15)

Or if you just want a legend you use add_legend and remove the colorbar:
```python
ds.plot.scatter(
    x="x",
    y="y",
    hue="color",
    ax=plt.figure().gca(),
    add_legend=True,
    add_colorbar=False,
)
```
![image](https://github.com/pydata/xarray/assets/14371165/7ebbad28-ecd0-4380-999b-a514e0980cef)

xarray switches between 2 plotting colormaps, sequential or divergent. If you want a different colormap then you can use `xr.set_options(cmap_sequential = "inferno")`

https://github.com/pydata/xarray/blob/276b6bf22fdd5d6abeb6236b8e3c63e63049d44a/xarray/core/options.py#L164-L171

```python
ds["color"] = ds["color"].astype(str)
xr.set_options(cmap_sequential = "cool")
ds.plot.scatter(x="x", y="y", hue="color", ax=plt.figure().gca())
```
![image](https://github.com/pydata/xarray/assets/14371165/591d78f2-ed0f-4e16-abb8-8acabd29034d)

**Comment by mgunyho** [comment]
Thanks for the reply! So are you saying that the `hue_style` keyword should really be removed entirely, and this is just a mistake in the docs? That would make sense I guess, and my use case is really covered by `add_colorbar=False, add_legend=True`, even if that's quite a bit of typing. Maybe it feels a bit magical or inconsistent that string-valued coords create a discrete colorbar.

It was maybe a bit surprising to me that `hue` created a colorbar instead of legend because I was used to the line plot behavior. But it's understandable, because (dataset) scatter plots can have as many values for the hue as there are points.

I can try to submit a patch to remove (or deprecate for dataset) the `hue_style` option if you think it makes sense.

**Comment by mgunyho** [comment]
Oh, I see you started something along these lines in #7925
