### ISSUE TITLE
Upstream CI is failing

### ISSUE THREAD

**Issue by Illviljan** [pydata/xarray#7969]
### What happened?
The upstream CI has been failing for a while. Here's the latest:
https://github.com/pydata/xarray/actions/runs/5501368493/jobs/10024902009#step:7:16

```python
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/runner/work/xarray/xarray/xarray/__init__.py", line 1, in <module>
    from xarray import testing, tutorial
  File "/home/runner/work/xarray/xarray/xarray/testing.py", line 7, in <module>
    import numpy as np
ModuleNotFoundError: No module named 'numpy'
```

Digging a little in the logs
```
  Installing build dependencies: started
  Installing build dependencies: finished with status 'error'
  error: subprocess-exited-with-error
  
  × pip subprocess to install build dependencies did not run successfully.
  │ exit code: 1
  ╰─> [3 lines of output]
      Looking in indexes: https://pypi.anaconda.org/scipy-wheels-nightly/simple
      ERROR: Could not find a version that satisfies the requirement meson-python==0.13.1 (from versions: none)
      ERROR: No matching distribution found for meson-python==0.13.1
      [end of output]
```

Might be some numpy problem?

Should the CI be robust enough to handle these kinds of errors? Because I suppose we would like to get the automatic issue created anyway?

**Comment by keewis** [comment]
actually, no, that's not `numpy` but `pandas` that caused that issue... we're installing `pandas`, `numpy`, `matplotlib`, and `scipy` from the `scipy-wheels-nightly` repository, and apparently `pip` selects the source distribution of `pandas` and fails because the build dependencies cannot be satisfied.

I don't know why it selects the source dist, but the fix might be easy: switch to `scientific-python-nightly-wheels`, because apparently `pandas` doesn't publish to `scipy-wheels-nightly` anymore?

**Comment by keewis** [comment]
as for making CI emit an error in that case: yes, that would be ideal, but in that case we'd need to rethink our test workflow... we currently have a step that fails early in case
