### ISSUE TITLE
dictionaries in labeled indexing with letter values

### ISSUE THREAD

**Issue by oceanEngineer** [pydata/xarray#801]
An exception is raised when a letter is used in a dictionary as a labelled index. I believe this use of letter values is acceptable according to #291.

The error is:
```
ValueError: invalid literal for int() with base 10: 'b'
```
The work around is simple at least, the .loc keyword works as expected with dictionary labelled indexing.

```
test = np.random.randn(3, 3)
test_xr = xr.DataArray(test, coords=[[1, 2, 3], ['a', 'b', 'c']], dims=['inter', 'alpha'])
test_xr.loc[dict(inter=1)]
test_xr[dict(inter=1)]
test_xr.loc[dict(alpha='b')]
# Throws a ValueError exception
test_xr[dict(alpha='b')]
```

**Comment by shoyer** [comment]
`test_xr[dict(alpha='b')]` is equivalent to `text_xr[:, 'b']`, which raises because indexing in brackets in xarray is only by integer position, not label. See the third row in [the indexing summary table](http://xarray.pydata.org/en/stable/indexing.html#indexing-and-selecting-data) in the docs. Does that make sense?

**Comment by oceanEngineer** [comment]
Ah yes, that does make sense. I should have noticed that

``
test_xr.loc[dict(inter=1)] != test_xr[dict(inter=1)]
```

Thanks for your help.
