### ISSUE TITLE
Support rolling with numbagg

### ISSUE THREAD

**Issue by dcherian** [pydata/xarray#8337]
### Is your feature request related to a problem?

We can do plain reductions, and groupby reductions with numbagg. Rolling is the last one left!

I don't think coarsen will benefit since it's basically a reshape and reduce on that view, so it should already be accelerated. There may be small gains in handling the boundary conditions but that's probably it.

**Comment by max-sixty** [comment]
Yes, we can definitely do this! Need to write the routines (only have `move_mean` atm). 

But tbh that's the easy part (maybe the first huge benefit I've found from LLMs, fwiw)

**Comment by max-sixty** [comment]
Done in numbagg for all the easy ones — https://github.com/numbagg/numbagg/pull/174. So much faster than pandas. I can't actually test bottleneck locally, since it doesn't seem to compile on ARM... I can try and get it running on GHA (though the dev loops will be frustrating...)

Others like `move_nanmax` are actually not trivial, particularly with numba, which doesn't have the data structures to implement this; e.g. a dequeue. I'll think about it some more, ideas welcome!

@dcherian should we push this through flox? Or add to xarray directly from numbagg?

**Comment by max-sixty** [comment]
This is done!
