### ISSUE TITLE
Try to open .grb2 file in google colab

### ISSUE THREAD

**Issue by Victorrani** [pydata/xarray#8398]
### What is your issue?

im trying to open a .grb2 file using xarray. i already import cfgrib, xarray. 

Name: xarray
Version: 2023.10.1
Summary: N-D labeled arrays and datasets in Python

Name: cfgrib
Version: 0.9.10.4
Summary: Python interface to map GRIB files to the NetCDF Common Data Model following the CF Convention using ecCodes.

Name: eccodes
Version: 1.6.1
Summary: Python interface to the ecCodes GRIB and BUFR decoder/encoder

![image](https://github.com/pydata/xarray/assets/71741679/f5286d8f-8cae-45df-b869-9bdb68e0ec4b)

Should the error message be different?
what could be happening?

thanks

**Comment by keewis** [comment]
what this does tell you is that it can't find the `cfgrib` engine. Usually, this indicates an issue with your environment. Since you are able to import `cfgrib`, this would mean there's something wrong with its package metadata (where the entrypoints are stored) or the `entrypoint` mechanism.

Looking at your import path, you seem to have installed both using a linux distribution's package manager, is that right? If so, it would be best to ask the appropriate package maintainers for help.

**Comment by max-sixty** [comment]
Please reopen with a link to the notebook and `xr.show_versions()`
