### ISSUE TITLE
Unintuitive broadcasting behavior

### ISSUE THREAD

**Issue by v0lat1le** [pydata/xarray#840]
Using python 2.7.10, xarray 0.7.2

``` python
arr = xarray.DataArray(numpy.empty((3,3)), 
                       coords={'a':['a1', 'a2', 'a3'],
                               'b':['b1', 'b2', 'b3']},
                       dims=['a', 'b'])
arr.loc['a2':'a3'] = arr.loc['a1':'a2']*arr.loc['a1']
arr.loc['a2':'a3'] = arr.loc['a1']*arr.loc['a1':'a2']
```

First assignment statements succeeds, while the second one generates
`ValueError: could not broadcast input array from shape (3,2) into shape (2,3)`

I'd expect the multiplication not to swap the order of dimensions. But if it does, the assignment should be able to swap it back.

**Comment by shoyer** [comment]
In the second multiplication, you are multiplying an array with dimensions (b,) by one with dimensions (a,b). This results in something with dimensions (b,a), because we broadcast dimensions in order of appearance.

I agree that it would be nice to swap dimensions back in assignment, at least in this context. But I'll just note that we currently don't do *any* alignment of RHS arguments in assignment operations, so we would need to think about the full implications of doing such alignment.
