### ISSUE TITLE
more frequency string updates?

### ISSUE THREAD

**Issue by mathause** [pydata/xarray#8612]
### What is your issue?

I looked a bit into the frequency string update & found 3 issues we could improve upon.

1. Apart from `"M"`, pandas also deprecated `"Y"`, and `"Q"`, in favor of `"YE"` and `"QE"`. (And they are discussing renaming `"MS"` to `"MB"`). Should we do the same?

2. Should we translate the new freq strings to the old ones if pandas < 2.2 is installed? Otherwise  we get the following situation:
   ```python
   import xarray as xr
   xr.date_range("1600-02-01", periods=3, freq="M") # deprecation warning
   xr.date_range("1600-02-01", periods=3, freq="ME") # ValueError: Invalid frequency: ME
   ```

3. `date_range_like` can emit deprecation warnings without a way to mitigate them if pandas < 2.2 is installed. (When a `DatetimeIndex`) is passed. Could be nice to translate the old freq string to the new one without a warning.

I have played around with 2. and 3. and can open a PR if you are on board.

@spencerkclark @aulemahal 

- pandas-dev/pandas#55792
- pandas-dev/pandas#55553
- pandas-dev/pandas#56840

**Comment by max-sixty** [comment]
> * Should we translate the new freq strings to the old ones if pandas < 2.2 is installed? Otherwise  we get the following situation:
>   ```python
>   import xarray as xr
>   xr.date_range("1600-02-01", periods=3, freq="M") # deprecation warning
>   xr.date_range("1600-02-01", periods=3, freq="ME") # ValueError: Invalid frequency: ME
>   ```

No strong view, but if we're just more permissive — forwarding almost anything to pandas — this gets around the issue. And doesn't involve writing translation code that will be removed fairly soon.

**Comment by spencerkclark** [comment]
If I understand correctly, the issue @mathause is noting is a bit more subtle.  [We already do forward to pandas by default for the standard calendar](https://github.com/pydata/xarray/blob/35b7ab1c5158382336cfb631251b6da84619fe27/xarray/coding/cftime_offsets.py#L1223-L1239), but in this case pandas will raise an `OutOfBoundsDatetime` exception due to the start date being out range for nanosecond-precision datetimes.  We catch this and then fall back to using `cftime_range`, which is implemented in xarray.  For pandas < 2.2, passing `"ME"` as a frequency string will raise a `ValueError`, which short circuits this fallback logic, so in this narrow case it is not possible to address the deprecation warning emitted by xarray.

I think I am open to this, especially since we already introduced some translation logic as part of #8394; this refines that a bit more.  It is nice though that pandas 2.2 was just released yesterday, which makes this less of an issue.

**Comment by max-sixty** [comment]
> but in this case pandas will raise an `OutOfBoundsDatetime` exception due to the start date being out range for nanosecond-precision datetimes. We catch this and then fall back to using `cftime_range`, which is implemented in xarray.

👍 , thanks for the clear explanation

---

Could I ask how close we are to fixing the other string issues — e.g. `M` / `ME`? Those are the ones that break the doctests at the moment.

Should we ignore them in the doctests in the meantime? Or does changing the doctests to use the new string solve it?

**Comment by spencerkclark** [comment]
Indeed changing the doctests to use the new string should solve it (fortunately we don't have to worry about supporting multiple pandas versions there). I think this is already taken care of in https://github.com/pydata/xarray/pull/8638.
