### ISSUE TITLE
renaming index variables with `rename_vars` seems buggy

### ISSUE THREAD

**Issue by dcherian** [pydata/xarray#8659]
### What happened?

(xref #8658)

I'm not sure what the expected behaviour is here:

```python
import xarray as xr
import numpy as np
from xarray.testing import _assert_internal_invariants

ds = xr.Dataset()
ds.coords["1"] = ("1", np.array([1], dtype=np.uint32))
ds["1_"] = ("1", np.array([1], dtype=np.uint32))
ds = ds.rename_vars({"1": "0"})
ds
```

It looks like this sequence of operations creates a default index
<img width="728" alt="image" src="https://github.com/pydata/xarray/assets/2448579/3fc15f20-d7b5-43bf-854c-313216437730">

But then 
```python
from xarray.testing import _assert_internal_invariants

_assert_internal_invariants(ds, check_default_indexes=True)
```
fails with
```
...
File ~/repos/xarray/xarray/testing/assertions.py:301, in _assert_indexes_invariants_checks(indexes, possible_coord_variables, dims, check_default)
    299 if check_default:
    300     defaults = default_indexes(possible_coord_variables, dims)
--> 301     assert indexes.keys() == defaults.keys(), (set(indexes), set(defaults))
    302     assert all(v.equals(defaults[k]) for k, v in indexes.items()), (
    303         indexes,
    304         defaults,
    305     )

AssertionError: ({'0'}, set())
```

**Comment by benbovy** [comment]
That looks right to me.

- `ds.coords["1"] = ("1", np.array([1], dtype=np.uint32))` creates an index by default (setting a dimension coordinate)
- since the index refactor `ds = ds.rename_vars({"1": "0"})` preserves the coordinate index
- `_assert_internal_invariants(ds, check_default_indexes=True)` fails as expected (presence of a non-dimension index after renaming the coordinate "1" -> "0".
