### ISSUE TITLE
Errors started appearing after release v2024.02.0

### ISSUE THREAD

**Issue by navidcy** [pydata/xarray#8769]
### What happened?

I started seeing errors in my CI after [latest xarray release](https://github.com/pydata/xarray/releases/tag/v2024.02.0). See, e.g.,

https://github.com/COSIMA/regional-mom6/actions/runs/7957078139/job/21719091616#step:7:226

After I added a [compat for xarray](https://github.com/COSIMA/regional-mom6/pull/98/commits/46ca91d2ac91ab57371f94108f18549aaa7040cf) to preclude the latest release the error went away. See:

https://github.com/COSIMA/regional-mom6/actions/runs/7957192738

### MVCE confirmation

- [ ] Minimal example — the example is as focused as reasonably possible to demonstrate the underlying issue in xarray.
- [ ] Complete example — the example is self-contained, including all data and the text of any traceback.
- [ ] Verifiable example — the example copy & pastes into an IPython prompt or [Binder notebook](https://mybinder.org/v2/gh/pydata/xarray/main?urlpath=lab/tree/doc/examples/blank_template.ipynb), returning the result.
- [x] New issue — a search of GitHub Issues suggests this is not a duplicate.
- [X] Recent environment — the issue occurs with the latest version of xarray and its dependencies.

### Environment

<details>

</details>

**Comment by angus-g** [comment]
This issue is actually coming from the downstream xESMF library, see relevant issue there: https://github.com/pangeo-data/xESMF/issues/338

**Comment by TomNicholas** [comment]
Importing code directly from `xarray.core` is [explicitly not supported](https://docs.xarray.dev/en/stable/getting-started-guide/faq.html#what-parts-of-xarray-are-considered-public-api), and if you do it your code could potentially break on any new commit to xarray - there is no guarantee of stability.

We're happy to help advise on how to restructure your code so as not to rely on `xarray.core` directly - in this case it looks like the fix was pretty simple.

**Comment by dcherian** [comment]
hehe this was my fault in cf-xarray :) sorry!
