### ISSUE TITLE
BUG: Dataset constructor puts lists in coords rather that data_vars

### ISSUE THREAD

**Issue by max-imlian** [pydata/xarray#890]
I'd expect `a` to be a data_vars rather than a coord here:

``` python
In [9]: xr.Dataset(data_vars={'a': [2,3]}, attrs={'name':'hello'})
Out[9]: 
<xarray.Dataset>
Dimensions:  (a: 2)
Coordinates:
  * a        (a) int64 2 3
Data variables:
    *empty*
Attributes:
    name: hello
```

**Comment by shoyer** [comment]
This may not be clearly documented, but it is/was intentional behavior.

To be clear, there are two things going on here:

1. Arguments like `{'a': [2, 3]}` get implicit dimensions added, e.g., `{'a': ('a', [2, 3])}`.
2. 1D `data_vars` arguments which have the same name as their sole argument are converted in `coords`.

Originally, this made sense because we didn't have a separate `coords` argument. Now, this could simply be passed as `coords` instead, which is certainly more explicit. So instead of allowing this we could raise an error. My concern such a deprecation this is that (1) there's a lot of code written with the assumption that this works and (2) there's not much be to be gained -- there's nothing else that we could sensibly use this syntax for, and (3) this is marginally convenient, allowing for slightly less typing (one less pair of curly braces).

**Comment by max-imlian** [comment]
Closing - while the behavior could be surprising at first glance, for @shoyer 's reasons above: not much to gain from changes
