### ISSUE TITLE
Pickle and .value vs. dask backend

### ISSUE THREAD

**Issue by crusaderky** [pydata/xarray#902]
Pickling a xarray.DataArray with dask backend will cause it to resolve the .data to a numpy array.
This is not desirable, as there's legitimate use cases where you may want to e.g. save a computation for later, or send it somewhere across the network.

Analogously, auto-converting a dask xarray to a numpy xarray as soon as you invoke the .value property is probably nice when you are working on a jupyter terminal, but not in a general purpose situation, particularly when xarray is used at the foundation of a very complex framework. Most of my headaches so far have been caused trying to figure out when, where and why the dask backend was replaced with numpy.

IMHO a module-wide switch to disable implicit dask->numpy conversion would be a nice solution.
A new method, compute(), could explicitly convert in place from dask to numpy.

**Comment by shoyer** [comment]
I agree about loading data into memory automatically -- this behavior made sense *before* we used dask in xarray, but now it doesn't really.

We actually already have a `.load()` method for explicitly loading data into memory, though it might make sense to add `.compute()` as an alias, possibly without modifying the original dataset inplace.

I'm a little less certain about how to handle pickling data, because anytime you open a file from disk using `open_dataset` it's not going to pickle. But on the other hand, it's also not hard to explicitly write `.load()` or `.compute()` before using pickle or invoking multiprocessing.

**Comment by crusaderky** [comment]
I'm happy to look into this - could you point me in the right direction?

**Comment by shoyer** [comment]
This is where you can find the core caching logic on Variable objects:
https://github.com/pydata/xarray/blob/56abba54ca4e89af570fd9cacc8f3ffcf5a5c4c7/xarray/core/variable.py#L257-L305

Here's where we define `load` on Dataset and DataArray:
https://github.com/pydata/xarray/blob/56abba54ca4e89af570fd9cacc8f3ffcf5a5c4c7/xarray/core/dataset.py#L305-L327
https://github.com/pydata/xarray/blob/56abba54ca4e89af570fd9cacc8f3ffcf5a5c4c7/xarray/core/dataarray.py#L523-L536

As I mentioned before, let's add `.compute()` to evaluate and return a new object, and use it for `.values` instead of caching. `.load()` can remain unchanged for when users actually want to cache data. And we can definitely disable automatically loading data in pickles.

**Comment by crusaderky** [comment]
Working on it now.
What I didn't understand is if you want to disable caching for all backends (NetCDF etc.) or only for dask?
The change for dask only is very straightforward. For all backends much less so...

**Comment by shoyer** [comment]
@crusaderky Let's just disable caching for dask.

**Comment by crusaderky** [comment]
I'm done... I think. The result is less clean than I would have hoped - suggestions are welcome.
https://github.com/pydata/xarray/pull/1018
