### ISSUE TITLE
Combine `UnsignedIntegerCoder` and `CFMaskCoder`

### ISSUE THREAD

**Issue by dcherian** [pydata/xarray#9266]
### What is your issue?

Longer discussion here: https://github.com/pydata/xarray/pull/9258#discussion_r1686731537 but fundamentally, it's not possible to handle the `_Unsigned` attribute and masking separately so we'll need to merge these.

@djhoese will you be able to send a PR for this please?

**Comment by djhoese** [comment]
I will try my best, but no guarantees on timeliness. I'll mostly be using this as yet another source of procrastination on the work I'm supposed to be doing. Anyway...

I think the high-level summary of our discussion on my PR (#9258) and the PR that came before it (#9136) as far as changes needed are:

1. `_FillValue` as far as the user is concerned should always be the on-disk type. For the case where `_Unsigned: "true"` that means it will be signed; even in-memory. This means it will not always match the dtype of the data array it is attached/assigned to.
2. Absorb the `UnsignedIntegerCoder` into the `CFMaskCoder` (or some logical not-too-long rename) so that `_FillValue` can be decoded to unsigned type if necessary, used for masking, and then discarded in favor of CF compliance and retaining the on-disk type of the `_FillValue` attribute.
3. If it makes sense, add a serialization warning when in-memory `_FillValue`s go through the encode process and they do not already match the on-disk dtype. For example, a uint8 DataArray with `FillValue` of 255, but is going to be saved to a NetCDF file as an int8 variable via `_Unsigned: "true"`. 255 can be converted to a signed int8, but it will result in a warning as -1 should have been used instead.

@dcherian you seemed to know that xarray can't load integer arrays as integers and instead produces floats. Is this by design or something that is too complicated to fix?

**Comment by keewis** [comment]
> you seemed to know that xarray can't load integer arrays as integers and instead produces floats. Is this by design or something that is too complicated to fix?

The reason for this is that there is no representation for masked arrays with dtypes other than `complex` and `float` (and the new `string` dtype) that support masked values – and `complex` and `float` reuse `nan` for this, which actually means something else. Obviously that also means that if you don't need to apply `_FillValue` the conversion does not happen.

The logic is here: https://github.com/pydata/xarray/blob/ad35a1059f0d10c29f9ed28bc87192b6b88b6cb3/xarray/core/dtypes.py#L49-L88

To fix that we need one of (or both):
- a `maskedarray` implementation that behaves like a normal array (for example [marray](https://github.com/mdhaber/marray/))
- truly nullable dtypes

Both of these are sufficiently hard to get right that nothing other than the pandas extension dtypes exist (that I'm aware of).

**Comment by djhoese** [comment]
Well it seems obvious when you say it like that :wink: 

Ok so I was focused on the encoding/decoding of dtypes, but it is more about the masking and operations that need to know the validity of a value. So while I might know that my data quality flag that is uint8 where a value of 1 means "bad"/mask, that doesn't mean that any numpy operation will know that even though I probably wouldn't use the variable in normal arithmetic operations anyway.

**Comment by djhoese** [comment]
FYI I'm almost done with this at least as a first draft. I'll need to clean it up a lot as right now it is mostly a copy/paste job. Right now I'm just trying to get tests to pass and make sense. The hardest part is figuring out when things should be in `.encoding` and when they should be in `.attrs`, but I'm almost there.

**Comment by dcherian** [comment]
Closed by #9274
