### ISSUE TITLE
dims instead of dimensions!?

### ISSUE THREAD

**Issue by ocehugo** [pydata/xarray#949]
Hello, just wondering why there is such a difference in the method/dict from netCDF4. It's on purpose to break compatibility with netCDF4 because of some particular difference or a matter of taste? I don't know but looks like I saw that somewhere but couldn't find...

I'm just porting some functions to accept xarray, but some of them  use/access explicitly the dimensions method of a dataset. Should i keep doing this:

```python
xrobj.__setitem__('dimensions',dims)
```

to support both inputs ? or anywhere in the api the dimensions keyword is used somehow or planned?

**Comment by shoyer** [comment]
We never intended for `xarray.Dataset` to be a drop in replacement for `netCDF4.Dataset`, because we wanted a more succinct and expressive API like pandas.

You can certainly access `xarray.Dataset.dims` and `xarray.Dataset.variables` like the `netCDF4.Dataset` attributes, but they aren't necessary for most uses in xarray. In particular, note that [`xarray.Dataset.variables`](http://xarray.pydata.org/en/stable/internals.html#variable-objects) is a low level API intended for developers. Generally, you should just index the Dataset itself.

**Comment by ocehugo** [comment]
@shoyer, yes but at the end of the day it's kind off a substitute, particularly with large datasets and dask support. I didn't find (yet) how to not use them since still very attach to netCDF4 api and the verbosity it requires (there is always a new api to learn and not enough time ;)) but i was just trying to quick port some of my discovery functions to slowly change to xarray and was getting AttributeError all over the place. 

cheers
