### ISSUE TITLE
BUG: Repr on inherited classes is incorrect

### ISSUE THREAD

**Issue by max-sixty** [pydata/xarray#957]
This is extremely minor, I generally wouldn't report it.

We're using classes inherited from `Dataset` more & more - this works really well for classes with a lot of array-like properties that can be aligned, and allows `@property` to lazily compute some calcs. (any feedback on this approach very welcome)

The top of the repr is incorrect

``` python
<xarray.SecurityMeasure>
Dimensions:         (date: 6647, security: 285, sub_measure: 4)
Coordinates:
...
```

Could just be the qualified name.

**Comment by shoyer** [comment]
I would be interested to know if registering an accessor works for you, which was designed for exactly this sort of use case:
http://xarray.pydata.org/en/stable/internals.html#extending-xarray

The reason why I chose not to just use the qualified name is that `xarray.core.dataset.Dataset` is a little long, and also points users in the direction of private API.

But I'd be happy to use qualified names for subclasses not builtin to xarray. Currently you can find this logic in `dataset_repr` and `array_repr` at the bottom of core/formatting.py. You'd just need to write a helper function to calculate the class name rather than our current use of `u'<xarray.%s>' % type(ds).__name__`.

**Comment by MaximilianR** [comment]
> I would be interested to know if registering an accessor works

Yes I knew about that. Our use case is a bit different - rather than add a property to all `Dataset`s is the environment, we want to do it to specific classes. 
We used to have a class that had an underlying `Dataset` (or many `DataFrame`s) and then offered accessor properties on top. So the current solution is a bit nicer, in that it integrates those two objects (the custom class and the underlying `Dataset`) into one
Numerical operations probably aren't reliable, but that's OK for us
